package com.cricketcraft.chisel.client;

import static com.cricketcraft.chisel.block.variant.BlockVariants.*;
import net.minecraft.block.Block;
import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.model.ModelBakery;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

import com.cricketcraft.chisel.Chisel;
import com.cricketcraft.chisel.init.ChiselBlocks;
import com.cricketcraft.chisel.init.ChiselItems;
import com.cricketcraft.chisel.util.IItemWithVariants;

@SideOnly(Side.CLIENT)
public class ModelsChisel {
	public static void prepareModels() {
		addVariantNames(ChiselBlocks.acacia, ACACIA_PLANKS_SMOOTH.getName(), ACACIA_PLANKS_SHORT.getName(), ACACIA_PLANKS_FANCY.getName(), ACACIA_PLANKS_PANEL.getName(), ACACIA_PLANKS_DOUBLE_SLAB.getName(), ACACIA_PLANKS_CRATE.getName(), ACACIA_PLANKS_CRATE_FANCY.getName(), ACACIA_PLANKS_LONG.getName(), ACACIA_PLANKS_VERTICAL.getName(), ACACIA_PLANKS_VERTICAL_UNEVEN.getName(), ACACIA_PLANKS_PARQUET.getName(), ACACIA_PLANKS_BLINDS.getName(), ACACIA_PLANKS_SCAFFOLD.getName(), ACACIA_PLANKS_DISARRAY.getName(), ACACIA_PLANKS_DISARRAY_VERTICAL.getName());
		addVariantNames(ChiselBlocks.aluminum, ALUMINUM_CAUTION.getName(), ALUMINUM_SHIPPING.getName(), ALUMINUM_THERMAL.getName(), ALUMINUM_125.getName(), ALUMINUM_BORDERED.getName(), ALUMINUM_BOLTED.getName());
		addVariantNames(ChiselBlocks.andesite, ANDESITE_PILLAR.getName(), ANDESITE_BRICKS.getName(), ANDESITE_ORNATE.getName(), ANDESITE_PRISMATIC.getName(), ANDESITE_TILES_SMALL.getName());
		addVariantNames(ChiselBlocks.antiblock, ANTIBLOCK_0.getName(), ANTIBLOCK_1.getName(), ANTIBLOCK_2.getName(), ANTIBLOCK_3.getName(), ANTIBLOCK_4.getName(), ANTIBLOCK_5.getName(), ANTIBLOCK_6.getName(), ANTIBLOCK_7.getName(), ANTIBLOCK_8.getName(), ANTIBLOCK_9.getName(), ANTIBLOCK_10.getName(), ANTIBLOCK_11.getName(), ANTIBLOCK_12.getName(), ANTIBLOCK_13.getName(), ANTIBLOCK_14.getName(), ANTIBLOCK_15.getName());
		addVariantNames(ChiselBlocks.birch, BIRCH_PLANKS_SMOOTH.getName(), BIRCH_PLANKS_SHORT.getName(), BIRCH_PLANKS_FANCY.getName(), BIRCH_PLANKS_PANEL.getName(), BIRCH_PLANKS_DOUBLE_SLAB.getName(), BIRCH_PLANKS_CRATE.getName(), BIRCH_PLANKS_CRATE_FANCY.getName(), BIRCH_PLANKS_LONG.getName(), BIRCH_PLANKS_VERTICAL.getName(), BIRCH_PLANKS_VERTICAL_UNEVEN.getName(), BIRCH_PLANKS_PARQUET.getName(), BIRCH_PLANKS_BLINDS.getName(), BIRCH_PLANKS_SCAFFOLD.getName(), BIRCH_PLANKS_DISARRAY.getName(), BIRCH_PLANKS_DISARRAY_VERTICAL.getName());
		addVariantNames(ChiselBlocks.bookshelf, BOOKSHELF_RAINBOW.getName(), BOOKSHELF_NECROMANCER_APPRENTICE.getName(), BOOKSHELF_NECROMANCER.getName(), BOOKSHELF_TOMES.getName(), BOOKSHELF_ABANDONED.getName(), BOOKSHELF_HOARDERS.getName(), BOOKSHELF_PASTEL.getName(), BOOKSHELF_HISTORIAN.getName());
		addVariantNames(ChiselBlocks.bricks, BRICKS_LARGE.getName(), BRICKS_MORTARLESS.getName(), BRICKS_VARIED.getName(), BRICKS_AGED.getName(), BRICKS_YELLOW.getName());
		addVariantNames(ChiselBlocks.bronze, BRONZE_CAUTION.getName(), BRONZE_SHIPPING.getName(), BRONZE_THERMAL.getName(), BRONZE_125.getName(), BRONZE_BORDERED.getName(), BRONZE_BOLTED.getName());
		addVariantNames(ChiselBlocks.carpet, CARPET_0.getName(), CARPET_1.getName(), CARPET_2.getName(), CARPET_3.getName(), CARPET_4.getName(), CARPET_5.getName(), CARPET_6.getName(), CARPET_7.getName(), CARPET_8.getName(), CARPET_9.getName(), CARPET_9.getName(), CARPET_10.getName(), CARPET_11.getName(), CARPET_12.getName(), CARPET_13.getName(), CARPET_14.getName(), CARPET_15.getName());
		addVariantNames(ChiselBlocks.carpet_floor, CARPET_FLOOR_0.getName(), CARPET_FLOOR_1.getName(), CARPET_FLOOR_2.getName(), CARPET_FLOOR_3.getName(), CARPET_FLOOR_4.getName(), CARPET_FLOOR_5.getName(), CARPET_FLOOR_6.getName(), CARPET_FLOOR_7.getName(), CARPET_FLOOR_8.getName(), CARPET_FLOOR_9.getName(), CARPET_FLOOR_10.getName(), CARPET_FLOOR_11.getName(), CARPET_FLOOR_12.getName(), CARPET_FLOOR_13.getName(), CARPET_FLOOR_14.getName(), CARPET_FLOOR_15.getName());
		addVariantNames(ChiselBlocks.chest, CHEST_0.getName(), CHEST_1.getName(), CHEST_2.getName(), CHEST_3.getName(), CHEST_4.getName(), CHEST_5.getName(), CHEST_6.getName(), CHEST_7.getName(), CHEST_8.getName(), CHEST_9.getName(), CHEST_10.getName(), CHEST_11.getName(), CHEST_12.getName(), CHEST_13.getName(), CHEST_14.getName(), CHEST_15.getName());
		addVariantNames(ChiselBlocks.cobblestone, COBBLESTONE_BRICKS_ALIGNED.getName(), COBBLESTONE_BRICKS_DETAILED.getName(), COBBLESTONE_BRICKS_SMALL.getName(), COBBLESTONE_TILES_LARGE.getName(), COBBLESTONE_TILES_SMALL.getName(), COBBLESTONE_TILES_FRENCH.getName(), COBBLESTONE_TILES_FRENCH_LIGHT.getName(), COBBLESTONE_TILES_CREEPER.getName(), COBBLESTONE_TILES_DAMAGED.getName(), COBBLESTONE_TILES_HUGE.getName(), COBBLESTONE_PANEL_CREEPER.getName(), COBBLESTONE_DENT.getName(), COBBLESTONE_PANEL.getName(), COBBLESTONE_PANEL_LIGHT.getName(), COBBLESTONE_PANEL_DARK.getName());
		addVariantNames(ChiselBlocks.concrete, CONCRETE_RAW.getName(), CONCRETE_BLOCK.getName(), CONCRETE_SLAB.getName(), CONCRETE_BLOCKS.getName(), CONCRETE_RAW_WEATHERED.getName(), CONCRETE_BLOCK_WEATHERED.getName(), CONCRETE_SLAB_WEATHERED.getName(), CONCRETE_BLOCK_WEATHERED.getName(), CONCRETE_RAW_PARTLY.getName(), CONCRETE_BLOCK_PARTLY.getName(), CONCRETE_ASPHALT.getName());
		addVariantNames(ChiselBlocks.copper, COPPER_CAUTION.getName(), COPPER_SHIPPING.getName(), COPPER_THERMAL.getName(), COPPER_125.getName(), COPPER_BORDERED.getName(), COPPER_BOLTED.getName());
		addVariantNames(ChiselBlocks.cloud, CLOUD_NORMAL.getName(), CLOUD_GRID.getName(), CLOUD_LARGE.getName(), CLOUD_SMALL.getName(), CLOUD_VERTICAL.getName());
		addVariantNames(ChiselBlocks.dark_oak, DARK_OAK_PLANKS_SMOOTH.getName(), DARK_OAK_PLANKS_SHORT.getName(), DARK_OAK_PLANKS_FANCY.getName(), DARK_OAK_PLANKS_PANEL.getName(), DARK_OAK_PLANKS_DOUBLE_SLAB.getName(), DARK_OAK_PLANKS_CRATE.getName(), DARK_OAK_PLANKS_CRATE_FANCY.getName(), DARK_OAK_PLANKS_LONG.getName(), DARK_OAK_PLANKS_VERTICAL.getName(), DARK_OAK_PLANKS_VERTICAL_UNEVEN.getName(), DARK_OAK_PLANKS_PARQUET.getName(), DARK_OAK_PLANKS_BLINDS.getName(), DARK_OAK_PLANKS_SCAFFOLD.getName(), DARK_OAK_PLANKS_DISARRAY.getName(), DARK_OAK_PLANKS_DISARRAY_VERTICAL.getName());
		addVariantNames(ChiselBlocks.diamond, DIAMOND_EMBOSSED.getName(), DIAMOND_PANEL.getName(), DIAMOND_CELLS.getName(), DIAMOND_OBSIDIAN_PURPLE.getName(), DIAMOND_OBSIDIAN.getName(), DIAMOND_SIMPLE.getName(), DIAMOND_BISMUTH.getName(), DIAMOND_CRUSHED.getName(), DIAMOND_SMALL_BLOCKS.getName(), DIAMOND_SMALL_BLOCKS_ORNATE.getName(), DIAMOND_ZELDA.getName(), DIAMOND_ORNATE.getName());
		addVariantNames(ChiselBlocks.diorite, DIORITE_POLISHED.getName(), DIORITE_PILLAR.getName(), DIORITE_BRICKS.getName(), DIORITE_ORNATE.getName(), DIORITE_PRISMATIC.getName(), DIORITE_TILES_SMALL.getName());
		addVariantNames(ChiselBlocks.dirt, DIRT_BRICKS_DISARRAY.getName(), DIRT_NETHER.getName(), DIRT_BRICKS.getName(), DIRT_COBBLE.getName(), DIRT_COBBLE_REINFORCED.getName(), DIRT_REINFORCED.getName(), DIRT_HAPPY.getName(), DIRT_BRICKS_LARGE.getName(), DIRT_BRICKS_LARGE_ON.getName(), DIRT_HORIZONTAL.getName(), DIRT_VERTICAL.getName(), DIRT_LAYERS.getName(), DIRT_CRUMBLING.getName());
		addVariantNames(ChiselBlocks.emerald, EMERALD_PANEL.getName(), EMERALD_PANEL_CLASSIC.getName(), EMERALD_SMOOTH.getName(), EMERALD_CHUNK.getName(), EMERALD_ORNATE_LAYER.getName(), EMERALD_ZELDA.getName(), EMERALD_CELL.getName(), EMERALD_BISMUTH.getName(), EMERALD_BLOCKS_SMALL.getName(), EMERALD_BLOCKS_SMALL_ORNATE.getName(), EMERALD_ORNATE.getName());
		addVariantNames(ChiselBlocks.energised_voidstone, ENERGISED_VOIDSTONE_RAW.getName(), ENERGISED_VOIDSTONE_TILES.getName(), ENERGISED_VOIDSTONE_SMOOTH.getName(), ENERGISED_VOIDSTONE_SKULL.getName(), ENERGISED_VOIDSTONE_RUNIC.getName(), ENERGISED_VOIDSTONE_RUNIC.getName(), ENERGISED_VOIDSTONE_METAL.getName(), ENERGISED_VOIDSTONE_EYE.getName(), ENERGISED_VOIDSTONE_BEVEL.getName());
		addVariantNames(ChiselBlocks.energised_voidstone_pillar, ENERGISED_VOIDSTONE_PILLAR_NORMAL.getName());
		addVariantNames(ChiselBlocks.factory, FACTORY_RUSTY_DOTTED.getName(), FACTORY_RUSTY_PLATE.getName(), FACTORY_RUSTY_VERY.getName(), FACTORY_RUSTY_LITTLE.getName(), FACTORY_WIREFRAME.getName(), FACTORY_WIREFRAME.getName(), FACTORY_WIREFRAME_PURPLE.getName(), FACTORY_HAZARD_YELLOW.getName(), FACTORY_HAZARD_ORANGE.getName(), FACTORY_CIRCUIT_FANCY.getName(), FACTORY_METAL.getName(), FACTORY_GOLD_CIRCUIT.getName(), FACTORY_GOLD_PURPLE.getName(), FACTORY_CONSTRUCTION.getName(), FACTORY_VENT_WORN.getName(), FACTORY_RUSTY_PLATES.getName(), FACTORY_COLUMN.getName(), FACTORY_BLUE.getName(), FACTORY_VENT_VERTICAL.getName(), FACTORY_CIRCUIT_BLUE.getName(), FACTORY_WIREFRAME_BLUE.getName());
		addVariantNames(ChiselBlocks.fantasy, FANTASY_BRICK.getName(), FANTASY_BRICK_FADED.getName(), FANTASY_BRICK_WORN.getName(), FANTASY_BRICK_DAMAGED.getName(), FANTASY_DECORATION.getName(), FANTASY_DECORATION_BLOCK.getName(), FANTASY_DECORATION_PILLAR.getName(), FANTASY_PILLAR.getName(), FANTASY_DECORATION_SNAKE.getName(), FANTASY_DECORATION_NOISE.getName(), FANTASY_DECORATION_ENGRAVING.getName(), FANTASY_DECORATION_CHAINS.getName(), FANTASY_DECORATION_PLATE.getName(), FANTASY_BLOCK.getName(), FANTASY_BRICKS_DISARRAY.getName(), FANTASY_BRICKS_DISARRAY_WORN.getName());
		addVariantNames(ChiselBlocks.futura, FUTURA_SCREEN_GRAY.getName(), FUTURA_SCREEN_CYAN.getName(), FUTURA_CONTROLLER.getName(), FUTURA_CONTROLLER_PURPLE.getName(), FUTURA_RAINBOW.getName());
		addVariantNames(ChiselBlocks.glass, GLASS_BUBBLE.getName(), GLASS_CHINESE.getName(), GLASS_JAPANESE.getName(), GLASS_DUNGEON.getName(), GLASS_LIGHT.getName(), GLASS_BORDERLESS.getName(), GLASS_SCREEN.getName(), GLASS_SHALE.getName(), GLASS_STEEL.getName(), GLASS_STONE.getName(), GLASS_GRID_THICK.getName(), GLASS_GRID_THIN.getName(), GLASS_FENCE.getName(), GLASS_LEADED.getName());
		addVariantNames(ChiselBlocks.glass_pane, GLASS_PANE_BUBBLE.getName(), GLASS_PANE_CHINESE.getName(), GLASS_PANE_JAPANESE.getName(), GLASS_PANE_DUNGEON.getName(), GLASS_PANE_LIGHT.getName(), GLASS_PANE_BORDERLESS.getName(), GLASS_PANE_SCREEN.getName(), GLASS_PANE_SHALE.getName(), GLASS_PANE_STEEL.getName(), GLASS_PANE_STONE.getName(), GLASS_PANE_GRID_THICK.getName(), GLASS_PANE_GRID_THIN.getName(), GLASS_PANE_FENCE.getName(), GLASS_PANE_LEADED.getName());
		addVariantNames(ChiselBlocks.glowstone, GLOWSTONE_COBBLE.getName(), GLOWSTONE_CORRODED.getName(), GLOWSTONE_NEON.getName(), GLOWSTONE_ORNATE.getName(), GLOWSTONE_ROCKY.getName(), GLOWSTONE_SHALE.getName(), GLOWSTONE_TILES.getName(), GLOWSTONE_FANCY.getName(), GLOWSTONE_CRUMBLING.getName(), GLOWSTONE_ORGANIC.getName(), GLOWSTONE_LAYERS.getName(), GLOWSTONE_CORRODED_TILES.getName(), GLOWSTONE_BISMUTH.getName(), GLOWSTONE_BISMUTH_PANEL.getName());
		addVariantNames(ChiselBlocks.gold, GOLD_INGOTS_LARGE.getName(), GOLD_INGOTS_SMALL.getName(), GOLD_BRICKS.getName(), GOLD_CART.getName(), GOLD_COIN_HEADS.getName(), GOLD_COIN_TAILS.getName(), GOLD_CRATE_DARK.getName(), GOLD_CRATE_LIGHT.getName(), GOLD_PLATES.getName(), GOLD_RIVETS.getName(), GOLD_STAR_DECOR.getName(), GOLD_STAR_OBSIDIAN_PURPLE.getName(), GOLD_STAR_OBSIDIAN.getName(), GOLD_SIMPLE.getName(), GOLD_CAUTION.getName(), GOLD_SHIPPING.getName(), GOLD_THERMAL.getName(), GOLD_125.getName(), GOLD_BORDERED.getName(), GOLD_BOLTED.getName());
		addVariantNames(ChiselBlocks.granite, GRANITE_POLISHED.getName(), GRANITE_PILLAR.getName(), GRANITE_BRICKS.getName(), GRANITE_ORNATE.getName(), GRANITE_PRISMATIC.getName(), GRANITE_TILES_SMALL.getName());
		addVariantNames(ChiselBlocks.grimstone, GRIMSTONE_RAW.getName(), GRIMSTONE_SMOOTH.getName(), GRIMSTONE_SYMBOL.getName(), GRIMSTONE_CHISELED.getName(), GRIMSTONE_BLOCKS.getName(), GRIMSTONE_BLOCKS_ROUGH.getName(), GRIMSTONE_BRICKS.getName(), GRIMSTONE_BRICKS_LARGE.getName(), GRIMSTONE_PLATFORM.getName(), GRIMSTONE_PLATFORM_TILES.getName(), GRIMSTONE_CONSTRUCTION.getName(), GRIMSTONE_TILES.getName(), GRIMSTONE_PLATE_SMOOTH.getName(), GRIMSTONE_PLATE.getName(), GRIMSTONE_FLAKY.getName());
		addVariantNames(ChiselBlocks.hex_plating, HEX_PLATING_0.getName(), HEX_PLATING_1.getName(), HEX_PLATING_2.getName(), HEX_PLATING_3.getName(), HEX_PLATING_4.getName(), HEX_PLATING_5.getName(), HEX_PLATING_6.getName(), HEX_PLATING_7.getName(), HEX_PLATING_8.getName(), HEX_PLATING_9.getName(), HEX_PLATING_10.getName(), HEX_PLATING_11.getName(), HEX_PLATING_12.getName(), HEX_PLATING_13.getName(), HEX_PLATING_14.getName(), HEX_PLATING_15.getName());
		addVariantNames(ChiselBlocks.holystone, HOLYSTONE_RAW.getName(), HOLYSTONE_SMOOTH.getName(), HOLYSTONE_SYMBOL.getName(), HOLYSTONE_CHISELED.getName(), HOLYSTONE_BLOCKS.getName(), HOLYSTONE_BLOCKS_ROUGH.getName(), HOLYSTONE_BRICKS.getName(), HOLYSTONE_BRICKS_LARGE.getName(), HOLYSTONE_PLATFORM.getName(), HOLYSTONE_PLATFORM_TILES.getName(), HOLYSTONE_CONSTRUCTION.getName(), HOLYSTONE_TILES.getName(), HOLYSTONE_PLATE_SMOOTH.getName(), HOLYSTONE_PLATE.getName());
		addVariantNames(ChiselBlocks.ice, ICE_ROUGH.getName(), ICE_COBBLE.getName(), ICE_ROUGH_LARGE.getName(), ICE_BRICKS_LARGE.getName(), ICE_BRICKS_SMALL.getName(), ICE_GLASS_WALL.getName(), ICE_TILES_LARGE.getName(), ICE_TILES_FANCY.getName(), ICE_TILES_SUNKEN.getName(), ICE_TILES_DISORDERED.getName(), ICE_PANEL.getName(), ICE_DOUBLE_SLAB.getName(), ICE_ZELDA.getName(), ICE_BISMUTH.getName(), ICE_POISON.getName());
		addVariantNames(ChiselBlocks.ice_pillar, ICE_PILLAR_PLAIN_PLAIN.getName(), ICE_PILLAR_PLAIN_GREEK.getName(), ICE_PILLAR_GREEK_PLAIN.getName(), ICE_PILLAR_GREEK_GREEK.getName(), ICE_PILLAR_CARVED.getName(), ICE_PILLAR_ORNAMENTAL.getName(), ICE_PILLAR_INSCRIBED.getName());
		addVariantNames(ChiselBlocks.imperial, IMPERIAL_CAMO.getName(), IMPERIAL_CAMO_SECLUDED.getName(), IMPERIAL_BOLT.getName(), IMPERIAL_CAUTION_WHITE.getName(), IMPERIAL_CAUTION_TEAM.getName());
		addVariantNames(ChiselBlocks.industrial, INDUSTRIAL_FAN.getName(), INDUSTRIAL_PLATING.getName());
		addVariantNames(ChiselBlocks.iron, IRON_INGOTS_LARGE.getName(), IRON_INGOTS_SMALL.getName(), IRON_GEARS.getName(), IRON_BRICKS.getName(), IRON_PLATES.getName(), IRON_COIN_HEADS.getName(), IRON_COIN_TAILS.getName(), IRON_CRATE_DARK.getName(), IRON_CRATE_LIGHT.getName(), IRON_MOON_DECOR.getName(), IRON_MOON_OBSIDIAN_PURPLE.getName(), IRON_MOON_OBSIDIAN.getName(), IRON_VENTS.getName(), IRON_SIMPLE.getName(), IRON_CAUTION.getName(), IRON_SHIPPING.getName(), IRON_THERMAL.getName(), IRON_125.getName(), IRON_BORDERED.getName(), IRON_BOLTED.getName());
		addVariantNames(ChiselBlocks.iron_bars, IRON_BARS_NO_FRAME.getName(), IRON_BARS_MENACING.getName(), IRON_BARS_CAGE.getName(), IRON_BARS_MENACING_SPIKES.getName(), IRON_BARS_GRID_THICK.getName(), IRON_BARS_GRID_THIN.getName(), IRON_BARS_ORNATE.getName(), IRON_BARS_VERTICAL.getName(), IRON_BARS_SPIKES.getName());
		addVariantNames(ChiselBlocks.jungle, JUNGLE_PLANKS_SMOOTH.getName(), JUNGLE_PLANKS_SHORT.getName(), JUNGLE_PLANKS_FANCY.getName(), JUNGLE_PLANKS_PANEL.getName(), JUNGLE_PLANKS_DOUBLE_SLAB.getName(), JUNGLE_PLANKS_CRATE.getName(), JUNGLE_PLANKS_CRATE_FANCY.getName(), JUNGLE_PLANKS_LONG.getName(), JUNGLE_PLANKS_VERTICAL.getName(), JUNGLE_PLANKS_VERTICAL_UNEVEN.getName(), JUNGLE_PLANKS_PARQUET.getName(), JUNGLE_PLANKS_BLINDS.getName(), JUNGLE_PLANKS_SCAFFOLD.getName(), JUNGLE_PLANKS_DISARRAY.getName(), JUNGLE_PLANKS_DISARRAY_VERTICAL.getName());
		addVariantNames(ChiselBlocks.laboratory, LABORATORY_PANEL_WALL.getName(), LABORATORY_PANEL_DOTTED.getName(), LABORATORY_WALL.getName(), LABORATORY_WALL_ROUNDED.getName(), LABORATORY_WALL_VENT.getName(), LABORATORY_TILES_ENAMELLED_LARGE.getName(), LABORATORY_TILES_ENAMELLED_SMALL.getName(), LABORATORY_FLOOR.getName(), LABORATORY_CHECKERBOARD.getName(), LABORATORY_PANEL_CLEAR.getName(), LABORATORY_PANEL_FUZZY.getName(), LABORATORY_TILES_STEEL_LARGE.getName(), LABORATORY_TILES_STEEL_SMALL.getName(), LABORATORY_CONSOLE_RIGHT.getName(), LABORATORY_CONSOLE_LEFT.getName(), LABORATORY_CONSOLE_INFORMATION.getName());
		addVariantNames(ChiselBlocks.lapis, LAPIS_CHUNKY.getName(), LAPIS_DARK.getName(), LAPIS_ZELDA.getName(), LAPIS_ORNATE.getName(), LAPIS_TILE.getName(), LAPIS_PANEL.getName(), LAPIS_SMOOTH.getName(), LAPIS_ORNATE_LAYER.getName());
		addVariantNames(ChiselBlocks.large_hex_plating, LARGE_HEX_PLATING_0.getName(), LARGE_HEX_PLATING_1.getName(), LARGE_HEX_PLATING_2.getName(), LARGE_HEX_PLATING_3.getName(), LARGE_HEX_PLATING_4.getName(), LARGE_HEX_PLATING_5.getName(), LARGE_HEX_PLATING_6.getName(), LARGE_HEX_PLATING_7.getName(), LARGE_HEX_PLATING_8.getName(), LARGE_HEX_PLATING_9.getName(), LARGE_HEX_PLATING_10.getName(), LARGE_HEX_PLATING_11.getName(), LARGE_HEX_PLATING_12.getName(), LARGE_HEX_PLATING_13.getName(), LARGE_HEX_PLATING_14.getName(), LARGE_HEX_PLATING_15.getName());
		addVariantNames(ChiselBlocks.lavastone, LAVASTONE_RAW.getName(), LAVASTONE_BLACK.getName(), LAVASTONE_TILES.getName(), LAVASTONE_BRICKS.getName(), LAVASTONE_TILES_CREEPER.getName(), LAVASTONE_PANEL.getName(), LAVASTONE_PANEL_ORNATE.getName(), LAVASTONE_DARK.getName());
		addVariantNames(ChiselBlocks.lead, LEAD_CAUTION.getName(), LEAD_SHIPPING.getName(), LEAD_THERMAL.getName(), LEAD_125.getName(), LEAD_BORDERED.getName(), LEAD_BOLTED.getName());
		addVariantNames(ChiselBlocks.leaf, LEAVES_DEAD.getName(), LEAVES_FANCY.getName(), LEAVES_PINK.getName(), LEAVES_RED.getName(), LEAVES_WHITE.getName(), LEAVES_CHRISTMAS_BALLS.getName(), LEAVES_CHRISTMAS_LIGHTS.getName());
		addVariantNames(ChiselBlocks.limestone, LIMESTONE_RAW.getName(), LIMESTONE_TILES.getName(), LIMESTONE_TILES_FRENCH.getName(), LIMESTONE_TILES_FRENCH_LIGHT.getName(), LIMESTONE_TILES_CREEPER.getName(), LIMESTONE_TILES_LARGE.getName(), LIMESTONE_BRICKS.getName(), LIMESTONE_SMOOTH.getName(), LIMESTONE_PANEL_ORNATE.getName(), LIMESTONE_PANEL_ENGRAVED.getName(), LIMESTONE_PANEL_CREEPER.getName(), LIMESTONE_PANEL_LIGHT.getName(), LIMESTONE_PANEL_DARK.getName(), LIMESTONE_PANEL.getName(), LIMESTONE_DENT.getName());
		addVariantNames(ChiselBlocks.litpumpkin, LITPUMPKIN_0.getName(), LITPUMPKIN_1.getName(), LITPUMPKIN_2.getName(), LITPUMPKIN_3.getName(), LITPUMPKIN_4.getName(), LITPUMPKIN_5.getName(), LITPUMPKIN_6.getName(), LITPUMPKIN_7.getName(), LITPUMPKIN_8.getName(), LITPUMPKIN_9.getName(), LITPUMPKIN_10.getName(), LITPUMPKIN_11.getName(), LITPUMPKIN_12.getName(), LITPUMPKIN_13.getName(), LITPUMPKIN_14.getName(), LITPUMPKIN_15.getName(), LITPUMPKIN_16.getName());
		addVariantNames(ChiselBlocks.marble, MARBLE_RAW.getName(), MARBLE_BRICK.getName(), MARBLE_PANEL_CLASSIC.getName(), MARBLE_PANEL_ORNATE.getName(), MARBLE_PANEL.getName(), MARBLE_BLOCK.getName(), MARBLE_CREEPER_DARK.getName(), MARBLE_CREEPER_LIGHT.getName(), MARBLE_CARVED.getName(), MARBLE_CARVED_RADIAL.getName(), MARBLE_DENT.getName(), MARBLE_DENT_LARGE.getName(), MARBLE_TILES.getName(), MARBLE_TILES_ARRANGED.getName(), MARBLE_TILES_FANCY.getName(), MARBLE_BLOCKS.getName());
		addVariantNames(ChiselBlocks.mossy_cobblestone, MOSSY_COBBLESTONE_BRICKS_ALIGNED.getName(), MOSSY_COBBLESTONE_BRICKS_DETAILED.getName(), MOSSY_COBBLESTONE_BRICKS_SMALL.getName(), MOSSY_COBBLESTONE_TILES_LARGE.getName(), MOSSY_COBBLESTONE_TILES_SMALL.getName(), MOSSY_COBBLESTONE_TILES_FRENCH.getName(), MOSSY_COBBLESTONE_TILES_FRENCH_LIGHT.getName(), MOSSY_COBBLESTONE_TILES_CREEPER.getName(), MOSSY_COBBLESTONE_TILES_DAMAGED.getName(), MOSSY_COBBLESTONE_TILES_DAMAGED.getName(), MOSSY_COBBLESTONE_TILES_HUGE.getName(), MOSSY_COBBLESTONE_PANEL_CREEPER.getName(), MOSSY_COBBLESTONE_DENT.getName(), MOSSY_COBBLESTONE_PANEL.getName(), MOSSY_COBBLESTONE_PANEL_LIGHT.getName(), MOSSY_COBBLESTONE_PANEL_DARK.getName());
		addVariantNames(ChiselBlocks.mossy_temple, MOSSY_TEMPLE_COBBLE.getName(), MOSSY_TEMPLE_ORNATE.getName(), MOSSY_TEMPLE_PLATE.getName(), MOSSY_TEMPLE_PLATE_CRACKED.getName(), MOSSY_TEMPLE_BRICKS.getName(), MOSSY_TEMPLE_BRICKS_LARGE.getName(), MOSSY_TEMPLE_BRICKS_WORN.getName(), MOSSY_TEMPLE_BRICKS_DISARRAY.getName(), MOSSY_TEMPLE_COLUMN.getName(), MOSSY_TEMPLE_STAND.getName(), MOSSY_TEMPLE_STAND_MOSAIC.getName(), MOSSY_TEMPLE_STAND_CREEPER.getName(), MOSSY_TEMPLE_TILES.getName(), MOSSY_TEMPLE_TILES_SMALL.getName(), MOSSY_TEMPLE_TILES_LIGHT.getName(), MOSSY_TEMPLE_TILES_SMALL_LIGHT.getName());
		addVariantNames(ChiselBlocks.netherbrick, NETHER_BRICK_BLUE.getName(), NETHER_BRICK_SPATTERED.getName(), NETHER_BRICK_GUTS.getName(), NETHER_BRICK_GUTS_DARK.getName(), NETHER_BRICK_GUTS_SMALL.getName(), NETHER_BRICK_BLUE_LAVA.getName(), NETHER_BRICK_BROWN.getName(), NETHER_BRICK_OBSIDIAN.getName(), NETHER_BRICK_STONE.getName(), NETHER_BRICK_MEAT.getName(), NETHER_BRICK_MEAT_RED.getName(), NETHER_BRICK_MEAT_SMALL.getName(), NETHER_BRICK_MEAT_SMALL_RED.getName(), NETHER_BRICK_RED.getName(), NETHER_BRICK_RED_SMALL.getName());
		addVariantNames(ChiselBlocks.netherrack, NETHERRACK_BLOOD_GRAVEL.getName(), NETHERRACK_BLOOD.getName(), NETHERRACK_BLOOD_DARK.getName(), NETHERRACK_BLUE.getName(), NETHERRACK_BLUE_SHALE.getName(), NETHERRACK_CLASSIC.getName(), NETHERRACK_SPATTERED.getName(), NETHERRACK_GUTS.getName(), NETHERRACK_GUTS_DARK.getName(), NETHERRACK_MEAT.getName(), NETHERRACK_MEAT_RED.getName(), NETHERRACK_MEAT_SMALL.getName(), NETHERRACK_RED.getName(), NETHERRACK_LAVA.getName());
		addVariantNames(ChiselBlocks.oak, OAK_PLANKS_SMOOTH.getName(), OAK_PLANKS_SHORT.getName(), OAK_PLANKS_FANCY.getName(), OAK_PLANKS_PANEL.getName(), OAK_PLANKS_DOUBLE_SLAB.getName(), OAK_PLANKS_CRATE.getName(), OAK_PLANKS_CRATE_FANCY.getName(), OAK_PLANKS_LONG.getName(), OAK_PLANKS_VERTICAL.getName(), OAK_PLANKS_VERTICAL_UNEVEN.getName(), OAK_PLANKS_PARQUET.getName(), OAK_PLANKS_BLINDS.getName(), OAK_PLANKS_SCAFFOLD.getName(), OAK_PLANKS_DISARRAY.getName(), OAK_PLANKS_DISARRAY_VERTICAL.getName());
		addVariantNames(ChiselBlocks.obsidian, OBSIDIAN_PILLAR_LARGE.getName(), OBSIDIAN_PILLAR.getName(), OBSIDIAN_CHISELED.getName(), OBSIDIAN_PANEL_SHINY.getName(), OBSIDIAN_PANEL.getName(), OBSIDIAN_ORGANIC_CHUNKS.getName(), OBSIDIAN_ORGANIC_GROWTH.getName(), OBSIDIAN_CRYSTAL.getName(), OBSIDIAN_CRYSTAL.getName(), OBSIDIAN_PANEL_MAP.getName(), OBSIDIAN_PANEL_REGION.getName(), OBSIDIAN_PANEL_BRIGHT.getName(), OBSIDIAN_BLOCKS.getName(), OBSIDIAN_TILES.getName(), OBSIDIAN_GREEK.getName(), OBSIDIAN_CRATE.getName());
		addVariantNames(ChiselBlocks.packed_ice, PACKED_ICE_ROUGH.getName(), PACKED_ICE_COBBLE.getName(), PACKED_ICE_ROUGH_LARGE.getName(), PACKED_ICE_BRICKS_LARGE.getName(), PACKED_ICE_BRICKS_SMALL.getName(), PACKED_ICE_GLASS_WALL.getName(), PACKED_ICE_TILES_LARGE.getName(), PACKED_ICE_TILES_FANCY.getName(), PACKED_ICE_TILES_SUNKEN.getName(), PACKED_ICE_TILES_DISORDERED.getName(), PACKED_ICE_PANEL.getName(), PACKED_ICE_DOUBLE_SLAB.getName(), PACKED_ICE_ZELDA.getName(), PACKED_ICE_BISMUTH.getName(), PACKED_ICE_POISON.getName());
		addVariantNames(ChiselBlocks.packed_ice_pillar, PACKED_ICE_PILLAR_PLAIN_PLAIN.getName(), PACKED_ICE_PILLAR_PLAIN_GREEK.getName(), PACKED_ICE_PILLAR_GREEK_PLAIN.getName(), PACKED_ICE_PILLAR_GREEK_GREEK.getName(), PACKED_ICE_PILLAR_CARVED.getName(), PACKED_ICE_PILLAR_ORNAMENTAL.getName(), PACKED_ICE_PILLAR_INSCRIBED.getName());
		addVariantNames(ChiselBlocks.paperwall, PAPERWALL_BOXED.getName(), PAPERWALL_STRIKE_MIDDLE.getName(), PAPERWALL_CROSSED.getName(), PAPERWALL_SIX.getName(), PAPERWALL_STRIKE_VERTICAL.getName(), PAPERWALL_STRIKE_HORIZONTAL.getName(), PAPERWALL_FLORAL.getName(), PAPERWALL_PLAIN.getName(), PAPERWALL_DOOR.getName());
		addVariantNames(ChiselBlocks.paperwall_block, PAPERWALL_BLOCK_BOXED.getName(), PAPERWALL_BLOCK_STRIKE_MIDDLE.getName(), PAPERWALL_BLOCK_CROSSED.getName(), PAPERWALL_BLOCK_SIX.getName(), PAPERWALL_BLOCK_STRIKE_VERTICAL.getName(), PAPERWALL_BLOCK_STRIKE_HORIZONTAL.getName(), PAPERWALL_BLOCK_FLORAL.getName(), PAPERWALL_BLOCK_PLAIN.getName(), PAPERWALL_BLOCK_DOOR.getName());
		addVariantNames(ChiselBlocks.pumpkin, PUMPKIN_0.getName(), PUMPKIN_1.getName(), PUMPKIN_2.getName(), PUMPKIN_3.getName(), PUMPKIN_4.getName(), PUMPKIN_5.getName(), PUMPKIN_6.getName(), PUMPKIN_7.getName(), PUMPKIN_8.getName(), PUMPKIN_9.getName(), PUMPKIN_10.getName(), PUMPKIN_11.getName(), PUMPKIN_12.getName(), PUMPKIN_13.getName(), PUMPKIN_14.getName(), PUMPKIN_15.getName(), PUMPKIN_16.getName());
		addVariantNames(ChiselBlocks.purple_fantasy, PURPLED_FANTASY_BRICK.getName(), PURPLED_FANTASY_BRICK_FADED.getName(), PURPLED_FANTASY_BRICK_WORN.getName(), PURPLED_FANTASY_BRICK_DAMAGED.getName(), PURPLED_FANTASY_DECORATION.getName(), PURPLED_FANTASY_DECORATION_BLOCK.getName(), PURPLED_FANTASY_DECORATION_PILLAR.getName(), PURPLED_FANTASY_PILLAR.getName(), PURPLED_FANTASY_DECORATION_SNAKE.getName(), PURPLED_FANTASY_DECORATION_NOISE.getName(), PURPLED_FANTASY_DECORATION_ENGRAVING.getName(), PURPLED_FANTASY_DECORATION_CHAINS.getName(), PURPLED_FANTASY_DECORATION_PLATE.getName(), PURPLED_FANTASY_BLOCK.getName(), PURPLED_FANTASY_BRICKS_DISARRAY.getName(), PURPLED_FANTASY_BRICKS_DISARRAY_WORN.getName());
		addVariantNames(ChiselBlocks.rebel, REBEL_CAMO.getName(), REBEL_CAMO_SECLUDED.getName(), REBEL_BOLT.getName(), REBEL_CAUTION_WHITE.getName(), REBEL_CAUTION_TEAM.getName());
		addVariantNames(ChiselBlocks.redstone, REDSTONE_SMOOTH.getName(), REDSTONE_LARGE.getName(), REDSTONE_SMALL.getName(), REDSTONE_BRICKS.getName(), REDSTONE_BRICKS_SMALL.getName(), REDSTONE_BRICKS_CHAOTIC.getName(), REDSTONE_CHISELED.getName(), REDSTONE_GREEK.getName(), REDSTONE_TILES_ORNATE.getName(), REDSTONE_PILLAR.getName(), REDSTONE_TILES.getName(), REDSTONE_CIRCUIT.getName(), REDSTONE_CIRCUIT_SUPAPLEX.getName(), REDSTONE_SKULLS.getName(), REDSTONE_ZELDA.getName());
		addVariantNames(ChiselBlocks.road_line, ROAD_LINES_WHITE.getName(), ROAD_LINES_YELLOW.getName(), ROAD_LINES_WHITE_DOUBLE.getName(), ROAD_LINES_YELLOW_DOUBLE.getName());
		addVariantNames(ChiselBlocks.runic_voidstone, RUNIC_VOIDSTONE_0.getName(), RUNIC_VOIDSTONE_1.getName(), RUNIC_VOIDSTONE_2.getName(), RUNIC_VOIDSTONE_3.getName(), RUNIC_VOIDSTONE_4.getName(), RUNIC_VOIDSTONE_5.getName(), RUNIC_VOIDSTONE_6.getName(), RUNIC_VOIDSTONE_7.getName(), RUNIC_VOIDSTONE_8.getName(), RUNIC_VOIDSTONE_9.getName(), RUNIC_VOIDSTONE_10.getName(), RUNIC_VOIDSTONE_11.getName(), RUNIC_VOIDSTONE_12.getName(), RUNIC_VOIDSTONE_13.getName(), RUNIC_VOIDSTONE_14.getName(), RUNIC_VOIDSTONE_15.getName());
		addVariantNames(ChiselBlocks.sandstone, SANDSTONE_FADED.getName(), SANDSTONE_PILLAR.getName(), SANDSTONE_PILLAR_CAPSTONE.getName(), SANDSTONE_PILLAR_SMALL.getName(), SANDSTONE_PILLAR_BASE.getName(), SANDSTONE_SMOOTH_FLAT.getName(), SANDSTONE_PILLAR_CAPSTONE_SMOOTH.getName(),SANDSTONE_PILLAR_SMALL_SMOOTH.getName(), SANDSTONE_PILLAR_SMOOTH.getName(), SANDSTONE_BLOCK.getName(), SANDSTONE_BLOCKS_SMALL.getName(), SANDSTONE_BLOCKS.getName(), SANDSTONE_MOSAIC.getName(), SANDSTONE_STACKED.getName());
		addVariantNames(ChiselBlocks.sandstone_scribbles, SANDSTONE_SCRIBBLES_0.getName(), SANDSTONE_SCRIBBLES_1.getName(), SANDSTONE_SCRIBBLES_2.getName(), SANDSTONE_SCRIBBLES_3.getName(), SANDSTONE_SCRIBBLES_4.getName(), SANDSTONE_SCRIBBLES_5.getName(), SANDSTONE_SCRIBBLES_6.getName(), SANDSTONE_SCRIBBLES_7.getName(), SANDSTONE_SCRIBBLES_8.getName(), SANDSTONE_SCRIBBLES_9.getName(), SANDSTONE_SCRIBBLES_10.getName(), SANDSTONE_SCRIBBLES_11.getName(), SANDSTONE_SCRIBBLES_12.getName(), SANDSTONE_SCRIBBLES_13.getName(), SANDSTONE_SCRIBBLES_14.getName());
		addVariantNames(ChiselBlocks.silver, SILVER_CAUTION.getName(), SILVER_SHIPPING.getName(), SILVER_THERMAL.getName(), SILVER_125.getName(), SILVER_BORDERED.getName(), SILVER_BOLTED.getName());
		addVariantNames(ChiselBlocks.snakestone_sand, SNAKESTONE_SAND_0.getName(), SNAKESTONE_SAND_1.getName());
		addVariantNames(ChiselBlocks.snakestone_stone, SNAKESTONE_STONE_0.getName(), SNAKESTONE_STONE_1.getName());
		addVariantNames(ChiselBlocks.spruce, SPRUCE_PLANKS_SMOOTH.getName(), SPRUCE_PLANKS_SHORT.getName(), SPRUCE_PLANKS_FANCY.getName(), SPRUCE_PLANKS_PANEL.getName(), SPRUCE_PLANKS_DOUBLE_SLAB.getName(), SPRUCE_PLANKS_CRATE.getName(), SPRUCE_PLANKS_CRATE_FANCY.getName(), SPRUCE_PLANKS_LONG.getName(), SPRUCE_PLANKS_VERTICAL.getName(), SPRUCE_PLANKS_VERTICAL_UNEVEN.getName(), SPRUCE_PLANKS_PARQUET.getName(), SPRUCE_PLANKS_BLINDS.getName(), SPRUCE_PLANKS_SCAFFOLD.getName(), SPRUCE_PLANKS_DISARRAY.getName(), SPRUCE_PLANKS_DISARRAY_VERTICAL.getName());
		addVariantNames(ChiselBlocks.stained_glass_black, STAINED_GLASS_BLACK_BUBBLE.getName(), STAINED_GLASS_BLACK_PANEL.getName(), STAINED_GLASS_BLACK_PANEL_FANCY.getName(), STAINED_GLASS_BLACK_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_red, STAINED_GLASS_RED_BUBBLE.getName(), STAINED_GLASS_RED_PANEL.getName(), STAINED_GLASS_RED_PANEL_FANCY.getName(), STAINED_GLASS_RED_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_green, STAINED_GLASS_GREEN_BUBBLE.getName(), STAINED_GLASS_GREEN_PANEL.getName(), STAINED_GLASS_GREEN_PANEL_FANCY.getName(), STAINED_GLASS_GREEN_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_brown, STAINED_GLASS_BROWN_BUBBLE.getName(), STAINED_GLASS_BROWN_PANEL.getName(), STAINED_GLASS_BROWN_PANEL_FANCY.getName(), STAINED_GLASS_BROWN_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_blue, STAINED_GLASS_BLUE_BUBBLE.getName(), STAINED_GLASS_BLUE_PANEL.getName(), STAINED_GLASS_BLUE_PANEL_FANCY.getName(), STAINED_GLASS_BLUE_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_purple, STAINED_GLASS_PURPLE_BUBBLE.getName(), STAINED_GLASS_PURPLE_PANEL.getName(), STAINED_GLASS_PURPLE_PANEL_FANCY.getName(), STAINED_GLASS_PURPLE_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_cyan, STAINED_GLASS_CYAN_BUBBLE.getName(), STAINED_GLASS_CYAN_PANEL.getName(), STAINED_GLASS_CYAN_PANEL_FANCY.getName(), STAINED_GLASS_CYAN_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_light_gray, STAINED_GLASS_LIGHT_GRAY_BUBBLE.getName(), STAINED_GLASS_LIGHT_GRAY_PANEL.getName(), STAINED_GLASS_LIGHT_GRAY_PANEL_FANCY.getName(), STAINED_GLASS_LIGHT_GRAY_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_gray, STAINED_GLASS_GRAY_BUBBLE.getName(), STAINED_GLASS_GRAY_PANEL.getName(), STAINED_GLASS_GRAY_PANEL_FANCY.getName(), STAINED_GLASS_GRAY_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pink, STAINED_GLASS_PINK_BUBBLE.getName(), STAINED_GLASS_PINK_PANEL.getName(), STAINED_GLASS_PINK_PANEL_FANCY.getName(), STAINED_GLASS_PINK_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_lime, STAINED_GLASS_LIME_BUBBLE.getName(), STAINED_GLASS_LIME_PANEL.getName(), STAINED_GLASS_LIME_PANEL_FANCY.getName(), STAINED_GLASS_LIME_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_yellow, STAINED_GLASS_YELLOW_BUBBLE.getName(), STAINED_GLASS_YELLOW_PANEL.getName(), STAINED_GLASS_YELLOW_PANEL_FANCY.getName(), STAINED_GLASS_YELLOW_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_light_blue, STAINED_GLASS_LIGHT_BLUE_BUBBLE.getName(), STAINED_GLASS_LIGHT_BLUE_PANEL.getName(), STAINED_GLASS_LIGHT_BLUE_PANEL_FANCY.getName(), STAINED_GLASS_LIGHT_BLUE_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_magenta, STAINED_GLASS_MAGENTA_BUBBLE.getName(), STAINED_GLASS_MAGENTA_PANEL.getName(), STAINED_GLASS_MAGENTA_PANEL_FANCY.getName(), STAINED_GLASS_MAGENTA_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_orange, STAINED_GLASS_ORANGE_BUBBLE.getName(), STAINED_GLASS_ORANGE_PANEL.getName(), STAINED_GLASS_ORANGE_PANEL_FANCY.getName(), STAINED_GLASS_ORANGE_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_white, STAINED_GLASS_WHITE_BUBBLE.getName(), STAINED_GLASS_WHITE_PANEL.getName(), STAINED_GLASS_WHITE_PANEL_FANCY.getName(), STAINED_GLASS_WHITE_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_black, STAINED_GLASS_PANE_BLACK_BUBBLE.getName(), STAINED_GLASS_PANE_BLACK_PANEL.getName(), STAINED_GLASS_PANE_BLACK_PANEL_FANCY.getName(), STAINED_GLASS_PANE_BLACK_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_red, STAINED_GLASS_PANE_RED_BUBBLE.getName(), STAINED_GLASS_PANE_RED_PANEL.getName(), STAINED_GLASS_PANE_RED_PANEL_FANCY.getName(), STAINED_GLASS_PANE_RED_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_green, STAINED_GLASS_PANE_GREEN_BUBBLE.getName(), STAINED_GLASS_PANE_GREEN_PANEL.getName(), STAINED_GLASS_PANE_GREEN_PANEL_FANCY.getName(), STAINED_GLASS_PANE_GREEN_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_brown, STAINED_GLASS_PANE_BROWN_BUBBLE.getName(), STAINED_GLASS_PANE_BROWN_PANEL.getName(), STAINED_GLASS_PANE_BROWN_PANEL_FANCY.getName(), STAINED_GLASS_PANE_BROWN_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_blue, STAINED_GLASS_PANE_BLUE_BUBBLE.getName(), STAINED_GLASS_PANE_BLUE_PANEL.getName(), STAINED_GLASS_PANE_BLUE_PANEL_FANCY.getName(), STAINED_GLASS_PANE_BLUE_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_purple, STAINED_GLASS_PANE_PURPLE_BUBBLE.getName(), STAINED_GLASS_PANE_PURPLE_PANEL.getName(), STAINED_GLASS_PANE_PURPLE_PANEL_FANCY.getName(), STAINED_GLASS_PANE_PURPLE_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_cyan, STAINED_GLASS_PANE_CYAN_BUBBLE.getName(), STAINED_GLASS_PANE_CYAN_PANEL.getName(), STAINED_GLASS_PANE_CYAN_PANEL_FANCY.getName(), STAINED_GLASS_PANE_CYAN_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_light_gray, STAINED_GLASS_PANE_LIGHT_GRAY_BUBBLE.getName(), STAINED_GLASS_PANE_LIGHT_GRAY_PANEL.getName(), STAINED_GLASS_PANE_LIGHT_GRAY_PANEL_FANCY.getName(), STAINED_GLASS_PANE_LIGHT_GRAY_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_gray, STAINED_GLASS_PANE_GRAY_BUBBLE.getName(), STAINED_GLASS_PANE_GRAY_PANEL.getName(), STAINED_GLASS_PANE_GRAY_PANEL_FANCY.getName(), STAINED_GLASS_PANE_GRAY_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_pink, STAINED_GLASS_PANE_PINK_BUBBLE.getName(), STAINED_GLASS_PANE_PINK_PANEL.getName(), STAINED_GLASS_PANE_PINK_PANEL_FANCY.getName(), STAINED_GLASS_PANE_PINK_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_lime, STAINED_GLASS_PANE_LIME_BUBBLE.getName(), STAINED_GLASS_PANE_LIME_PANEL.getName(), STAINED_GLASS_PANE_LIME_PANEL_FANCY.getName(), STAINED_GLASS_PANE_LIME_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_yellow, STAINED_GLASS_PANE_YELLOW_BUBBLE.getName(), STAINED_GLASS_PANE_YELLOW_PANEL.getName(), STAINED_GLASS_PANE_YELLOW_PANEL_FANCY.getName(), STAINED_GLASS_PANE_YELLOW_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_light_blue, STAINED_GLASS_PANE_LIGHT_BLUE_BUBBLE.getName(), STAINED_GLASS_PANE_LIGHT_BLUE_PANEL.getName(), STAINED_GLASS_PANE_LIGHT_BLUE_PANEL_FANCY.getName(), STAINED_GLASS_PANE_LIGHT_BLUE_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_magenta, STAINED_GLASS_PANE_MAGENTA_BUBBLE.getName(), STAINED_GLASS_PANE_MAGENTA_PANEL.getName(), STAINED_GLASS_PANE_MAGENTA_PANEL_FANCY.getName(), STAINED_GLASS_PANE_MAGENTA_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_orange, STAINED_GLASS_PANE_ORANGE_BUBBLE.getName(), STAINED_GLASS_PANE_ORANGE_PANEL.getName(), STAINED_GLASS_PANE_ORANGE_PANEL_FANCY.getName(), STAINED_GLASS_PANE_ORANGE_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.stained_glass_pane_white, STAINED_GLASS_PANE_WHITE_BUBBLE.getName(), STAINED_GLASS_PANE_WHITE_PANEL.getName(), STAINED_GLASS_PANE_WHITE_PANEL_FANCY.getName(), STAINED_GLASS_PANE_WHITE_BORDERLESS.getName());
		addVariantNames(ChiselBlocks.steel, STEEL_CAUTION.getName(), STEEL_SHIPPING.getName(), STEEL_THERMAL.getName(), STEEL_125.getName(), STEEL_BORDERED.getName(), STEEL_BOLTED.getName());
		addVariantNames(ChiselBlocks.stone_bricks, STONE_BRICKS_NEUTRAL.getName(), STONE_BRICKS_FELSIC.getName(), STONE_BRICKS_MAFIC.getName(), STONE_BRICKS_SMALL.getName(), STONE_BRICKS_WIDE.getName(), STONE_BRICKS_DISORDERED_SMALL.getName(), STONE_BRICKS_DISORDERED.getName(), STONE_BRICKS_DISORDERED_PANEL.getName(), STONE_BRICKS_FANCY.getName(), STONE_BRICKS_ORNATE.getName(), STONE_BRICKS_ORNATE_LARGE.getName(), STONE_BRICKS_PANEL.getName(), STONE_BRICKS_PANEL_SUNKEN.getName(), STONE_BRICKS_PANEL_ORNATE.getName(), STONE_BRICKS_POISON.getName());
		addVariantNames(ChiselBlocks.technical, TECHNICAL_SCAFFOLD.getName(), TECHNICAL_PANEL_CAUTION.getName(), TECHNICAL_125.getName(), TECHNICAL_UNDER_LARGE.getName(), TECHNICAL_FAN_FAST.getName(), TECHNICAL_UNDER_SMALL.getName(), TECHNICAL_FAN_OFF.getName(), TECHNICAL_VENTS.getName(), TECHNICAL_VENTS_GLOWING.getName(), TECHNICAL_INSULATION.getName(), TECHNICAL_GEARS.getName(), TECHNICAL_CABLES.getName(), TECHNICAL_PANEL_RUSTY.getName(), TECHNICAL_GRATE.getName(), TECHNICAL_FAN_MALFUNCTIONING.getName(), TECHNICAL_GRATE_RUSTY.getName());
		addVariantNames(ChiselBlocks.temple, TEMPLE_COBBLE.getName(), TEMPLE_ORNATE.getName(), TEMPLE_PLATE.getName(), TEMPLE_PLATE_CRACKED.getName(), TEMPLE_BRICKS.getName(), TEMPLE_BRICKS_LARGE.getName(), TEMPLE_BRICKS_WORN.getName(), TEMPLE_BRICKS_DISARRAY.getName(), TEMPLE_COLUMN.getName(), TEMPLE_STAND.getName(), TEMPLE_STAND_MOSAIC.getName(), TEMPLE_STAND_CREEPER.getName(), TEMPLE_TILES.getName(), TEMPLE_TILES_SMALL.getName(), TEMPLE_TILES_LIGHT.getName(), TEMPLE_TILES_SMALL_LIGHT.getName());
		addVariantNames(ChiselBlocks.tin, TIN_CAUTION.getName(), TIN_SHIPPING.getName(), TIN_THERMAL.getName(), TIN_125.getName(), TIN_BORDERED.getName(), TIN_BOLTED.getName());
		addVariantNames(ChiselBlocks.torch, TORCH_0.getName(), TORCH_1.getName(), TORCH_2.getName(), TORCH_3.getName(), TORCH_4.getName(), TORCH_5.getName(), TORCH_6.getName(), TORCH_7.getName(), TORCH_8.getName(), TORCH_9.getName());
		addVariantNames(ChiselBlocks.transparent_technical, TRANSPARENT_TECHNICAL_SCAFFOLD.getName(), TRANSPARENT_TECHNICAL_FAN_FAST.getName(), TRANSPARENT_TECHNICAL_FAN_OFF.getName(), TRANSPARENT_TECHNICAL_FAN_MALFUNCTIONING.getName());
		addVariantNames(ChiselBlocks.tyrian, TYRIAN_NORMAL.getName(), TYRIAN_BLEAK.getName(), TYRIAN_PURPLE.getName(), TYRIAN_PURPLE_FADED.getName(), TYRIAN_RUSTED.getName(), TYRIAN_ELABORATE.getName(), TYRIAN_SEAMS.getName(), TYRIAN_PLATFORM.getName(), TYRIAN_TILES.getName(), TYRIAN_DIAGONAL.getName(), TYRIAN_DENT.getName(), TYRIAN_BLUE.getName(), TYRIAN_BLACK.getName(), TYRIAN_BLACK_TILES.getName(), TYRIAN_OPENING.getName(), TYRIAN_SHINY.getName());
		addVariantNames(ChiselBlocks.uranium, URANIUM_CAUTION.getName(), URANIUM_SHIPPING.getName(), URANIUM_THERMAL.getName(), URANIUM_125.getName(), URANIUM_BORDERED.getName(), URANIUM_BOLTED.getName());
		addVariantNames(ChiselBlocks.valentines, VALENTINES_BRICKS.getName(), VALENTINES_COMPANION.getName(), VALENTINES_EMPTY.getName(), VALENTINES_HEART.getName(), VALENTINES_HEART_GRAY.getName(), VALENTINES_BLOCK.getName(), VALENTINES_COBBLE.getName(), VALENTINES_BUMPY.getName(), VALENTINES_FIRE.getName(), VALENTINES_TILE.getName());
		addVariantNames(ChiselBlocks.voidstone, VOIDSTONE_RAW.getName(), VOIDSTONE_TILES.getName(), VOIDSTONE_SMOOTH.getName(), VOIDSTONE_SKULL.getName(), VOIDSTONE_RUNIC.getName(), VOIDSTONE_METAL.getName(), VOIDSTONE_EYE.getName(), VOIDSTONE_BEVEL.getName());
		addVariantNames(ChiselBlocks.warning, WARNING_RADIATION.getName(), WARNING_BIOHAZARD.getName(), WARNING_FIRE.getName(), WARNING_EXPLOSION.getName(), WARNING_DEATH.getName(), WARNING_FALLING_OBJECTS.getName(), WARNING_FALLING.getName(), WARNING_VOLTAGE.getName(), WARNING_GENERIC.getName(), WARNING_CHEM.getName(), WARNING_CONSTRUCTION.getName(), WARNING_LOUD.getName(), WARNING_NO_ENTRY.getName(), WARNING_CRYOGENIC.getName(), WARNING_OXYGEN.getName());
		addVariantNames(ChiselBlocks.waterstone, WATERSTONE_BRICKS.getName(), WATERSTONE_BLACK.getName(), WATERSTONE_TILES.getName(), WATERSTONE_CHAOTIC.getName(), WATERSTONE_CREEPER.getName(), WATERSTONE_PANEL.getName(), WATERSTONE_ORNATE.getName());
		addVariantNames(ChiselBlocks.woolen_clay, WOOLEN_CLAY_0.getName(), WOOLEN_CLAY_1.getName(), WOOLEN_CLAY_2.getName(), WOOLEN_CLAY_3.getName(), WOOLEN_CLAY_4.getName(), WOOLEN_CLAY_5.getName(), WOOLEN_CLAY_6.getName(), WOOLEN_CLAY_7.getName(), WOOLEN_CLAY_8.getName(), WOOLEN_CLAY_9.getName(), WOOLEN_CLAY_10.getName(), WOOLEN_CLAY_11.getName(), WOOLEN_CLAY_12.getName(), WOOLEN_CLAY_13.getName(), WOOLEN_CLAY_14.getName(), WOOLEN_CLAY_15.getName());

		addVariantNames(ChiselItems.upgrade, "upgrade_speed", "upgrade_automation", "upgrade_stack", "upgrade_reversion");
	}

	public static void registerModels() {
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_SMOOTH.getMeta(), getResource(ACACIA_PLANKS_SMOOTH.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_SHORT.getMeta(), getResource(ACACIA_PLANKS_SHORT.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_FANCY.getMeta(), getResource(ACACIA_PLANKS_FANCY.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_PANEL.getMeta(), getResource(ACACIA_PLANKS_PANEL.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_DOUBLE_SLAB.getMeta(), getResource(ACACIA_PLANKS_DOUBLE_SLAB.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_CRATE.getMeta(), getResource(ACACIA_PLANKS_CRATE.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_CRATE_FANCY.getMeta(), getResource(ACACIA_PLANKS_CRATE_FANCY.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_LONG.getMeta(), getResource(ACACIA_PLANKS_LONG.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_VERTICAL.getMeta(), getResource(ACACIA_PLANKS_VERTICAL.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_VERTICAL_UNEVEN.getMeta(), getResource(ACACIA_PLANKS_VERTICAL_UNEVEN.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_PARQUET.getMeta(), getResource(ACACIA_PLANKS_PARQUET.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_BLINDS.getMeta(), getResource(ACACIA_PLANKS_BLINDS.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_SCAFFOLD.getMeta(), getResource(ACACIA_PLANKS_SCAFFOLD.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_DISARRAY.getMeta(), getResource(ACACIA_PLANKS_DISARRAY.getName()));
		registerBlockModel(ChiselBlocks.acacia, ACACIA_PLANKS_DISARRAY_VERTICAL.getMeta(), getResource(ACACIA_PLANKS_DISARRAY_VERTICAL.getName()));

		registerBlockModel(ChiselBlocks.aluminum, ALUMINUM_CAUTION.getMeta(), getResource(ALUMINUM_CAUTION.getName()));
		registerBlockModel(ChiselBlocks.aluminum, ALUMINUM_SHIPPING.getMeta(), getResource(ALUMINUM_SHIPPING.getName()));
		registerBlockModel(ChiselBlocks.aluminum, ALUMINUM_THERMAL.getMeta(), getResource(ALUMINUM_THERMAL.getName()));
		registerBlockModel(ChiselBlocks.aluminum, ALUMINUM_125.getMeta(), getResource(ALUMINUM_125.getName()));
		registerBlockModel(ChiselBlocks.aluminum, ALUMINUM_BORDERED.getMeta(), getResource(ALUMINUM_BORDERED.getName()));
		registerBlockModel(ChiselBlocks.aluminum, ALUMINUM_BOLTED.getMeta(), getResource(ALUMINUM_BOLTED.getName()));


		registerBlockModel(ChiselBlocks.cloud, CLOUD_NORMAL.getMeta(), getResource(CLOUD_NORMAL.getName()));
		registerBlockModel(ChiselBlocks.cloud, CLOUD_GRID.getMeta(), getResource(CLOUD_GRID.getName()));
		registerBlockModel(ChiselBlocks.cloud, CLOUD_LARGE.getMeta(), getResource(CLOUD_LARGE.getName()));
		registerBlockModel(ChiselBlocks.cloud, CLOUD_SMALL.getMeta(), getResource(CLOUD_SMALL.getName()));
		registerBlockModel(ChiselBlocks.cloud, CLOUD_VERTICAL.getMeta(), getResource(CLOUD_VERTICAL.getName()));

		registerBlockModel(ChiselBlocks.marble, MARBLE_RAW.getMeta(), getResource(MARBLE_RAW.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_BRICK.getMeta(), getResource(MARBLE_BRICK.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_PANEL_CLASSIC.getMeta(), getResource(MARBLE_PANEL_CLASSIC.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_PANEL_ORNATE.getMeta(), getResource(MARBLE_PANEL_ORNATE.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_PANEL.getMeta(), getResource(MARBLE_PANEL.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_BLOCK.getMeta(), getResource(MARBLE_BLOCK.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_CREEPER_DARK.getMeta(), getResource(MARBLE_CREEPER_DARK.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_CREEPER_LIGHT.getMeta(), getResource(MARBLE_CREEPER_LIGHT.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_CARVED.getMeta(), getResource(MARBLE_CARVED.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_CARVED_RADIAL.getMeta(), getResource(MARBLE_CARVED_RADIAL.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_DENT.getMeta(), getResource(MARBLE_DENT.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_DENT_LARGE.getMeta(), getResource(MARBLE_DENT_LARGE.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_TILES.getMeta(), getResource(MARBLE_TILES.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_TILES_ARRANGED.getMeta(), getResource(MARBLE_TILES_ARRANGED.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_TILES_FANCY.getMeta(), getResource(MARBLE_TILES_FANCY.getName()));
		registerBlockModel(ChiselBlocks.marble, MARBLE_BLOCKS.getMeta(), getResource(MARBLE_BLOCKS.getName()));

		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_RAW.getMeta(), getResource(LIMESTONE_RAW.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_TILES.getMeta(), getResource(LIMESTONE_TILES.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_TILES_FRENCH.getMeta(), getResource(LIMESTONE_TILES_FRENCH.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_TILES_FRENCH_LIGHT.getMeta(), getResource(LIMESTONE_TILES_FRENCH_LIGHT.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_TILES_CREEPER.getMeta(), getResource(LIMESTONE_TILES_CREEPER.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_TILES_DAMAGED.getMeta(), getResource(LIMESTONE_TILES_DAMAGED.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_TILES_LARGE.getMeta(), getResource(LIMESTONE_TILES_LARGE.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_BRICKS.getMeta(), getResource(LIMESTONE_BRICKS.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_SMOOTH.getMeta(), getResource(LIMESTONE_SMOOTH.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_PANEL_ORNATE.getMeta(), getResource(LIMESTONE_PANEL_ORNATE.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_PANEL_ENGRAVED.getMeta(), getResource(LIMESTONE_PANEL_ENGRAVED.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_PANEL_CREEPER.getMeta(), getResource(LIMESTONE_PANEL_CREEPER.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_PANEL_LIGHT.getMeta(), getResource(LIMESTONE_PANEL_LIGHT.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_PANEL_DARK.getMeta(), getResource(LIMESTONE_PANEL_DARK.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_PANEL.getMeta(), getResource(LIMESTONE_PANEL.getName()));
		registerBlockModel(ChiselBlocks.limestone, LIMESTONE_DENT.getMeta(), getResource(LIMESTONE_DENT.getName()));

		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_0.getMeta(), getResource(PUMPKIN_0.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_1.getMeta(), getResource(PUMPKIN_1.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_2.getMeta(), getResource(PUMPKIN_2.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_3.getMeta(), getResource(PUMPKIN_3.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_4.getMeta(), getResource(PUMPKIN_4.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_5.getMeta(), getResource(PUMPKIN_5.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_6.getMeta(), getResource(PUMPKIN_6.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_7.getMeta(), getResource(PUMPKIN_7.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_8.getMeta(), getResource(PUMPKIN_8.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_9.getMeta(), getResource(PUMPKIN_9.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_10.getMeta(), getResource(PUMPKIN_10.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_11.getMeta(), getResource(PUMPKIN_11.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_12.getMeta(), getResource(PUMPKIN_12.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_13.getMeta(), getResource(PUMPKIN_13.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_14.getMeta(), getResource(PUMPKIN_14.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_15.getMeta(), getResource(PUMPKIN_15.getName()));
		registerBlockModel(ChiselBlocks.pumpkin, PUMPKIN_16.getMeta(), getResource(PUMPKIN_16.getName()));

		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_0.getMeta(), getResource(LITPUMPKIN_0.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_1.getMeta(), getResource(LITPUMPKIN_1.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_2.getMeta(), getResource(LITPUMPKIN_2.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_3.getMeta(), getResource(LITPUMPKIN_3.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_4.getMeta(), getResource(LITPUMPKIN_4.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_5.getMeta(), getResource(LITPUMPKIN_5.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_6.getMeta(), getResource(LITPUMPKIN_6.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_7.getMeta(), getResource(LITPUMPKIN_7.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_8.getMeta(), getResource(LITPUMPKIN_8.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_9.getMeta(), getResource(LITPUMPKIN_9.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_10.getMeta(), getResource(LITPUMPKIN_10.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_11.getMeta(), getResource(LITPUMPKIN_11.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_12.getMeta(), getResource(LITPUMPKIN_12.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_13.getMeta(), getResource(LITPUMPKIN_13.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_14.getMeta(), getResource(LITPUMPKIN_14.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_15.getMeta(), getResource(LITPUMPKIN_15.getName()));
		registerBlockModel(ChiselBlocks.litpumpkin, LITPUMPKIN_16.getMeta(), getResource(LITPUMPKIN_16.getName()));

		// ITEMS BELOW.

		registerItemModel(ChiselItems.cloudInABottle);
		registerItemModel(ChiselItems.smashing_rock);
		registerItemModel(ChiselItems.ballOMoss);
		registerItemModels(ChiselItems.upgrade);
		registerItemModel(ChiselItems.chisel);
		registerItemModel(ChiselItems.diamondChisel);
		registerItemModel(ChiselItems.obsidianChisel);
	}

	private static void addVariantNames(Block block, String... names)
	{
		for (int i = 0; i < names.length; i++)
		{
			names[i] = getResource(names[i]);
		}

		ModelBakery.addVariantName(Item.getItemFromBlock(block), names);
	}

	private static void addVariantNames(Item item, String... names)
	{
		for (int i = 0; i < names.length; i++)
		{
			names[i] = getResource(names[i]);
		}

		ModelBakery.addVariantName(item, names);
	}

	private static void registerBlockModel(Block block)
	{
		ResourceLocation resourceLocation = (ResourceLocation) Block.blockRegistry.getNameForObject(block);

		registerBlockModel(block, 0, resourceLocation.toString());
	}

	private static void registerItemModel(Item item)
	{
		ResourceLocation resourceLocation = (ResourceLocation) Item.itemRegistry.getNameForObject(item);

		registerItemModel(item, 0, resourceLocation.toString());
	}

	private static void registerBlockModel(Block block, int meta, String modelName)
	{
		registerItemModel(Item.getItemFromBlock(block), meta, modelName);
	}

	private static void registerItemModel(Item item, int meta, String resourcePath)
	{
		ModelResourceLocation modelResourceLocation = new ModelResourceLocation(resourcePath, "inventory");

		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(item, meta, modelResourceLocation);
	}

	public static void registerItemModels(Item item) {
		for (int i = 0; i < ((IItemWithVariants) item).getVariantNames().length; i++) {
			String NAME = item.getUnlocalizedName().substring(5) + "_" + ((IItemWithVariants) item).getVariantNames()[i];
			registerItemModel(item, i, getResource(NAME));
		}
	}

	public static String getResource(String resource) {
		return (Chisel.MOD_ID + ":") + resource;
	}
}
