package com.cricketcraft.chisel.block.variant;

import com.cricketcraft.chisel.util.BlockVariant;

public class BlockVariants
{
	public static final BlockVariant

			ANDESITE_POLISHED = new BlockVariant(0, "andesite_polished"),
			ANDESITE_PILLAR = new BlockVariant(1, "andesite_pillar"),
			ANDESITE_BRICKS = new BlockVariant(2, "andesite_bricks"),
			ANDESITE_ORNATE = new BlockVariant(3, "andesite_ornate"),
			ANDESITE_PRISMATIC = new BlockVariant(4, "andesite_prismatic"),
			ANDESITE_TILES_SMALL = new BlockVariant(5, "andesite_tiles_small"),

			BRICKS_LARGE = new BlockVariant(0, "bricks_large"),
			BRICKS_MORTARLESS = new BlockVariant(1, "bricks_mortarless"),
			BRICKS_VARIED = new BlockVariant(2, "bricks_varied"),
			BRICKS_AGED = new BlockVariant(3, "bricks_aged"),
			BRICKS_YELLOW = new BlockVariant(4, "bricks_yellow"),

			COBBLESTONE_BRICKS_ALIGNED = new BlockVariant(0, "cobblestone_bricks_aligned"),
			COBBLESTONE_BRICKS_DETAILED = new BlockVariant(1, "cobblestone_bricks_detailed"),
			COBBLESTONE_BRICKS_SMALL = new BlockVariant(2, "cobblestone_bricks_small"),
			COBBLESTONE_TILES_LARGE = new BlockVariant(3, "cobblestone_tiles_large"),
			COBBLESTONE_TILES_SMALL = new BlockVariant(4, "cobblestone_tiles_small"),
			COBBLESTONE_TILES_FRENCH = new BlockVariant(5, "cobblestone_tiles_french"),
			COBBLESTONE_TILES_FRENCH_LIGHT = new BlockVariant(6, "cobblestone_tiles_french_light"),
			COBBLESTONE_TILES_CREEPER = new BlockVariant(7, "cobblestone_tiles_creeper"),
			COBBLESTONE_TILES_DAMAGED = new BlockVariant(8, "cobblestone_tiles_damaged"),
			COBBLESTONE_TILES_HUGE = new BlockVariant(9, "cobblestone_tiles_huge"),
			COBBLESTONE_PANEL_CREEPER = new BlockVariant(10, "cobblestone_panel_creeper"),
			COBBLESTONE_DENT = new BlockVariant(11, "cobblestone_dent"),
			COBBLESTONE_PANEL = new BlockVariant(12, "cobblestone_panel"),
			COBBLESTONE_PANEL_LIGHT = new BlockVariant(13, "cobblestone_panel_light"),
			COBBLESTONE_PANEL_DARK = new BlockVariant(14, "cobblestone_panel_dark"),

			CONCRETE_RAW = new BlockVariant(0, "concrete_raw"),
			CONCRETE_BLOCK = new BlockVariant(1, "concrete_block"),
			CONCRETE_SLAB = new BlockVariant(2, "concrete_slab"),
			CONCRETE_BLOCKS = new BlockVariant(3, "concrete_blocks"),
			CONCRETE_RAW_WEATHERED = new BlockVariant(4, "concrete_raw_weathered"),
			CONCRETE_BLOCK_WEATHERED = new BlockVariant(5, "concrete_block_weathered"),
			CONCRETE_SLAB_WEATHERED = new BlockVariant(6, "concrete_slab_weathered"),
			CONCRETE_BLOCKS_WEATHERED = new BlockVariant(7, "concrete_blocks_weathered"),
			CONCRETE_RAW_PARTLY = new BlockVariant(8, "concrete_raw_partly"),
			CONCRETE_BLOCK_PARTLY = new BlockVariant(9, "concrete_block_partly"),
			CONCRETE_ASPHALT = new BlockVariant(10, "concrete_asphalt"),

			CLOUD_NORMAL = new BlockVariant(0, "cloud_normal"),
			CLOUD_GRID = new BlockVariant(1, "cloud_grid"),
			CLOUD_LARGE = new BlockVariant(2, "cloud_large"),
			CLOUD_SMALL = new BlockVariant(3, "cloud_small"),
			CLOUD_VERTICAL = new BlockVariant(4, "cloud_vertical"),

			DIORITE_POLISHED = new BlockVariant(0, "diorite_polished"),
			DIORITE_PILLAR = new BlockVariant(1, "diorite_pillar"),
			DIORITE_BRICKS = new BlockVariant(2, "diorite_bricks"),
			DIORITE_ORNATE = new BlockVariant(3, "diorite_ornate"),
			DIORITE_PRISMATIC = new BlockVariant(4, "diorite_prismatic"),
			DIORITE_TILES_SMALL = new BlockVariant(5, "diorite_tiles_small"),

			FANTASY_BRICK = new BlockVariant(0, "fantasy_brick"),
			FANTASY_BRICK_FADED = new BlockVariant(1, "fantasy_brick_faded"),
			FANTASY_BRICK_WORN = new BlockVariant(2, "fantasy_brick_faded"),
			FANTASY_BRICK_DAMAGED = new BlockVariant(3, "purpled_fantasy_brick_faded"),
			FANTASY_DECORATION = new BlockVariant(4, "fantasy_brick_faded"),
			FANTASY_DECORATION_BLOCK = new BlockVariant(5, "fantasy_brick_faded"),
			FANTASY_DECORATION_PILLAR = new BlockVariant(6, "fantasy_brick_faded"),
			FANTASY_PILLAR = new BlockVariant(7, "fantasy_brick_faded"),
			FANTASY_DECORATION_SNAKE = new BlockVariant(8, "fantasy_brick_faded"),
			FANTASY_DECORATION_NOISE = new BlockVariant(9, "fantasy_brick_faded"),
			FANTASY_DECORATION_ENGRAVING = new BlockVariant(10, "fantasy_brick_faded"),
			FANTASY_DECORATION_CHAINS = new BlockVariant(11, "fantasy_brick_faded"),
			FANTASY_DECORATION_PLATE = new BlockVariant(12, "fantasy_brick_faded"),
			FANTASY_BLOCK = new BlockVariant(13, "fantasy_brick_faded"),
			FANTASY_BRICKS_DISARRAY = new BlockVariant(14, "fantasy_brick_faded"),
			FANTASY_BRICKS_DISARRAY_WORN = new BlockVariant(15, "fantasy_brick_faded"),

			GRANITE_POLISHED = new BlockVariant(0, "granite_polished"),
			GRANITE_PILLAR = new BlockVariant(1, "granite_pillar"),
			GRANITE_BRICKS = new BlockVariant(2, "granite_bricks"),
			GRANITE_ORNATE = new BlockVariant(3, "granite_ornate"),
			GRANITE_PRISMATIC = new BlockVariant(4, "granite_prismatic"),
			GRANITE_TILES_SMALL = new BlockVariant(5, "granite_tiles_small"),

			GRIMSTONE_RAW = new BlockVariant(0, "grimstone_raw"),
			GRIMSTONE_SMOOTH = new BlockVariant(1, "grimstone_smooth"),
			GRIMSTONE_SYMBOL = new BlockVariant(2, "grimstone_symbol"),
			GRIMSTONE_CHISELED = new BlockVariant(3, "grimstone_chiseled"),
			GRIMSTONE_BLOCKS = new BlockVariant(4, "grimstone_blocks"),
			GRIMSTONE_BLOCKS_ROUGH = new BlockVariant(5, "grimstone_blocks_rough"),
			GRIMSTONE_BRICKS = new BlockVariant(6, "grimstone_bricks"),
			GRIMSTONE_BRICKS_LARGE = new BlockVariant(7, "grimstone_bricks_large"),
			GRIMSTONE_PLATFORM = new BlockVariant(8, "grimstone_platform"),
			GRIMSTONE_PLATFORM_TILES = new BlockVariant(9, "grimstone_platform_tiles"),
			GRIMSTONE_CONSTRUCTION = new BlockVariant(10, "grimstone_construction"),
			GRIMSTONE_TILES = new BlockVariant(11, "grimstone_tiles"),
			GRIMSTONE_PLATE_SMOOTH = new BlockVariant(12, "grimstone_plate_smooth"),
			GRIMSTONE_PLATE = new BlockVariant(13, "grimstone_plate"),
			GRIMSTONE_FLAKY = new BlockVariant(14, "grimstone_flaky"),

			HOLYSTONE_RAW = new BlockVariant(0, "holystone_raw"),
			HOLYSTONE_SMOOTH = new BlockVariant(1, "holystone_smooth"),
			HOLYSTONE_SYMBOL = new BlockVariant(2, "holystone_symbol"),
			HOLYSTONE_CHISELED = new BlockVariant(3, "holystone_chiseled"),
			HOLYSTONE_BLOCKS = new BlockVariant(4, "holystone_blocks"),
			HOLYSTONE_BLOCKS_ROUGH = new BlockVariant(5, "holystonee_blocks_rough"),
			HOLYSTONE_BRICKS = new BlockVariant(6, "holystone_bricks"),
			HOLYSTONE_BRICKS_LARGE = new BlockVariant(7, "holystone_bricks_large"),
			HOLYSTONE_PLATFORM = new BlockVariant(8, "grimstone_platform"),
			HOLYSTONE_PLATFORM_TILES = new BlockVariant(9, "grimstone_platform_tiles"),
			HOLYSTONE_CONSTRUCTION = new BlockVariant(10, "grimstone_construction"),
			HOLYSTONE_TILES = new BlockVariant(11, "grimstone_tiles"),
			HOLYSTONE_PLATE_SMOOTH = new BlockVariant(12, "grimstone_plate_smooth"),
			HOLYSTONE_PLATE = new BlockVariant(13, "grimstone_plate"),

			LIMESTONE_RAW = new BlockVariant(0, "limestone_raw"),
			LIMESTONE_TILES = new BlockVariant(1, "limestone_tiles"),
			LIMESTONE_TILES_FRENCH = new BlockVariant(2, "limestone_tiles_french"),
			LIMESTONE_TILES_FRENCH_LIGHT = new BlockVariant(2, "limestone_tiles_french_light"),
			LIMESTONE_TILES_CREEPER = new BlockVariant(3, "limestone_tiles_creeper"),
			LIMESTONE_TILES_DAMAGED = new BlockVariant(4, "limestone_tiles_damaged"),
			LIMESTONE_TILES_LARGE = new BlockVariant(5, "limestone_tiles_large"),
			LIMESTONE_BRICKS = new BlockVariant(6, "limestone_bricks"),
			LIMESTONE_SMOOTH = new BlockVariant(7, "limestone_smooth"),
			LIMESTONE_PANEL_ORNATE = new BlockVariant(8, "limestone_panel_ornate"),
			LIMESTONE_PANEL_ENGRAVED = new BlockVariant(9, "limestone_panel_engraved"),
			LIMESTONE_PANEL_CREEPER = new BlockVariant(10, "limestone_panel_creeper"),
			LIMESTONE_PANEL_LIGHT = new BlockVariant(11, "limestone_panel_light"),
			LIMESTONE_PANEL_DARK = new BlockVariant(12, "limestone_panel_dark"),
			LIMESTONE_PANEL = new BlockVariant(13, "limestone_panel"),
			LIMESTONE_DENT = new BlockVariant(14, "limestone_dent"),

			LITPUMPKIN_0 = new BlockVariant(0, "litpumpkin_0"),
			LITPUMPKIN_1 = new BlockVariant(1, "litpumpkin_1"),
			LITPUMPKIN_2 = new BlockVariant(2, "litpumpkin_2"),
			LITPUMPKIN_3 = new BlockVariant(3, "litpumpkin_3"),
			LITPUMPKIN_4 = new BlockVariant(4, "litpumpkin_4"),
			LITPUMPKIN_5 = new BlockVariant(5, "litpumpkin_5"),
			LITPUMPKIN_6 = new BlockVariant(6, "litpumpkin_6"),
			LITPUMPKIN_7 = new BlockVariant(7, "litpumpkin_7"),
			LITPUMPKIN_8 = new BlockVariant(8, "litpumpkin_8"),
			LITPUMPKIN_9 = new BlockVariant(9, "litpumpkin_9"),
			LITPUMPKIN_10 = new BlockVariant(10, "litpumpkin_10"),
			LITPUMPKIN_11 = new BlockVariant(11, "litpumpkin_11"),
			LITPUMPKIN_12 = new BlockVariant(12, "litpumpkin_12"),
			LITPUMPKIN_13 = new BlockVariant(13, "litpumpkin_13"),
			LITPUMPKIN_14 = new BlockVariant(14, "litpumpkin_14"),
			LITPUMPKIN_15 = new BlockVariant(15, "litpumpkin_15"),
			LITPUMPKIN_16 = new BlockVariant(16, "litpumpkin_16"),

			MARBLE_RAW = new BlockVariant(0, "marble_raw"),
			MARBLE_BRICK = new BlockVariant(1, "marble_brick"),
			MARBLE_PANEL_CLASSIC = new BlockVariant(2, "marble_panel_classic"),
			MARBLE_PANEL_ORNATE = new BlockVariant(3, "marble_panel_ornate"),
			MARBLE_PANEL = new BlockVariant(4, "marble_panel"),
			MARBLE_BLOCK = new BlockVariant(5, "marble_block"),
			MARBLE_CREEPER_DARK = new BlockVariant(6, "marble_creeper_dark"),
			MARBLE_CREEPER_LIGHT = new BlockVariant(7, "marble_creeper_light"),
			MARBLE_CARVED = new BlockVariant(8, "marble_carved"),
			MARBLE_CARVED_RADIAL = new BlockVariant(9, "marble_carved_radial"),
			MARBLE_DENT = new BlockVariant(10, "marble_dent"),
			MARBLE_DENT_LARGE = new BlockVariant(11, "marble_dent_large"),
			MARBLE_TILES = new BlockVariant(12, "marble_tiles"),
			MARBLE_TILES_ARRANGED = new BlockVariant(13, "marble_tiles_arranged"),
			MARBLE_TILES_FANCY = new BlockVariant(14, "marble_tiles_fancy"),
			MARBLE_BLOCKS = new BlockVariant(15, "marble_blocks"),

			MOSSY_COBBLESTONE_BRICKS_ALIGNED = new BlockVariant(0, "mossy_cobblestone_bricks_aligned"),
			MOSSY_COBBLESTONE_BRICKS_DETAILED = new BlockVariant(1, "mossy_cobblestone_bricks_detailed"),
			MOSSY_COBBLESTONE_BRICKS_SMALL = new BlockVariant(2, "mossy_cobblestone_bricks_small"),
			MOSSY_COBBLESTONE_TILES_LARGE = new BlockVariant(3, "mossy_cobblestone_tiles_large"),
			MOSSY_COBBLESTONE_TILES_SMALL = new BlockVariant(4, "mossy_cobblestone_tiles_small"),
			MOSSY_COBBLESTONE_TILES_FRENCH = new BlockVariant(5, "mossy_cobblestone_tiles_french"),
			MOSSY_COBBLESTONE_TILES_FRENCH_LIGHT = new BlockVariant(6, "mossy_cobblestone_tiles_french_light"),
			MOSSY_COBBLESTONE_TILES_CREEPER = new BlockVariant(7, "mossy_cobblestone_tiles_creeper"),
			MOSSY_COBBLESTONE_TILES_DAMAGED = new BlockVariant(8, "mossy_cobblestone_tiles_damaged"),
			MOSSY_COBBLESTONE_TILES_HUGE = new BlockVariant(9, "mossy_cobblestone_tiles_huge"),
			MOSSY_COBBLESTONE_PANEL_CREEPER = new BlockVariant(10, "mossy_cobblestone_panel_creeper"),
			MOSSY_COBBLESTONE_DENT = new BlockVariant(11, "mossy_cobblestone_dent"),
			MOSSY_COBBLESTONE_PANEL = new BlockVariant(12, "mossy_cobblestone_panel"),
			MOSSY_COBBLESTONE_PANEL_LIGHT = new BlockVariant(13, "mossy_cobblestone_panel_light"),
			MOSSY_COBBLESTONE_PANEL_DARK = new BlockVariant(14, "mossy_cobblestone_panel_dark"),

			PUMPKIN_0 = new BlockVariant(0, "pumpkin_0"),
			PUMPKIN_1 = new BlockVariant(1, "pumpkin_1"),
			PUMPKIN_2 = new BlockVariant(2, "pumpkin_2"),
			PUMPKIN_3 = new BlockVariant(3, "pumpkin_3"),
			PUMPKIN_4 = new BlockVariant(4, "pumpkin_4"),
			PUMPKIN_5 = new BlockVariant(5, "pumpkin_5"),
			PUMPKIN_6 = new BlockVariant(6, "pumpkin_6"),
			PUMPKIN_7 = new BlockVariant(7, "pumpkin_7"),
			PUMPKIN_8 = new BlockVariant(8, "pumpkin_8"),
			PUMPKIN_9 = new BlockVariant(9, "pumpkin_9"),
			PUMPKIN_10 = new BlockVariant(10, "pumpkin_10"),
			PUMPKIN_11 = new BlockVariant(11, "pumpkin_11"),
			PUMPKIN_12 = new BlockVariant(12, "pumpkin_12"),
			PUMPKIN_13 = new BlockVariant(13, "pumpkin_13"),
			PUMPKIN_14 = new BlockVariant(14, "pumpkin_14"),
			PUMPKIN_15 = new BlockVariant(15, "pumpkin_15"),
			PUMPKIN_16 = new BlockVariant(16, "pumpkin_16"),

			PURPLED_FANTASY_BRICK = new BlockVariant(0, "purpled_fantasy_brick"),
			PURPLED_FANTASY_BRICK_FADED = new BlockVariant(1, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_BRICK_WORN = new BlockVariant(2, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_BRICK_DAMAGED = new BlockVariant(3, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION = new BlockVariant(4, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_BLOCK = new BlockVariant(5, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_PILLAR = new BlockVariant(6, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_PILLAR = new BlockVariant(7, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_SNAKE = new BlockVariant(8, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_NOISE = new BlockVariant(9, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_ENGRAVING = new BlockVariant(10, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_CHAINS = new BlockVariant(11, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_PLATE = new BlockVariant(12, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_BLOCK = new BlockVariant(13, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_BRICKS_DISARRAY = new BlockVariant(14, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_BRICKS_DISARRAY_WORN = new BlockVariant(15, "purpled_fantasy_brick_faded");

}
