package com.cricketcraft.chisel.block.variant;

import com.cricketcraft.chisel.util.BlockVariant;

public class BlockVariants {
	public static final BlockVariant

			ACACIA_PLANKS_SMOOTH = new BlockVariant(0, "acacia_planks_smooth"),
			ACACIA_PLANKS_SHORT = new BlockVariant(1, "acacia_planks_short"),
			ACACIA_PLANKS_FANCY = new BlockVariant(2, "acacia_planks_fancy"),
			ACACIA_PLANKS_PANEL = new BlockVariant(3, "acacia_planks_panel"),
			ACACIA_PLANKS_DOUBLE_SLAB = new BlockVariant(4, "acacia_planks_double_slab"),
			ACACIA_PLANKS_CRATE = new BlockVariant(5, "acacia_planks_crate"),
			ACACIA_PLANKS_CRATE_FANCY = new BlockVariant(6, "acacia_planks_crate_fancy"),
			ACACIA_PLANKS_LONG = new BlockVariant(7, "acacia_planks_long"),
			ACACIA_PLANKS_VERTICAL = new BlockVariant(8, "acacia_planks_vertical"),
			ACACIA_PLANKS_VERTICAL_UNEVEN = new BlockVariant(9, "acacia_planks_vertical_uneven"),
			ACACIA_PLANKS_PARQUET = new BlockVariant(10, "acacia_planks_parquet"),
			ACACIA_PLANKS_BLINDS = new BlockVariant(11, "acacia_planks_blinds"),
			ACACIA_PLANKS_SCAFFOLD = new BlockVariant(12, "acacia_planks_scaffold"),
			ACACIA_PLANKS_DISARRAY = new BlockVariant(13, "acacia_planks_disarray"),
			ACACIA_PLANKS_DISARRAY_VERTICAL = new BlockVariant(14, "acacia_planks_disarray_vertical"),

			ALUMINUM_CAUTION = new BlockVariant(0, "aluminum_caution"),
			ALUMINUM_SHIPPING = new BlockVariant(1, "aluminum_shipping"),
			ALUMINUM_THERMAL = new BlockVariant(2, "aluminum_thermal"),
			ALUMINUM_125 = new BlockVariant(3, "aluminum_125"),
			ALUMINUM_BORDERED = new BlockVariant(4, "aluminum_bordered"),
			ALUMINUM_BOLTED = new BlockVariant(5, "aluminum_bolted"),

			ANDESITE_PILLAR = new BlockVariant(0, "andesite_pillar"),
			ANDESITE_BRICKS = new BlockVariant(1, "andesite_bricks"),
			ANDESITE_ORNATE = new BlockVariant(2, "andesite_ornate"),
			ANDESITE_PRISMATIC = new BlockVariant(3, "andesite_prismatic"),
			ANDESITE_TILES_SMALL = new BlockVariant(4, "andesite_tiles_small"),

			ANTIBLOCK_0 = new BlockVariant(0, "antiblock_0"),
			ANTIBLOCK_1 = new BlockVariant(1, "antiblock_1"),
			ANTIBLOCK_2 = new BlockVariant(2, "antiblock_2"),
			ANTIBLOCK_3 = new BlockVariant(3, "antiblock_3"),
			ANTIBLOCK_4 = new BlockVariant(4, "antiblock_4"),
			ANTIBLOCK_5 = new BlockVariant(5, "antiblock_5"),
			ANTIBLOCK_6 = new BlockVariant(6, "antiblock_6"),
			ANTIBLOCK_7 = new BlockVariant(7, "antiblock_7"),
			ANTIBLOCK_8 = new BlockVariant(8, "antiblock_8"),
			ANTIBLOCK_9 = new BlockVariant(9, "antiblock_9"),
			ANTIBLOCK_10 = new BlockVariant(10, "antiblock_10"),
			ANTIBLOCK_11 = new BlockVariant(11, "antiblock_11"),
			ANTIBLOCK_12 = new BlockVariant(12, "antiblock_12"),
			ANTIBLOCK_13 = new BlockVariant(13, "antiblock_13"),
			ANTIBLOCK_14 = new BlockVariant(14, "antiblock_14"),
			ANTIBLOCK_15 = new BlockVariant(15, "antiblock_15"),

			BIRCH_PLANKS_SMOOTH = new BlockVariant(0, "birch_planks_smooth"),
			BIRCH_PLANKS_SHORT = new BlockVariant(1, "birch_planks_short"),
			BIRCH_PLANKS_FANCY = new BlockVariant(2, "birch_planks_fancy"),
			BIRCH_PLANKS_PANEL = new BlockVariant(3, "birch_planks_panel"),
			BIRCH_PLANKS_DOUBLE_SLAB = new BlockVariant(4, "birch_planks_double_slab"),
			BIRCH_PLANKS_CRATE = new BlockVariant(5, "birch_planks_crate"),
			BIRCH_PLANKS_CRATE_FANCY = new BlockVariant(6, "birch_planks_crate_fancy"),
			BIRCH_PLANKS_LONG = new BlockVariant(7, "birch_planks_long"),
			BIRCH_PLANKS_VERTICAL = new BlockVariant(8, "birch_planks_vertical"),
			BIRCH_PLANKS_VERTICAL_UNEVEN = new BlockVariant(9, "birch_planks_vertical_uneven"),
			BIRCH_PLANKS_PARQUET = new BlockVariant(10, "birch_planks_parquet"),
			BIRCH_PLANKS_BLINDS = new BlockVariant(11, "birch_planks_blinds"),
			BIRCH_PLANKS_SCAFFOLD = new BlockVariant(12, "birch_planks_scaffold"),
			BIRCH_PLANKS_DISARRAY = new BlockVariant(13, "birch_planks_disarray"),
			BIRCH_PLANKS_DISARRAY_VERTICAL = new BlockVariant(14, "birch_planks_disarray_vertical"),

			BOOKSHELF_RAINBOW = new BlockVariant(1, "bookshelf_rainbow"),
			BOOKSHELF_NECROMANCER_APPRENTICE = new BlockVariant(2, "bookshelf_necromancer_apprentice"),
			BOOKSHELF_NECROMANCER = new BlockVariant(3, "bookshelf_necromancer"),
			BOOKSHELF_TOMES = new BlockVariant(4, "bookshelf_tomes"),
			BOOKSHELF_ABANDONED = new BlockVariant(5, "bookshelf_abandoned"),
			BOOKSHELF_HOARDERS = new BlockVariant(6, "bookshelf_hoarders"),
			BOOKSHELF_PASTEL = new BlockVariant(7, "bookshelf_pastel"),
			BOOKSHELF_HISTORIAN = new BlockVariant(8, "bookshelf_historian"),

			BRICKS_LARGE = new BlockVariant(0, "bricks_large"),
			BRICKS_MORTARLESS = new BlockVariant(1, "bricks_mortarless"),
			BRICKS_VARIED = new BlockVariant(2, "bricks_varied"),
			BRICKS_AGED = new BlockVariant(3, "bricks_aged"),
			BRICKS_YELLOW = new BlockVariant(4, "bricks_yellow"),

			BRONZE_CAUTION = new BlockVariant(0, "bronze_caution"),
			BRONZE_SHIPPING = new BlockVariant(1, "bronze_shipping"),
			BRONZE_THERMAL = new BlockVariant(2, "bronze_thermal"),
			BRONZE_125 = new BlockVariant(3, "bronze_125"),
			BRONZE_BORDERED = new BlockVariant(4, "bronze_bordered"),
			BRONZE_BOLTED = new BlockVariant(5, "bronze_bolted"),

			CARPET_0 = new BlockVariant(0, "carpet_0"),
			CARPET_1 = new BlockVariant(1, "carpet_1"),
			CARPET_2 = new BlockVariant(2, "carpet_2"),
			CARPET_3 = new BlockVariant(3, "carpet_3"),
			CARPET_4 = new BlockVariant(4, "carpet_4"),
			CARPET_5 = new BlockVariant(5, "carpet_5"),
			CARPET_6 = new BlockVariant(6, "carpet_6"),
			CARPET_7 = new BlockVariant(7, "carpet_7"),
			CARPET_8 = new BlockVariant(8, "carpet_8"),
			CARPET_9 = new BlockVariant(9, "carpet_9"),
			CARPET_10 = new BlockVariant(10, "carpet_10"),
			CARPET_11 = new BlockVariant(11, "carpet_11"),
			CARPET_12 = new BlockVariant(12, "carpet_12"),
			CARPET_13 = new BlockVariant(13, "carpet_13"),
			CARPET_14 = new BlockVariant(14, "carpet_14"),
			CARPET_15 = new BlockVariant(15, "carpet_15"),

			CARPET_FLOOR_0 = new BlockVariant(0, "carpet_floor_0"),
			CARPET_FLOOR_1 = new BlockVariant(1, "carpet_floor_1"),
			CARPET_FLOOR_2 = new BlockVariant(2, "carpet_floor_2"),
			CARPET_FLOOR_3 = new BlockVariant(3, "carpet_floor_3"),
			CARPET_FLOOR_4 = new BlockVariant(4, "carpet_floor_4"),
			CARPET_FLOOR_5 = new BlockVariant(5, "carpet_floor_5"),
			CARPET_FLOOR_6 = new BlockVariant(6, "carpet_floor_6"),
			CARPET_FLOOR_7 = new BlockVariant(7, "carpet_floor_7"),
			CARPET_FLOOR_8 = new BlockVariant(8, "carpet_floor_8"),
			CARPET_FLOOR_9 = new BlockVariant(9, "carpet_floor_9"),
			CARPET_FLOOR_10 = new BlockVariant(10, "carpet_floor_10"),
			CARPET_FLOOR_11 = new BlockVariant(11, "carpet_floor_11"),
			CARPET_FLOOR_12 = new BlockVariant(12, "carpet_floor_12"),
			CARPET_FLOOR_13 = new BlockVariant(13, "carpet_floor_13"),
			CARPET_FLOOR_14 = new BlockVariant(14, "carpet_floor_14"),
			CARPET_FLOOR_15 = new BlockVariant(15, "carpet_floor_15"),

			CHEST_0 = new BlockVariant(0, "chest_0"),
			CHEST_1 = new BlockVariant(1, "chest_1"),
			CHEST_2 = new BlockVariant(2, "chest_2"),
			CHEST_3 = new BlockVariant(3, "chest_3"),
			CHEST_4 = new BlockVariant(4, "chest_4"),
			CHEST_5 = new BlockVariant(5, "chest_5"),
			CHEST_6 = new BlockVariant(6, "chest_6"),
			CHEST_7 = new BlockVariant(7, "chest_7"),
			CHEST_8 = new BlockVariant(8, "chest_8"),
			CHEST_9 = new BlockVariant(9, "chest_9"),
			CHEST_10 = new BlockVariant(10, "chest_10"),
			CHEST_11 = new BlockVariant(11, "chest_11"),
			CHEST_12 = new BlockVariant(12, "chest_12"),
			CHEST_13 = new BlockVariant(13, "chest_13"),
			CHEST_14 = new BlockVariant(14, "chest_14"),
			CHEST_15 = new BlockVariant(15, "chest_15"),

			COBBLESTONE_BRICKS_ALIGNED = new BlockVariant(0, "cobblestone_bricks_aligned"),
			COBBLESTONE_BRICKS_DETAILED = new BlockVariant(1, "cobblestone_bricks_detailed"),
			COBBLESTONE_BRICKS_SMALL = new BlockVariant(2, "cobblestone_bricks_small"),
			COBBLESTONE_TILES_LARGE = new BlockVariant(3, "cobblestone_tiles_large"),
			COBBLESTONE_TILES_SMALL = new BlockVariant(4, "cobblestone_tiles_small"),
			COBBLESTONE_TILES_FRENCH = new BlockVariant(5, "cobblestone_tiles_french"),
			COBBLESTONE_TILES_FRENCH_LIGHT = new BlockVariant(6, "cobblestone_tiles_french_light"),
			COBBLESTONE_TILES_CREEPER = new BlockVariant(7, "cobblestone_tiles_creeper"),
			COBBLESTONE_TILES_DAMAGED = new BlockVariant(8, "cobblestone_tiles_damaged"),
			COBBLESTONE_TILES_HUGE = new BlockVariant(9, "cobblestone_tiles_huge"),
			COBBLESTONE_PANEL_CREEPER = new BlockVariant(10, "cobblestone_panel_creeper"),
			COBBLESTONE_DENT = new BlockVariant(11, "cobblestone_dent"),
			COBBLESTONE_PANEL = new BlockVariant(12, "cobblestone_panel"),
			COBBLESTONE_PANEL_LIGHT = new BlockVariant(13, "cobblestone_panel_light"),
			COBBLESTONE_PANEL_DARK = new BlockVariant(14, "cobblestone_panel_dark"),

			CONCRETE_RAW = new BlockVariant(0, "concrete_raw"),
			CONCRETE_BLOCK = new BlockVariant(1, "concrete_block"),
			CONCRETE_SLAB = new BlockVariant(2, "concrete_slab"),
			CONCRETE_BLOCKS = new BlockVariant(3, "concrete_blocks"),
			CONCRETE_RAW_WEATHERED = new BlockVariant(4, "concrete_raw_weathered"),
			CONCRETE_BLOCK_WEATHERED = new BlockVariant(5, "concrete_block_weathered"),
			CONCRETE_SLAB_WEATHERED = new BlockVariant(6, "concrete_slab_weathered"),
			CONCRETE_BLOCKS_WEATHERED = new BlockVariant(7, "concrete_blocks_weathered"),
			CONCRETE_RAW_PARTLY = new BlockVariant(8, "concrete_raw_partly"),
			CONCRETE_BLOCK_PARTLY = new BlockVariant(9, "concrete_block_partly"),
			CONCRETE_ASPHALT = new BlockVariant(10, "concrete_asphalt"),

			COPPER_CAUTION = new BlockVariant(0, "copper_caution"),
			COPPER_SHIPPING = new BlockVariant(1, "copper_shipping"),
			COPPER_THERMAL = new BlockVariant(2, "copper_thermal"),
			COPPER_125 = new BlockVariant(3, "copper_125"),
			COPPER_BORDERED = new BlockVariant(4, "copper_bordered"),
			COPPER_BOLTED = new BlockVariant(5, "copper_bolted"),

			CLOUD_NORMAL = new BlockVariant(0, "cloud_normal"),
			CLOUD_GRID = new BlockVariant(1, "cloud_grid"),
			CLOUD_LARGE = new BlockVariant(2, "cloud_large"),
			CLOUD_SMALL = new BlockVariant(3, "cloud_small"),
			CLOUD_VERTICAL = new BlockVariant(4, "cloud_vertical"),

			DARK_OAK_PLANKS_SMOOTH = new BlockVariant(0, "dark_oak_planks_smooth"),
			DARK_OAK_PLANKS_SHORT = new BlockVariant(1, "dark_oak_planks_short"),
			DARK_OAK_PLANKS_FANCY = new BlockVariant(2, "dark_oak_planks_fancy"),
			DARK_OAK_PLANKS_PANEL = new BlockVariant(3, "dark_oak_planks_panel"),
			DARK_OAK_PLANKS_DOUBLE_SLAB = new BlockVariant(4, "dark_oak_planks_double_slab"),
			DARK_OAK_PLANKS_CRATE = new BlockVariant(5, "dark_oak_planks_crate"),
			DARK_OAK_PLANKS_CRATE_FANCY = new BlockVariant(6, "dark_oak_planks_crate_fancy"),
			DARK_OAK_PLANKS_LONG = new BlockVariant(7, "dark_oak_planks_long"),
			DARK_OAK_PLANKS_VERTICAL = new BlockVariant(8, "dark_oak_planks_vertical"),
			DARK_OAK_PLANKS_VERTICAL_UNEVEN = new BlockVariant(9, "dark_oak_planks_vertical_uneven"),
			DARK_OAK_PLANKS_PARQUET = new BlockVariant(10, "dark_oak_planks_parquet"),
			DARK_OAK_PLANKS_BLINDS = new BlockVariant(11, "dark_oak_planks_blinds"),
			DARK_OAK_PLANKS_SCAFFOLD = new BlockVariant(12, "dark_oak_planks_scaffold"),
			DARK_OAK_PLANKS_DISARRAY = new BlockVariant(13, "dark_oak_planks_disarray"),
			DARK_OAK_PLANKS_DISARRAY_VERTICAL = new BlockVariant(14, "dark_oak_planks_disarray_vertical"),

			DIAMOND_EMBOSSED = new BlockVariant(0, "diamond_embossed"),
			DIAMOND_PANEL = new BlockVariant(1, "diamond_panel"),
			DIAMOND_CELLS = new BlockVariant(2, "diamond_cells"),
			DIAMOND_OBSIDIAN_PURPLE = new BlockVariant(3, "diamond_obsidian_purple"),
			DIAMOND_OBSIDIAN = new BlockVariant(4, "diamond_obsidian"),
			DIAMOND_SIMPLE = new BlockVariant(5, "diamond_simple"),
			DIAMOND_BISMUTH = new BlockVariant(6, "diamond_bismuth"),
			DIAMOND_CRUSHED = new BlockVariant(7, "diamond_crushed"),
			DIAMOND_SMALL_BLOCKS = new BlockVariant(8, "diamond_small_blocks"),
			DIAMOND_SMALL_BLOCKS_ORNATE = new BlockVariant(9, "diamond_small_blocks_ornate"),
			DIAMOND_ZELDA = new BlockVariant(10, "diamond_zelda"),
			DIAMOND_ORNATE = new BlockVariant(11, "diamond_ornate"),

			DIORITE_POLISHED = new BlockVariant(0, "diorite_polished"),
			DIORITE_PILLAR = new BlockVariant(1, "diorite_pillar"),
			DIORITE_BRICKS = new BlockVariant(2, "diorite_bricks"),
			DIORITE_ORNATE = new BlockVariant(3, "diorite_ornate"),
			DIORITE_PRISMATIC = new BlockVariant(4, "diorite_prismatic"),
			DIORITE_TILES_SMALL = new BlockVariant(5, "diorite_tiles_small"),

			DIRT_BRICKS_DISARRAY = new BlockVariant(0, "dirt_bricks_disarray"),
			DIRT_NETHER = new BlockVariant(1, "dirt_nether"),
			DIRT_BRICKS = new BlockVariant(2, "dirt_bricks"),
			DIRT_COBBLE = new BlockVariant(3, "dirt_cobble"),
			DIRT_COBBLE_REINFORCED = new BlockVariant(4, "dirt_cobble_reinforced"),
			DIRT_REINFORCED = new BlockVariant(5, "dirt_reinforced"),
			DIRT_HAPPY = new BlockVariant(6, "dirt_happy"),
			DIRT_BRICKS_LARGE = new BlockVariant(7, "dirt_bricks_large"),
			DIRT_BRICKS_LARGE_ON = new BlockVariant(8, "dirt_bricks_large_on"),
			DIRT_HORIZONTAL = new BlockVariant(9, "dirt_horizontal"),
			DIRT_VERTICAL = new BlockVariant(10, "dirt_vertical"),
			DIRT_LAYERS = new BlockVariant(11, "dirt_layers"),
			DIRT_CRUMBLING = new BlockVariant(12, "dirt_crumbling"),
			DIRT_CHUNKY = new BlockVariant(13, "dirt_chunky"),
			DIRT_HORIZONTAL2 = new BlockVariant(14, "dirt_horizontal2"),
			DIRT_PLATE = new BlockVariant(14, "dirt_plate"),

			EMERALD_PANEL = new BlockVariant(0, "emerald_panel"),
			EMERALD_PANEL_CLASSIC = new BlockVariant(1, "emerald_panel_classic"),
			EMERALD_SMOOTH = new BlockVariant(2, "emerald_smooth"),
			EMERALD_CHUNK = new BlockVariant(3, "emerald_chunk"),
			EMERALD_ORNATE_LAYER = new BlockVariant(4, "emerald_ornate_layer"),
			EMERALD_ZELDA = new BlockVariant(5, "emerald_zelda"),
			EMERALD_CELL = new BlockVariant(6, "emerald_cell"),
			EMERALD_BISMUTH = new BlockVariant(7, "emerald_bismuth"),
			EMERALD_BLOCKS_SMALL = new BlockVariant(8, "emerald_blocks_small"),
			EMERALD_BLOCKS_SMALL_ORNATE = new BlockVariant(9, "emerald_blocks_small_ornate"),
			EMERALD_ORNATE = new BlockVariant(10, "emerald_ornate"),

			ENERGISED_VOIDSTONE_RAW = new BlockVariant(0, "energised_voidstone_raw"),
			ENERGISED_VOIDSTONE_TILES = new BlockVariant(1, "energised_voidstone_tiles"),
			ENERGISED_VOIDSTONE_SMOOTH = new BlockVariant(2, "energised_voidstone_smooth"),
			ENERGISED_VOIDSTONE_SKULL = new BlockVariant(3, "energised_voidstone_skull"),
			ENERGISED_VOIDSTONE_RUNIC = new BlockVariant(4, "energised_voidstone_runic"),
			ENERGISED_VOIDSTONE_METAL = new BlockVariant(5, "energised_voidstone_metal"),
			ENERGISED_VOIDSTONE_EYE = new BlockVariant(6, "energised_voidstone_eye"),
			ENERGISED_VOIDSTONE_BEVEL = new BlockVariant(7, "energised_voidstone_bevel"),

			ENERGISED_VOIDSTONE_PILLAR_NORMAL = new BlockVariant(0, "energized_voidstone_pillar_normal"),

			FACTORY_RUSTY_DOTTED = new BlockVariant(0, "factory_rusty_dotted"),
			FACTORY_RUSTY_PLATE = new BlockVariant(1, "factory_rusty_plate"),
			FACTORY_RUSTY_VERY = new BlockVariant(2, "factory_rusty_very"),
			FACTORY_RUSTY_LITTLE = new BlockVariant(3, "factory_rusty_little"),
			FACTORY_WIREFRAME = new BlockVariant(4, "factory_wireframe"),
			FACTORY_WIREFRAME_PURPLE = new BlockVariant(5, "factory_wireframe_purple"),
			FACTORY_HAZARD_YELLOW = new BlockVariant(6, "factory_hazard_yellow"),
			FACTORY_HAZARD_ORANGE = new BlockVariant(7, "factory_hazard_orange"),
			FACTORY_CIRCUIT_FANCY = new BlockVariant(8, "factory_circuit_fancy"),
			FACTORY_METAL = new BlockVariant(9, "factory_metal"),
			FACTORY_GOLD_CIRCUIT = new BlockVariant(10, "factory_gold_circuit"),
			FACTORY_GOLD_PURPLE = new BlockVariant(11, "factory_gold_purple"),
			FACTORY_CONSTRUCTION = new BlockVariant(12, "factory_construction"),
			FACTORY_VENT_WORN = new BlockVariant(13, "factory_vent_worn"),
			FACTORY_RUSTY_PLATES = new BlockVariant(14, "factory_rusty_plates"),
			FACTORY_COLUMN = new BlockVariant(15, "factory_column"),
			FACTORY_BLUE = new BlockVariant(16, "factory_blue"),
			FACTORY_VENT_VERTICAL = new BlockVariant(17, "factory_vent_vertical"),
			FACTORY_CIRCUIT_BLUE = new BlockVariant(18, "factory_circuit_blue"),
			FACTORY_WIREFRAME_BLUE = new BlockVariant(19, "factory_wireframe_blue"),

			FANTASY_BRICK = new BlockVariant(0, "fantasy_brick"),
			FANTASY_BRICK_FADED = new BlockVariant(1, "fantasy_brick_faded"),
			FANTASY_BRICK_WORN = new BlockVariant(2, "fantasy_brick_worn"),
			FANTASY_BRICK_DAMAGED = new BlockVariant(3, "fantasy_brick_damaged"),
			FANTASY_DECORATION = new BlockVariant(4, "fantasy_decoration"),
			FANTASY_DECORATION_BLOCK = new BlockVariant(5, "fantasy_decoration_block"),
			FANTASY_DECORATION_PILLAR = new BlockVariant(6, "fantasy_decoration_pillar"),
			FANTASY_PILLAR = new BlockVariant(7, "fantasy_pillar"),
			FANTASY_DECORATION_SNAKE = new BlockVariant(8, "fantasy_decoration_snake"),
			FANTASY_DECORATION_NOISE = new BlockVariant(9, "fantasy_decoration_noise"),
			FANTASY_DECORATION_ENGRAVING = new BlockVariant(10, "fantasy_decoration_engraving"),
			FANTASY_DECORATION_CHAINS = new BlockVariant(11, "fantasy_decoration_chains"),
			FANTASY_DECORATION_PLATE = new BlockVariant(12, "fantasy_decoration_plate"),
			FANTASY_BLOCK = new BlockVariant(13, "fantasy_block"),
			FANTASY_BRICKS_DISARRAY = new BlockVariant(14, "fantasy_bricks_disarray"),
			FANTASY_BRICKS_DISARRAY_WORN = new BlockVariant(15, "fantasy_bricks_disarray_worn"),

			FUTURA_SCREEN_GRAY = new BlockVariant(0, "futura_screen_gray"),
			FUTURA_SCREEN_CYAN = new BlockVariant(1, "futura_screen_cyan"),
			FUTURA_CONTROLLER = new BlockVariant(2, "futura_controller"),
			FUTURA_CONTROLLER_PURPLE = new BlockVariant(3, "futura_controller_purple"),
			FUTURA_RAINBOW = new BlockVariant(4, "futura_rainbow"),

			GLASS_BUBBLE = new BlockVariant(0, "glass_bubble"),
			GLASS_CHINESE = new BlockVariant(1, "glass_chinese"),
			GLASS_JAPANESE = new BlockVariant(2, "glass_japanese"),
			GLASS_DUNGEON = new BlockVariant(3, "glass_dungeon"),
			GLASS_LIGHT = new BlockVariant(4, "glass_light"),
			GLASS_BORDERLESS = new BlockVariant(5, "glass_borderless"),
			GLASS_ORNATE = new BlockVariant(6, "glass_ornate"),
			GLASS_SCREEN = new BlockVariant(7, "glass_screen"),
			GLASS_SHALE = new BlockVariant(8, "glass_shale"),
			GLASS_STEEL = new BlockVariant(9, "glass_steel"),
			GLASS_STONE = new BlockVariant(10, "glass_stone"),
			GLASS_GRID_THICK = new BlockVariant(11, "glass_grid_thick"),
			GLASS_GRID_THIN = new BlockVariant(12, "glass_grid_thin"),
			GLASS_FENCE = new BlockVariant(13, "glass_fence"),
			GLASS_LEADED = new BlockVariant(14, "glass_leaded"),

			GLASS_PANE_BUBBLE = new BlockVariant(0, "glass_pane_bubble"),
			GLASS_PANE_CHINESE = new BlockVariant(1, "glass_pane_chinese"),
			GLASS_PANE_JAPANESE = new BlockVariant(2, "glass_pane_japanese"),
			GLASS_PANE_DUNGEON = new BlockVariant(3, "glass_pane_dungeon"),
			GLASS_PANE_LIGHT = new BlockVariant(4, "glass_pane_light"),
			GLASS_PANE_BORDERLESS = new BlockVariant(5, "glass_pane_borderless"),
			GLASS_PANE_ORNATE = new BlockVariant(6, "glass_pane_ornate"),
			GLASS_PANE_SCREEN = new BlockVariant(7, "glass_pane_screen"),
			GLASS_PANE_SHALE = new BlockVariant(8, "glass_pane_shale"),
			GLASS_PANE_STEEL = new BlockVariant(9, "glass_pane_steel"),
			GLASS_PANE_STONE = new BlockVariant(10, "glass__panestone"),
			GLASS_PANE_GRID_THICK = new BlockVariant(11, "glass_pane_grid_thick"),
			GLASS_PANE_GRID_THIN = new BlockVariant(12, "glass_pane_grid_thin"),
			GLASS_PANE_FENCE = new BlockVariant(13, "glass_pane_fence"),
			GLASS_PANE_LEADED = new BlockVariant(14, "glass_pane_leaded"),

			GLOWSTONE_COBBLE = new BlockVariant(0, "glowstone_cobble"),
			GLOWSTONE_CORRODED = new BlockVariant(1, "glowstone_corroded"),
			GLOWSTONE_BLOCKS = new BlockVariant(2, "glowstone_blocks"),
			GLOWSTONE_NEON = new BlockVariant(3, "glowstone_neon"),
			GLOWSTONE_ORNATE = new BlockVariant(4, "glowstone_ornate"),
			GLOWSTONE_ROCKY = new BlockVariant(5, "glowstone_rocky"),
			GLOWSTONE_SHALE = new BlockVariant(6, "glowstone_shale"),
			GLOWSTONE_TILES = new BlockVariant(7, "glowstone_tiles"),
			GLOWSTONE_FANCY = new BlockVariant(8, "glowstone_fancy"),
			GLOWSTONE_CRUMBLING = new BlockVariant(9, "glowstone_crumbling"),
			GLOWSTONE_ORGANIC = new BlockVariant(10, "glowstone_organic"),
			GLOWSTONE_LAYERS = new BlockVariant(11, "glowstone_layers"),
			GLOWSTONE_CORRODED_TILES = new BlockVariant(12, "glowstone_corroded_tiles"),
			GLOWSTONE_BISMUTH = new BlockVariant(13, "glowstone_bismuth"),
			GLOWSTONE_BISMUTH_PANEL = new BlockVariant(14, "glowstone_bismuth_panel"),

			GOLD_INGOTS_LARGE = new BlockVariant(0, "gold_ingots_large"),
			GOLD_INGOTS_SMALL = new BlockVariant(1, "gold_ingots_small"),
			GOLD_BRICKS = new BlockVariant(2, "gold_bricks"),
			GOLD_CART = new BlockVariant(3, "gold_cart"),
			GOLD_COIN_HEADS = new BlockVariant(4, "gold_coin_heads"),
			GOLD_COIN_TAILS = new BlockVariant(5, "gold_coin_tails"),
			GOLD_CRATE_DARK = new BlockVariant(6, "gold_crate_dark"),
			GOLD_CRATE_LIGHT = new BlockVariant(7, "gold_crate_light"),
			GOLD_PLATES = new BlockVariant(8, "gold_plates"),
			GOLD_RIVETS = new BlockVariant(9, "gold_rivets"),
			GOLD_STAR_DECOR = new BlockVariant(10, "gold_star_decor"),
			GOLD_STAR_OBSIDIAN_PURPLE = new BlockVariant(11, "gold_star_obsidian_purple"),
			GOLD_STAR_OBSIDIAN = new BlockVariant(12, "gold_star_obsidian"),
			GOLD_SIMPLE = new BlockVariant(13, "gold_simple"),
			GOLD_CAUTION = new BlockVariant(14, "gold_caution"),
			GOLD_SHIPPING = new BlockVariant(15, "gold_shipping"),
			GOLD_THERMAL = new BlockVariant(16, "gold_thermal"),
			GOLD_125 = new BlockVariant(17, "gold_125"),
			GOLD_BORDERED = new BlockVariant(18, "gold_bordered"),
			GOLD_BOLTED = new BlockVariant(19, "gold_bolted"),

			GRANITE_POLISHED = new BlockVariant(0, "granite_polished"),
			GRANITE_PILLAR = new BlockVariant(1, "granite_pillar"),
			GRANITE_BRICKS = new BlockVariant(2, "granite_bricks"),
			GRANITE_ORNATE = new BlockVariant(3, "granite_ornate"),
			GRANITE_PRISMATIC = new BlockVariant(4, "granite_prismatic"),
			GRANITE_TILES_SMALL = new BlockVariant(5, "granite_tiles_small"),

			GRIMSTONE_RAW = new BlockVariant(0, "grimstone_raw"),
			GRIMSTONE_SMOOTH = new BlockVariant(1, "grimstone_smooth"),
			GRIMSTONE_SYMBOL = new BlockVariant(2, "grimstone_symbol"),
			GRIMSTONE_CHISELED = new BlockVariant(3, "grimstone_chiseled"),
			GRIMSTONE_BLOCKS = new BlockVariant(4, "grimstone_blocks"),
			GRIMSTONE_BLOCKS_ROUGH = new BlockVariant(5, "grimstone_blocks_rough"),
			GRIMSTONE_BRICKS = new BlockVariant(6, "grimstone_bricks"),
			GRIMSTONE_BRICKS_LARGE = new BlockVariant(7, "grimstone_bricks_large"),
			GRIMSTONE_PLATFORM = new BlockVariant(8, "grimstone_platform"),
			GRIMSTONE_PLATFORM_TILES = new BlockVariant(9, "grimstone_platform_tiles"),
			GRIMSTONE_CONSTRUCTION = new BlockVariant(10, "grimstone_construction"),
			GRIMSTONE_TILES = new BlockVariant(11, "grimstone_tiles"),
			GRIMSTONE_PLATE_SMOOTH = new BlockVariant(12, "grimstone_plate_smooth"),
			GRIMSTONE_PLATE = new BlockVariant(13, "grimstone_plate"),
			GRIMSTONE_FLAKY = new BlockVariant(14, "grimstone_flaky"),

			HEX_PLATING_0 = new BlockVariant(0, "hex_plating_0"),
			HEX_PLATING_1 = new BlockVariant(1, "hex_plating_1"),
			HEX_PLATING_2 = new BlockVariant(2, "hex_plating_2"),
			HEX_PLATING_3 = new BlockVariant(3, "hex_plating_3"),
			HEX_PLATING_4 = new BlockVariant(4, "hex_plating_4"),
			HEX_PLATING_5 = new BlockVariant(5, "hex_plating_5"),
			HEX_PLATING_6 = new BlockVariant(6, "hex_plating_6"),
			HEX_PLATING_7 = new BlockVariant(7, "hex_plating_7"),
			HEX_PLATING_8 = new BlockVariant(8, "hex_plating_8"),
			HEX_PLATING_9 = new BlockVariant(9, "hex_plating_9"),
			HEX_PLATING_10 = new BlockVariant(10, "hex_plating_10"),
			HEX_PLATING_11 = new BlockVariant(11, "hex_plating_11"),
			HEX_PLATING_12 = new BlockVariant(12, "hex_plating_12"),
			HEX_PLATING_13 = new BlockVariant(13, "hex_plating_13"),
			HEX_PLATING_14 = new BlockVariant(14, "hex_plating_14"),
			HEX_PLATING_15 = new BlockVariant(15, "hex_plating_15"),

			HOLYSTONE_RAW = new BlockVariant(0, "holystone_raw"),
			HOLYSTONE_SMOOTH = new BlockVariant(1, "holystone_smooth"),
			HOLYSTONE_SYMBOL = new BlockVariant(2, "holystone_symbol"),
			HOLYSTONE_CHISELED = new BlockVariant(3, "holystone_chiseled"),
			HOLYSTONE_BLOCKS = new BlockVariant(4, "holystone_blocks"),
			HOLYSTONE_BLOCKS_ROUGH = new BlockVariant(5, "holystonee_blocks_rough"),
			HOLYSTONE_BRICKS = new BlockVariant(6, "holystone_bricks"),
			HOLYSTONE_BRICKS_LARGE = new BlockVariant(7, "holystone_bricks_large"),
			HOLYSTONE_PLATFORM = new BlockVariant(8, "grimstone_platform"),
			HOLYSTONE_PLATFORM_TILES = new BlockVariant(9, "grimstone_platform_tiles"),
			HOLYSTONE_CONSTRUCTION = new BlockVariant(10, "grimstone_construction"),
			HOLYSTONE_TILES = new BlockVariant(11, "grimstone_tiles"),
			HOLYSTONE_PLATE_SMOOTH = new BlockVariant(12, "grimstone_plate_smooth"),
			HOLYSTONE_PLATE = new BlockVariant(13, "grimstone_plate"),

			ICE_ROUGH = new BlockVariant(0, "ice_rough"),
			ICE_COBBLE = new BlockVariant(1, "ice_cobble"),
			ICE_ROUGH_LARGE = new BlockVariant(2, "ice_rough_large"),
			ICE_BRICKS_LARGE = new BlockVariant(3, "ice_bricks_large"),
			ICE_BRICKS_SMALL = new BlockVariant(4, "ice_bricks_small"),
			ICE_GLASS_WALL = new BlockVariant(5, "ice_glass_wall"),
			ICE_TILES_LARGE = new BlockVariant(6, "ice_tiles_large"),
			ICE_TILES_FANCY = new BlockVariant(7, "ice_tiles_fancy"),
			ICE_TILES_SUNKEN = new BlockVariant(8, "ice_tiles_sunken"),
			ICE_TILES_DISORDERED = new BlockVariant(9, "ice_tiles_disordered"),
			ICE_PANEL = new BlockVariant(10, "ice_panel"),
			ICE_DOUBLE_SLAB = new BlockVariant(11, "ice_double_slab"),
			ICE_ZELDA = new BlockVariant(12, "ice_zelda"),
			ICE_BISMUTH = new BlockVariant(13, "ice_bismuth"),
			ICE_POISON = new BlockVariant(14, "ice_poison"),

			ICE_PILLAR_PLAIN_PLAIN = new BlockVariant(0, "ice_pillar_plain_plain"),
			ICE_PILLAR_PLAIN_GREEK = new BlockVariant(1, "ice_pillar_plain_greek"),
			ICE_PILLAR_GREEK_PLAIN = new BlockVariant(2, "ice_pillar_greek_plain"),
			ICE_PILLAR_GREEK_GREEK = new BlockVariant(3, "ice_pillar_greek_greek"),
			ICE_PILLAR_CARVED = new BlockVariant(4, "ice_pillar_carved"),
			ICE_PILLAR_ORNAMENTAL = new BlockVariant(5, "ice_pillar_ornamental"),
			ICE_PILLAR_INSCRIBED = new BlockVariant(6, "ice_pillar_inscribed"),

			IMPERIAL_CAMO = new BlockVariant(0, "imperial_camo"),
			IMPERIAL_CAMO_SECLUDED = new BlockVariant(1, "imperial_camo_secluded"),
			IMPERIAL_BOLT = new BlockVariant(2, "imperial_bolt"),
			IMPERIAL_CAUTION_WHITE = new BlockVariant(3, "imperial_caution_white"),
			IMPERIAL_CAUTION_TEAM = new BlockVariant(4, "imperial_caution_team"),

			INDUSTRIAL_FAN = new BlockVariant(0, "industrial_fan"),
			INDUSTRIAL_PLATING = new BlockVariant(1, "industrial_plating"),

			IRON_INGOTS_LARGE = new BlockVariant(0, "iron_ingots_large"),
			IRON_INGOTS_SMALL = new BlockVariant(1, "iron_ingots_small"),
			IRON_GEARS = new BlockVariant(2, "iron_gears"),
			IRON_BRICKS = new BlockVariant(3, "iron_bricks"),
			IRON_PLATES = new BlockVariant(4, "iron_plates"),
			IRON_COIN_HEADS = new BlockVariant(5, "iron_coin_heads"),
			IRON_COIN_TAILS = new BlockVariant(6, "iron_coin_tails"),
			IRON_CRATE_DARK = new BlockVariant(7, "iron_crate_dark"),
			IRON_CRATE_LIGHT = new BlockVariant(8, "iron_crate_light"),
			IRON_MOON_DECOR = new BlockVariant(9, "iron_moon_decor"),
			IRON_MOON_OBSIDIAN_PURPLE = new BlockVariant(10, "iron_moon_obsidian_purple"),
			IRON_MOON_OBSIDIAN = new BlockVariant(11, "iron_moon_obsidian"),
			IRON_VENTS = new BlockVariant(12, "iron_vents"),
			IRON_SIMPLE = new BlockVariant(13, "iron_simple"),
			IRON_CAUTION = new BlockVariant(14, "iron_caution"),
			IRON_SHIPPING = new BlockVariant(15, "iron_shipping"),
			IRON_THERMAL = new BlockVariant(16, "iron_thermal"),
			IRON_125 = new BlockVariant(17, "iron_125"),
			IRON_BORDERED = new BlockVariant(18, "iron_bordered"),
			IRON_BOLTED = new BlockVariant(19, "iron_bolted"),

			IRON_BARS_NO_FRAME = new BlockVariant(0, "iron_bars_no_frame"),
			IRON_BARS_MENACING = new BlockVariant(1, "iron_bars_menacing"),
			IRON_BARS_CAGE = new BlockVariant(2, "iron_bars_cage"),
			IRON_BARS_MENACING_SPIKES = new BlockVariant(3, "iron_bars_menacing_spikes"),
			IRON_BARS_GRID_THICK = new BlockVariant(4, "iron_bars_grid_thick"),
			IRON_BARS_GRID_THIN = new BlockVariant(5, "iron_bars_grid_thin"),
			IRON_BARS_ORNATE = new BlockVariant(6, "iron_bars_ornate"),
			IRON_BARS_VERTICAL = new BlockVariant(7, "iron_bars_vertical"),
			IRON_BARS_SPIKES = new BlockVariant(8, "iron_bars_spikes"),

			JUNGLE_PLANKS_SMOOTH = new BlockVariant(0, "jungle_planks_smooth"),
			JUNGLE_PLANKS_SHORT = new BlockVariant(1, "jungle_planks_short"),
			JUNGLE_PLANKS_FANCY = new BlockVariant(2, "jungle_planks_fancy"),
			JUNGLE_PLANKS_PANEL = new BlockVariant(3, "jungle_planks_panel"),
			JUNGLE_PLANKS_DOUBLE_SLAB = new BlockVariant(4, "jungle_planks_double_slab"),
			JUNGLE_PLANKS_CRATE = new BlockVariant(5, "jungle_planks_crate"),
			JUNGLE_PLANKS_CRATE_FANCY = new BlockVariant(6, "jungle_planks_crate_fancy"),
			JUNGLE_PLANKS_LONG = new BlockVariant(7, "jungle_planks_long"),
			JUNGLE_PLANKS_VERTICAL = new BlockVariant(8, "jungle_planks_vertical"),
			JUNGLE_PLANKS_VERTICAL_UNEVEN = new BlockVariant(9, "jungle_planks_vertical_uneven"),
			JUNGLE_PLANKS_PARQUET = new BlockVariant(10, "jungle_planks_parquet"),
			JUNGLE_PLANKS_BLINDS = new BlockVariant(11, "jungle_planks_blinds"),
			JUNGLE_PLANKS_SCAFFOLD = new BlockVariant(12, "jungle_planks_scaffold"),
			JUNGLE_PLANKS_DISARRAY = new BlockVariant(13, "jungle_planks_disarray"),
			JUNGLE_PLANKS_DISARRAY_VERTICAL = new BlockVariant(14, "jungle_planks_disarray_vertical"),

			LABORATORY_PANEL_WALL = new BlockVariant(0, "laboratory_panel_wall"),
			LABORATORY_PANEL_DOTTED = new BlockVariant(1, "laboratory_panel_dotted"),
			LABORATORY_WALL = new BlockVariant(2, "laboratory_wall"),
			LABORATORY_WALL_ROUNDED = new BlockVariant(3, "laboratory_wall_rounded"),
			LABORATORY_WALL_VENT = new BlockVariant(4, "laboratory_wall_vent"),
			LABORATORY_TILES_ENAMELLED_LARGE = new BlockVariant(5, "laboratory_tiles_enamelled_large"),
			LABORATORY_TILES_ENAMELLED_SMALL = new BlockVariant(6, "laboratory_tiles_enamelled_small"),
			LABORATORY_FLOOR = new BlockVariant(7, "laboratory_floor"),
			LABORATORY_CHECKERBOARD = new BlockVariant(8, "laboratory_checkerboard"),
			LABORATORY_PANEL_CLEAR = new BlockVariant(9, "laboratory_panel_clear"),
			LABORATORY_PANEL_FUZZY = new BlockVariant(10, "laboratory_panel_fuzzy"),
			LABORATORY_TILES_STEEL_LARGE = new BlockVariant(11, "laboratory_tiles_steel_large"),
			LABORATORY_TILES_STEEL_SMALL = new BlockVariant(12, "laboratory_tiles_steel_small"),
			LABORATORY_CONSOLE_RIGHT = new BlockVariant(13, "laboratory_console_right"),
			LABORATORY_CONSOLE_LEFT = new BlockVariant(14, "laboratory_console_left"),
			LABORATORY_CONSOLE_INFORMATION = new BlockVariant(15, "laboratory_console_information"),

			LAPIS_CHUNKY = new BlockVariant(0, "lapis_chunky"),
			LAPIS_DARK = new BlockVariant(1, "lapis_dark"),
			LAPIS_ZELDA = new BlockVariant(2, "lapis_zelda"),
			LAPIS_ORNATE = new BlockVariant(3, "lapis_ornate"),
			LAPIS_TILE = new BlockVariant(4, "lapis_tile"),
			LAPIS_PANEL = new BlockVariant(5, "lapis_panel"),
			LAPIS_SMOOTH = new BlockVariant(6, "lapis_smooth"),
			LAPIS_ORNATE_LAYER = new BlockVariant(7, "lapis_ornate_layer"),

			LARGE_HEX_PLATING_0 = new BlockVariant(0, "large_hex_plating_0"),
			LARGE_HEX_PLATING_1 = new BlockVariant(1, "large_hex_plating_1"),
			LARGE_HEX_PLATING_2 = new BlockVariant(2, "large_hex_plating_2"),
			LARGE_HEX_PLATING_3 = new BlockVariant(3, "large_hex_plating_3"),
			LARGE_HEX_PLATING_4 = new BlockVariant(4, "large_hex_plating_4"),
			LARGE_HEX_PLATING_5 = new BlockVariant(5, "large_hex_plating_5"),
			LARGE_HEX_PLATING_6 = new BlockVariant(6, "large_hex_plating_6"),
			LARGE_HEX_PLATING_7 = new BlockVariant(7, "large_hex_plating_7"),
			LARGE_HEX_PLATING_8 = new BlockVariant(8, "large_hex_plating_8"),
			LARGE_HEX_PLATING_9 = new BlockVariant(9, "large_hex_plating_9"),
			LARGE_HEX_PLATING_10 = new BlockVariant(10, "large_hex_plating_10"),
			LARGE_HEX_PLATING_11 = new BlockVariant(11, "large_hex_plating_11"),
			LARGE_HEX_PLATING_12 = new BlockVariant(12, "large_hex_plating_12"),
			LARGE_HEX_PLATING_13 = new BlockVariant(13, "large_hex_plating_13"),
			LARGE_HEX_PLATING_14 = new BlockVariant(14, "large_hex_plating_14"),
			LARGE_HEX_PLATING_15 = new BlockVariant(15, "large_hex_plating_15"),

			LAVASTONE_RAW = new BlockVariant(0, "lavastone_raw"),
			LAVASTONE_BLACK = new BlockVariant(1, "lavastone_black"),
			LAVASTONE_TILES = new BlockVariant(2, "lavastone_tiles"),
			LAVASTONE_BRICKS = new BlockVariant(3, "lavastone_bricks"),
			LAVASTONE_TILES_CREEPER = new BlockVariant(4, "lavastone_tiles_creeper"),
			LAVASTONE_PANEL = new BlockVariant(5, "lavastone_panel"),
			LAVASTONE_PANEL_ORNATE = new BlockVariant(6, "lavastone_panel_ornate"),
			LAVASTONE_DARK = new BlockVariant(7, "lavastone_dark"),

			LEAD_CAUTION = new BlockVariant(0, "lead_caution"),
			LEAD_SHIPPING = new BlockVariant(1, "lead_shipping"),
			LEAD_THERMAL = new BlockVariant(2, "lead_thermal"),
			LEAD_125 = new BlockVariant(3, "lead_125"),
			LEAD_BORDERED = new BlockVariant(4, "lead_bordered"),
			LEAD_BOLTED = new BlockVariant(5, "lead_bolted"),

			LEAVES_DEAD = new BlockVariant(0, "leaves_dead"),
			LEAVES_FANCY = new BlockVariant(1, "leaves_fancy"),
			LEAVES_PINK = new BlockVariant(2, "leaves_pink"),
			LEAVES_RED = new BlockVariant(3, "leaves_red"),
			LEAVES_WHITE = new BlockVariant(4, "leaves_white"),
			LEAVES_CHRISTMAS_BALLS = new BlockVariant(5, "leaves_christmas_balls"),
			LEAVES_CHRISTMAS_LIGHTS = new BlockVariant(6, "leaves_christmas_lights"),

			LIMESTONE_RAW = new BlockVariant(0, "limestone_raw"),
			LIMESTONE_TILES = new BlockVariant(1, "limestone_tiles"),
			LIMESTONE_TILES_FRENCH = new BlockVariant(2, "limestone_tiles_french"),
			LIMESTONE_TILES_FRENCH_LIGHT = new BlockVariant(2, "limestone_tiles_french_light"),
			LIMESTONE_TILES_CREEPER = new BlockVariant(3, "limestone_tiles_creeper"),
			LIMESTONE_TILES_DAMAGED = new BlockVariant(4, "limestone_tiles_damaged"),
			LIMESTONE_TILES_LARGE = new BlockVariant(5, "limestone_tiles_large"),
			LIMESTONE_BRICKS = new BlockVariant(6, "limestone_bricks"),
			LIMESTONE_SMOOTH = new BlockVariant(7, "limestone_smooth"),
			LIMESTONE_PANEL_ORNATE = new BlockVariant(8, "limestone_panel_ornate"),
			LIMESTONE_PANEL_ENGRAVED = new BlockVariant(9, "limestone_panel_engraved"),
			LIMESTONE_PANEL_CREEPER = new BlockVariant(10, "limestone_panel_creeper"),
			LIMESTONE_PANEL_LIGHT = new BlockVariant(11, "limestone_panel_light"),
			LIMESTONE_PANEL_DARK = new BlockVariant(12, "limestone_panel_dark"),
			LIMESTONE_PANEL = new BlockVariant(13, "limestone_panel"),
			LIMESTONE_DENT = new BlockVariant(14, "limestone_dent"),

			LITPUMPKIN_0 = new BlockVariant(0, "litpumpkin_0"),
			LITPUMPKIN_1 = new BlockVariant(1, "litpumpkin_1"),
			LITPUMPKIN_2 = new BlockVariant(2, "litpumpkin_2"),
			LITPUMPKIN_3 = new BlockVariant(3, "litpumpkin_3"),
			LITPUMPKIN_4 = new BlockVariant(4, "litpumpkin_4"),
			LITPUMPKIN_5 = new BlockVariant(5, "litpumpkin_5"),
			LITPUMPKIN_6 = new BlockVariant(6, "litpumpkin_6"),
			LITPUMPKIN_7 = new BlockVariant(7, "litpumpkin_7"),
			LITPUMPKIN_8 = new BlockVariant(8, "litpumpkin_8"),
			LITPUMPKIN_9 = new BlockVariant(9, "litpumpkin_9"),
			LITPUMPKIN_10 = new BlockVariant(10, "litpumpkin_10"),
			LITPUMPKIN_11 = new BlockVariant(11, "litpumpkin_11"),
			LITPUMPKIN_12 = new BlockVariant(12, "litpumpkin_12"),
			LITPUMPKIN_13 = new BlockVariant(13, "litpumpkin_13"),
			LITPUMPKIN_14 = new BlockVariant(14, "litpumpkin_14"),
			LITPUMPKIN_15 = new BlockVariant(15, "litpumpkin_15"),
			LITPUMPKIN_16 = new BlockVariant(16, "litpumpkin_16"),

			MARBLE_RAW = new BlockVariant(0, "marble_raw"),
			MARBLE_BRICK = new BlockVariant(1, "marble_brick"),
			MARBLE_PANEL_CLASSIC = new BlockVariant(2, "marble_panel_classic"),
			MARBLE_PANEL_ORNATE = new BlockVariant(3, "marble_panel_ornate"),
			MARBLE_PANEL = new BlockVariant(4, "marble_panel"),
			MARBLE_BLOCK = new BlockVariant(5, "marble_block"),
			MARBLE_CREEPER_DARK = new BlockVariant(6, "marble_creeper_dark"),
			MARBLE_CREEPER_LIGHT = new BlockVariant(7, "marble_creeper_light"),
			MARBLE_CARVED = new BlockVariant(8, "marble_carved"),
			MARBLE_CARVED_RADIAL = new BlockVariant(9, "marble_carved_radial"),
			MARBLE_DENT = new BlockVariant(10, "marble_dent"),
			MARBLE_DENT_LARGE = new BlockVariant(11, "marble_dent_large"),
			MARBLE_TILES = new BlockVariant(12, "marble_tiles"),
			MARBLE_TILES_ARRANGED = new BlockVariant(13, "marble_tiles_arranged"),
			MARBLE_TILES_FANCY = new BlockVariant(14, "marble_tiles_fancy"),
			MARBLE_BLOCKS = new BlockVariant(15, "marble_blocks"),

			MOSSY_COBBLESTONE_BRICKS_ALIGNED = new BlockVariant(0, "mossy_cobblestone_bricks_aligned"),
			MOSSY_COBBLESTONE_BRICKS_DETAILED = new BlockVariant(1, "mossy_cobblestone_bricks_detailed"),
			MOSSY_COBBLESTONE_BRICKS_SMALL = new BlockVariant(2, "mossy_cobblestone_bricks_small"),
			MOSSY_COBBLESTONE_TILES_LARGE = new BlockVariant(3, "mossy_cobblestone_tiles_large"),
			MOSSY_COBBLESTONE_TILES_SMALL = new BlockVariant(4, "mossy_cobblestone_tiles_small"),
			MOSSY_COBBLESTONE_TILES_FRENCH = new BlockVariant(5, "mossy_cobblestone_tiles_french"),
			MOSSY_COBBLESTONE_TILES_FRENCH_LIGHT = new BlockVariant(6, "mossy_cobblestone_tiles_french_light"),
			MOSSY_COBBLESTONE_TILES_CREEPER = new BlockVariant(7, "mossy_cobblestone_tiles_creeper"),
			MOSSY_COBBLESTONE_TILES_DAMAGED = new BlockVariant(8, "mossy_cobblestone_tiles_damaged"),
			MOSSY_COBBLESTONE_TILES_HUGE = new BlockVariant(9, "mossy_cobblestone_tiles_huge"),
			MOSSY_COBBLESTONE_PANEL_CREEPER = new BlockVariant(10, "mossy_cobblestone_panel_creeper"),
			MOSSY_COBBLESTONE_DENT = new BlockVariant(11, "mossy_cobblestone_dent"),
			MOSSY_COBBLESTONE_PANEL = new BlockVariant(12, "mossy_cobblestone_panel"),
			MOSSY_COBBLESTONE_PANEL_LIGHT = new BlockVariant(13, "mossy_cobblestone_panel_light"),
			MOSSY_COBBLESTONE_PANEL_DARK = new BlockVariant(14, "mossy_cobblestone_panel_dark"),

			MOSSY_TEMPLE_COBBLE = new BlockVariant(0, "mossy_temple_cobble"),
			MOSSY_TEMPLE_ORNATE = new BlockVariant(1, "mossy_temple_ornate"),
			MOSSY_TEMPLE_PLATE = new BlockVariant(2, "mossy_temple_plate"),
			MOSSY_TEMPLE_PLATE_CRACKED = new BlockVariant(3, "mossy_temple_plate_cracked"),
			MOSSY_TEMPLE_BRICKS = new BlockVariant(4, "mossy_temple_bricks"),
			MOSSY_TEMPLE_BRICKS_LARGE = new BlockVariant(5, "mossy_temple_bricks_large"),
			MOSSY_TEMPLE_BRICKS_WORN = new BlockVariant(6, "mossy_temple_bricks_worn"),
			MOSSY_TEMPLE_BRICKS_DISARRAY = new BlockVariant(7, "mossy_temple_bricks_disarray"),
			MOSSY_TEMPLE_COLUMN = new BlockVariant(8, "mossy_temple_column"),
			MOSSY_TEMPLE_STAND = new BlockVariant(9, "mossy_temple_stand"),
			MOSSY_TEMPLE_STAND_MOSAIC = new BlockVariant(10, "mossy_temple_stand_mosaic"),
			MOSSY_TEMPLE_STAND_CREEPER = new BlockVariant(11, "mossy_temple_stand_creeper"),
			MOSSY_TEMPLE_TILES = new BlockVariant(12, "mossy_temple_tiles"),
			MOSSY_TEMPLE_TILES_SMALL = new BlockVariant(13, "mossy_temple_tiles_small"),
			MOSSY_TEMPLE_TILES_LIGHT = new BlockVariant(14, "mossy_temple_tiles_light"),
			MOSSY_TEMPLE_TILES_SMALL_LIGHT = new BlockVariant(15, "mossy_temple_tiles_small_light"),

			NETHER_BRICK_BLUE = new BlockVariant(0, "nether_brick_blue"),
			NETHER_BRICK_SPATTERED = new BlockVariant(1, "nether_brick_spattered"),
			NETHER_BRICK_GUTS = new BlockVariant(2, "nether_brick_guts"),
			NETHER_BRICK_GUTS_DARK = new BlockVariant(3, "nether_brick_guts_dark"),
			NETHER_BRICK_GUTS_SMALL = new BlockVariant(4, "nether_brick_guts_small"),
			NETHER_BRICK_BLUE_LAVA = new BlockVariant(5, "nether_brick_blue_lava"),
			NETHER_BRICK_BROWN = new BlockVariant(6, "nether_brick_brown"),
			NETHER_BRICK_OBSIDIAN = new BlockVariant(7, "nether_brick_obsidian"),
			NETHER_BRICK_STONE = new BlockVariant(8, "nether_brick_stone"),
			NETHER_BRICK_MEAT = new BlockVariant(9, "nether_brick_meat"),
			NETHER_BRICK_MEAT_RED = new BlockVariant(10, "nether_brick_meat_red"),
			NETHER_BRICK_MEAT_SMALL = new BlockVariant(11, "nether_brick_meat_small"),
			NETHER_BRICK_MEAT_SMALL_RED = new BlockVariant(12, "nether_brick_meat_small_red"),
			NETHER_BRICK_RED = new BlockVariant(13, "nether_brick_red"),
			NETHER_BRICK_RED_SMALL = new BlockVariant(14, "nether_brick_red_small"),

			NETHERRACK_BLOOD_GRAVEL = new BlockVariant(0, "netherrack_blood_gravel"),
			NETHERRACK_BLOOD = new BlockVariant(1, "netherrack_blood_"),
			NETHERRACK_BLOOD_DARK = new BlockVariant(2, "netherrack_blood_dark"),
			NETHERRACK_BLUE = new BlockVariant(3, "netherrack_blue"),
			NETHERRACK_BLUE_SHALE = new BlockVariant(4, "netherrack_blue_shale"),
			NETHERRACK_CLASSIC = new BlockVariant(5, "netherrack_classic"),
			NETHERRACK_SPATTERED = new BlockVariant(6, "netherrack_splattered"),
			NETHERRACK_GUTS = new BlockVariant(7, "netherrack_guts"),
			NETHERRACK_GUTS_DARK = new BlockVariant(8, "netherrack_guts_dark"),
			NETHERRACK_MEAT = new BlockVariant(9, "netherrack_meat"),
			NETHERRACK_MEAT_RED = new BlockVariant(10, "netherrack_meat_red"),
			NETHERRACK_MEAT_SMALL = new BlockVariant(11, "netherrack_meat_small"),
			NETHERRACK_RED = new BlockVariant(12, "netherrack_red"),
			NETHERRACK_LAVA = new BlockVariant(13, "netherrack_lava"),

			OAK_PLANKS_SMOOTH = new BlockVariant(0, "oak_planks_smooth"),
			OAK_PLANKS_SHORT = new BlockVariant(1, "oak_planks_short"),
			OAK_PLANKS_FANCY = new BlockVariant(2, "oak_planks_fancy"),
			OAK_PLANKS_PANEL = new BlockVariant(3, "oak_planks_panel"),
			OAK_PLANKS_DOUBLE_SLAB = new BlockVariant(4, "oak_planks_double_slab"),
			OAK_PLANKS_CRATE = new BlockVariant(5, "oak_planks_crate"),
			OAK_PLANKS_CRATE_FANCY = new BlockVariant(6, "oak_planks_crate_fancy"),
			OAK_PLANKS_LONG = new BlockVariant(7, "oak_planks_long"),
			OAK_PLANKS_VERTICAL = new BlockVariant(8, "oak_planks_vertical"),
			OAK_PLANKS_VERTICAL_UNEVEN = new BlockVariant(9, "oak_planks_vertical_uneven"),
			OAK_PLANKS_PARQUET = new BlockVariant(10, "oak_planks_parquet"),
			OAK_PLANKS_BLINDS = new BlockVariant(11, "oak_planks_blinds"),
			OAK_PLANKS_SCAFFOLD = new BlockVariant(12, "oak_planks_scaffold"),
			OAK_PLANKS_DISARRAY = new BlockVariant(13, "oak_planks_disarray"),
			OAK_PLANKS_DISARRAY_VERTICAL = new BlockVariant(14, "oak_planks_disarray_vertical"),

			OBSIDIAN_PILLAR_LARGE = new BlockVariant(0, "obsidian_pillar_large"),
			OBSIDIAN_PILLAR = new BlockVariant(1, "obsidian_pillar"),
			OBSIDIAN_CHISELED = new BlockVariant(2, "obsidian_chiseled"),
			OBSIDIAN_PANEL_SHINY = new BlockVariant(3, "obsidian_panel_bright"),
			OBSIDIAN_PANEL = new BlockVariant(4, "obsidian_panel"),
			OBSIDIAN_ORGANIC_CHUNKS = new BlockVariant(5, "obsidian_organic_chunks"),
			OBSIDIAN_ORGANIC_GROWTH = new BlockVariant(6, "obsidian_organic_growth"),
			OBSIDIAN_CRYSTAL = new BlockVariant(7, "obsidian_crystal"),
			OBSIDIAN_PANEL_MAP = new BlockVariant(8, "obsidian_panel_map"),
			OBSIDIAN_PANEL_REGION = new BlockVariant(9, "obsidian_panel_region"),
			OBSIDIAN_PANEL_BRIGHT = new BlockVariant(10, "obsidian_panel_bright"),
			OBSIDIAN_BLOCKS = new BlockVariant(11, "obsidian_blocks"),
			OBSIDIAN_TILES = new BlockVariant(12, "obsidian_tiles"),
			OBSIDIAN_GREEK = new BlockVariant(13, "obsidian_greek"),
			OBSIDIAN_CRATE = new BlockVariant(14, "obsidian_crate"),

			PACKED_ICE_ROUGH = new BlockVariant(0, "packed_ice_rough"),
			PACKED_ICE_COBBLE = new BlockVariant(1, "packed_ice_cobble"),
			PACKED_ICE_ROUGH_LARGE = new BlockVariant(2, "packed_ice_rough_large"),
			PACKED_ICE_BRICKS_LARGE = new BlockVariant(3, "packed_ice_bricks_large"),
			PACKED_ICE_BRICKS_SMALL = new BlockVariant(4, "packed_ice_bricks_small"),
			PACKED_ICE_GLASS_WALL = new BlockVariant(5, "packed_ice_glass_wall"),
			PACKED_ICE_TILES_LARGE = new BlockVariant(6, "packed_ice_tiles_large"),
			PACKED_ICE_TILES_FANCY = new BlockVariant(7, "packed_ice_tiles_fancy"),
			PACKED_ICE_TILES_SUNKEN = new BlockVariant(8, "packed_ice_tiles_sunken"),
			PACKED_ICE_TILES_DISORDERED = new BlockVariant(9, "packed_ice_tiles_disordered"),
			PACKED_ICE_PANEL = new BlockVariant(10, "packed_ice_panel"),
			PACKED_ICE_DOUBLE_SLAB = new BlockVariant(11, "packed_ice_double_slab"),
			PACKED_ICE_ZELDA = new BlockVariant(12, "packed_ice_zelda"),
			PACKED_ICE_BISMUTH = new BlockVariant(13, "packed_ice_bismuth"),
			PACKED_ICE_POISON = new BlockVariant(14, "packed_ice_poison"),

			PACKED_ICE_PILLAR_PLAIN_PLAIN = new BlockVariant(0, "packed_ice_pillar_plain_plain"),
			PACKED_ICE_PILLAR_PLAIN_GREEK = new BlockVariant(1, "packed_ice_pillar_plain_greek"),
			PACKED_ICE_PILLAR_GREEK_PLAIN = new BlockVariant(2, "packed_ice_pillar_greek_plain"),
			PACKED_ICE_PILLAR_GREEK_GREEK = new BlockVariant(3, "packed_ice_pillar_greek_greek"),
			PACKED_ICE_PILLAR_CARVED = new BlockVariant(4, "packed_ice_pillar_carved"),
			PACKED_ICE_PILLAR_ORNAMENTAL = new BlockVariant(5, "packed_ice_pillar_ornamental"),
			PACKED_ICE_PILLAR_INSCRIBED = new BlockVariant(6, "packed_ice_pillar_inscribed"),

			PAPERWALL_BOXED = new BlockVariant(0, "paperwall_boxed"),
			PAPERWALL_STRIKE_MIDDLE = new BlockVariant(1, "paperwall_strike_middle"),
			PAPERWALL_CROSSED = new BlockVariant(2, "paperwall_crossed"),
			PAPERWALL_SIX = new BlockVariant(3, "paperwall_six"),
			PAPERWALL_STRIKE_VERTICAL = new BlockVariant(4, "paperwall_strike_vertical"),
			PAPERWALL_STRIKE_HORIZONTAL = new BlockVariant(5, "paperwall_strike_horizontal"),
			PAPERWALL_FLORAL = new BlockVariant(6, "paperwall_floral"),
			PAPERWALL_PLAIN = new BlockVariant(7, "paperwall_plain"),
			PAPERWALL_DOOR = new BlockVariant(8, "paperwall_door"),

			PAPERWALL_BLOCK_BOXED = new BlockVariant(0, "paperwall_block_boxed"),
			PAPERWALL_BLOCK_STRIKE_MIDDLE = new BlockVariant(1, "paperwall_block_strike_middle"),
			PAPERWALL_BLOCK_CROSSED = new BlockVariant(2, "paperwall_block_crossed"),
			PAPERWALL_BLOCK_SIX = new BlockVariant(3, "paperwall_block_six"),
			PAPERWALL_BLOCK_STRIKE_VERTICAL = new BlockVariant(4, "paperwall_block_strike_vertical"),
			PAPERWALL_BLOCK_STRIKE_HORIZONTAL = new BlockVariant(5, "paperwall_block_strike_horizontal"),
			PAPERWALL_BLOCK_FLORAL = new BlockVariant(6, "paperwall_block_floral"),
			PAPERWALL_BLOCK_PLAIN = new BlockVariant(7, "paperwall_block_plain"),
			PAPERWALL_BLOCK_DOOR = new BlockVariant(8, "paperwall_block_door"),

			PUMPKIN_0 = new BlockVariant(0, "pumpkin_0"),
			PUMPKIN_1 = new BlockVariant(1, "pumpkin_1"),
			PUMPKIN_2 = new BlockVariant(2, "pumpkin_2"),
			PUMPKIN_3 = new BlockVariant(3, "pumpkin_3"),
			PUMPKIN_4 = new BlockVariant(4, "pumpkin_4"),
			PUMPKIN_5 = new BlockVariant(5, "pumpkin_5"),
			PUMPKIN_6 = new BlockVariant(6, "pumpkin_6"),
			PUMPKIN_7 = new BlockVariant(7, "pumpkin_7"),
			PUMPKIN_8 = new BlockVariant(8, "pumpkin_8"),
			PUMPKIN_9 = new BlockVariant(9, "pumpkin_9"),
			PUMPKIN_10 = new BlockVariant(10, "pumpkin_10"),
			PUMPKIN_11 = new BlockVariant(11, "pumpkin_11"),
			PUMPKIN_12 = new BlockVariant(12, "pumpkin_12"),
			PUMPKIN_13 = new BlockVariant(13, "pumpkin_13"),
			PUMPKIN_14 = new BlockVariant(14, "pumpkin_14"),
			PUMPKIN_15 = new BlockVariant(15, "pumpkin_15"),
			PUMPKIN_16 = new BlockVariant(16, "pumpkin_16"),

			PURPLED_FANTASY_BRICK = new BlockVariant(0, "purpled_fantasy_brick"),
			PURPLED_FANTASY_BRICK_FADED = new BlockVariant(1, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_BRICK_WORN = new BlockVariant(2, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_BRICK_DAMAGED = new BlockVariant(3, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION = new BlockVariant(4, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_BLOCK = new BlockVariant(5, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_PILLAR = new BlockVariant(6, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_PILLAR = new BlockVariant(7, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_SNAKE = new BlockVariant(8, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_NOISE = new BlockVariant(9, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_ENGRAVING = new BlockVariant(10, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_CHAINS = new BlockVariant(11, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_DECORATION_PLATE = new BlockVariant(12, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_BLOCK = new BlockVariant(13, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_BRICKS_DISARRAY = new BlockVariant(14, "purpled_fantasy_brick_faded"),
			PURPLED_FANTASY_BRICKS_DISARRAY_WORN = new BlockVariant(15, "purpled_fantasy_brick_faded"),

			REBEL_CAMO = new BlockVariant(0, "rebel_camo"),
			REBEL_CAMO_SECLUDED = new BlockVariant(1, "rebel_camo_secluded"),
			REBEL_BOLT = new BlockVariant(2, "rebel_bolt"),
			REBEL_CAUTION_WHITE = new BlockVariant(3, "rebel_caution_white"),
			REBEL_CAUTION_TEAM = new BlockVariant(4, "rebel_caution_team"),

			REDSTONE_SMOOTH = new BlockVariant(0, "redstone_smooth"),
			REDSTONE_LARGE = new BlockVariant(1, "redstone_large"),
			REDSTONE_SMALL = new BlockVariant(2, "redstone_small"),
			REDSTONE_BRICKS = new BlockVariant(3, "redstone_bricks"),
			REDSTONE_BRICKS_SMALL = new BlockVariant(4, "redstone_bricks_small"),
			REDSTONE_BRICKS_CHAOTIC = new BlockVariant(5, "redstone_bricks_chaotic"),
			REDSTONE_CHISELED = new BlockVariant(6, "redstone_chiseled"),
			REDSTONE_GREEK = new BlockVariant(7, "redstone_greek"),
			REDSTONE_TILES_ORNATE = new BlockVariant(8, "redstone_tiles_ornate"),
			REDSTONE_PILLAR = new BlockVariant(9, "redstone_pillar"),
			REDSTONE_TILES = new BlockVariant(10, "redstone_tiles"),
			REDSTONE_CIRCUIT = new BlockVariant(11, "redstone_circuit"),
			REDSTONE_CIRCUIT_SUPAPLEX = new BlockVariant(12, "redstone_circuit_supaplex"),
			REDSTONE_SKULLS = new BlockVariant(13, "redstone_skulls"),
			REDSTONE_ZELDA = new BlockVariant(14, "redstone_zelda"),

			ROAD_LINES_WHITE = new BlockVariant(0, "road_lines_white"),
			ROAD_LINES_YELLOW = new BlockVariant(1, "road_lines_yellow"),
			ROAD_LINES_WHITE_DOUBLE = new BlockVariant(2, "road_lines_white_double"),
			ROAD_LINES_YELLOW_DOUBLE = new BlockVariant(3, "road_lines_yellow_double"),

			RUNIC_VOIDSTONE_0 = new BlockVariant(0, "runic_voidstone_0"),
			RUNIC_VOIDSTONE_1 = new BlockVariant(1, "runic_voidstone_1"),
			RUNIC_VOIDSTONE_2 = new BlockVariant(2, "runic_voidstone_2"),
			RUNIC_VOIDSTONE_3 = new BlockVariant(3, "runic_voidstone_3"),
			RUNIC_VOIDSTONE_4 = new BlockVariant(4, "runic_voidstone_4"),
			RUNIC_VOIDSTONE_5 = new BlockVariant(5, "runic_voidstone_5"),
			RUNIC_VOIDSTONE_6 = new BlockVariant(6, "runic_voidstone_6"),
			RUNIC_VOIDSTONE_7 = new BlockVariant(7, "runic_voidstone_7"),
			RUNIC_VOIDSTONE_8 = new BlockVariant(8, "runic_voidstone_8"),
			RUNIC_VOIDSTONE_9 = new BlockVariant(9, "runic_voidstone_9"),
			RUNIC_VOIDSTONE_10 = new BlockVariant(10, "runic_voidstone_10"),
			RUNIC_VOIDSTONE_11 = new BlockVariant(11, "runic_voidstone_11"),
			RUNIC_VOIDSTONE_12 = new BlockVariant(12, "runic_voidstone_12"),
			RUNIC_VOIDSTONE_13 = new BlockVariant(13, "runic_voidstone_13"),
			RUNIC_VOIDSTONE_14 = new BlockVariant(14, "runic_voidstone_14"),
			RUNIC_VOIDSTONE_15 = new BlockVariant(15, "runic_voidstone_15"),

			SANDSTONE_FADED = new BlockVariant(0, "sandstone_faded"),
			SANDSTONE_PILLAR = new BlockVariant(1, "sandstone_pillar"),
			SANDSTONE_PILLAR_CAPSTONE = new BlockVariant(2, "sandstone_pillar_capstone"),
			SANDSTONE_PILLAR_SMALL = new BlockVariant(3, "sandstone_pillar_small"),
			SANDSTONE_PILLAR_BASE = new BlockVariant(4, "sandstone_pillar_base"),
			SANDSTONE_SMOOTH_FLAT = new BlockVariant(5, "sandstone_smooth_flat"),
			SANDSTONE_PILLAR_CAPSTONE_SMOOTH = new BlockVariant(6, "sandstone_pillar_capstone_smooth"),
			SANDSTONE_PILLAR_SMALL_SMOOTH = new BlockVariant(7, "sandstone_pillar_small_smooth"),
			SANDSTONE_PILLAR_SMOOTH = new BlockVariant(8, "sandstone_pillar_smooth"),
			SANDSTONE_BLOCK = new BlockVariant(9, "sandstone_block"),
			SANDSTONE_BLOCKS_SMALL = new BlockVariant(10, "sandstone_blocks_small"),
			SANDSTONE_BLOCKS = new BlockVariant(11, "sandstone_blocks"),
			SANDSTONE_MOSAIC = new BlockVariant(12, "sandstone_mosaic"),
			SANDSTONE_STACKED = new BlockVariant(13, "sandstone_stacked"),

			SANDSTONE_SCRIBBLES_0 = new BlockVariant(0, "sandstone_scribbles_0"),
			SANDSTONE_SCRIBBLES_1 = new BlockVariant(1, "sandstone_scribbles_1"),
			SANDSTONE_SCRIBBLES_2 = new BlockVariant(2, "sandstone_scribbles_2"),
			SANDSTONE_SCRIBBLES_3 = new BlockVariant(3, "sandstone_scribbles_3"),
			SANDSTONE_SCRIBBLES_4 = new BlockVariant(4, "sandstone_scribbles_4"),
			SANDSTONE_SCRIBBLES_5 = new BlockVariant(5, "sandstone_scribbles_5"),
			SANDSTONE_SCRIBBLES_6 = new BlockVariant(6, "sandstone_scribbles_6"),
			SANDSTONE_SCRIBBLES_7 = new BlockVariant(7, "sandstone_scribbles_7"),
			SANDSTONE_SCRIBBLES_8 = new BlockVariant(8, "sandstone_scribbles_8"),
			SANDSTONE_SCRIBBLES_9 = new BlockVariant(9, "sandstone_scribbles_9"),
			SANDSTONE_SCRIBBLES_10 = new BlockVariant(10, "sandstone_scribbles_10"),
			SANDSTONE_SCRIBBLES_11 = new BlockVariant(11, "sandstone_scribbles_11"),
			SANDSTONE_SCRIBBLES_12 = new BlockVariant(12, "sandstone_scribbles_12"),
			SANDSTONE_SCRIBBLES_13 = new BlockVariant(13, "sandstone_scribbles_13"),
			SANDSTONE_SCRIBBLES_14 = new BlockVariant(14, "sandstone_scribbles_14"),

			SILVER_CAUTION = new BlockVariant(0, "silver_caution"),
			SILVER_SHIPPING = new BlockVariant(1, "silver_shipping"),
			SILVER_THERMAL = new BlockVariant(2, "silver_thermal"),
			SILVER_125 = new BlockVariant(3, "silver_125"),
			SILVER_BORDERED = new BlockVariant(4, "silver_bordered"),
			SILVER_BOLTED = new BlockVariant(5, "silver_bolted"),

			SNAKESTONE_SAND_0 = new BlockVariant(0, "snakestone_sand_0"),
			SNAKESTONE_SAND_1 = new BlockVariant(1, "snakestone_sand_1"),

			SNAKESTONE_STONE_0 = new BlockVariant(0, "snakestone_stone_0"),
			SNAKESTONE_STONE_1 = new BlockVariant(1, "snakestone_stone_1"),

			SPRUCE_PLANKS_SMOOTH = new BlockVariant(0, "spruce_planks_smooth"),
			SPRUCE_PLANKS_SHORT = new BlockVariant(1, "spruce_planks_short"),
			SPRUCE_PLANKS_FANCY = new BlockVariant(2, "spruce_planks_fancy"),
			SPRUCE_PLANKS_PANEL = new BlockVariant(3, "spruce_planks_panel"),
			SPRUCE_PLANKS_DOUBLE_SLAB = new BlockVariant(4, "spruce_planks_double_slab"),
			SPRUCE_PLANKS_CRATE = new BlockVariant(5, "spruce_planks_crate"),
			SPRUCE_PLANKS_CRATE_FANCY = new BlockVariant(6, "spruce_planks_crate_fancy"),
			SPRUCE_PLANKS_LONG = new BlockVariant(7, "spruce_planks_long"),
			SPRUCE_PLANKS_VERTICAL = new BlockVariant(8, "spruce_planks_vertical"),
			SPRUCE_PLANKS_VERTICAL_UNEVEN = new BlockVariant(9, "spruce_planks_vertical_uneven"),
			SPRUCE_PLANKS_PARQUET = new BlockVariant(10, "spruce_planks_parquet"),
			SPRUCE_PLANKS_BLINDS = new BlockVariant(11, "spruce_planks_blinds"),
			SPRUCE_PLANKS_SCAFFOLD = new BlockVariant(12, "spruce_planks_scaffold"),
			SPRUCE_PLANKS_DISARRAY = new BlockVariant(13, "spruce_planks_disarray"),
			SPRUCE_PLANKS_DISARRAY_VERTICAL = new BlockVariant(14, "spruce_planks_disarray_vertical"),

			STAINED_GLASS_BLACK_BUBBLE = new BlockVariant(0, "stained_glass_black_bubble"),
			STAINED_GLASS_BLACK_PANEL = new BlockVariant(1, "stained_glass_black_panel"),
			STAINED_GLASS_BLACK_PANEL_FANCY = new BlockVariant(2, "stained_glass_black_panel_fancy"),
			STAINED_GLASS_BLACK_BORDERLESS = new BlockVariant(3, "stained_glass_black_borderless"),

			STAINED_GLASS_RED_BUBBLE = new BlockVariant(0, "stained_glass_red_bubble"),
			STAINED_GLASS_RED_PANEL = new BlockVariant(1, "stained_glass_red_panel"),
			STAINED_GLASS_RED_PANEL_FANCY = new BlockVariant(2, "stained_glass_red_panel_fancy"),
			STAINED_GLASS_RED_BORDERLESS = new BlockVariant(3, "stained_glass_red_borderless"),

			STAINED_GLASS_GREEN_BUBBLE = new BlockVariant(0, "stained_glass_green_bubble"),
			STAINED_GLASS_GREEN_PANEL = new BlockVariant(1, "stained_glass_green_panel"),
			STAINED_GLASS_GREEN_PANEL_FANCY = new BlockVariant(2, "stained_glass_green_panel_fancy"),
			STAINED_GLASS_GREEN_BORDERLESS = new BlockVariant(3, "stained_glass_green_borderless"),

			STAINED_GLASS_BROWN_BUBBLE = new BlockVariant(0, "stained_glass_brown_bubble"),
			STAINED_GLASS_BROWN_PANEL = new BlockVariant(1, "stained_glass_brown_panel"),
			STAINED_GLASS_BROWN_PANEL_FANCY = new BlockVariant(2, "stained_glass_brown_panel_fancy"),
			STAINED_GLASS_BROWN_BORDERLESS = new BlockVariant(3, "stained_glass_brown_borderless"),

			STAINED_GLASS_BLUE_BUBBLE = new BlockVariant(0, "stained_glass_blue_bubble"),
			STAINED_GLASS_BLUE_PANEL = new BlockVariant(1, "stained_glass_blue_panel"),
			STAINED_GLASS_BLUE_PANEL_FANCY = new BlockVariant(2, "stained_glass_blue_panel_fancy"),
			STAINED_GLASS_BLUE_BORDERLESS = new BlockVariant(3, "stained_glass_blue_borderless"),

			STAINED_GLASS_PURPLE_BUBBLE = new BlockVariant(0, "stained_glass_purple_bubble"),
			STAINED_GLASS_PURPLE_PANEL = new BlockVariant(1, "stained_glass_purple_panel"),
			STAINED_GLASS_PURPLE_PANEL_FANCY = new BlockVariant(2, "stained_glass_purple_panel_fancy"),
			STAINED_GLASS_PURPLE_BORDERLESS = new BlockVariant(3, "stained_glass_purple_borderless"),

			STAINED_GLASS_CYAN_BUBBLE = new BlockVariant(0, "stained_glass_cyan_bubble"),
			STAINED_GLASS_CYAN_PANEL = new BlockVariant(1, "stained_glass_cyan_panel"),
			STAINED_GLASS_CYAN_PANEL_FANCY = new BlockVariant(2, "stained_glass_cyan_panel_fancy"),
			STAINED_GLASS_CYAN_BORDERLESS = new BlockVariant(3, "stained_glass_cyan_borderless"),

			STAINED_GLASS_LIGHT_GRAY_BUBBLE = new BlockVariant(0, "stained_glass_light_gray_bubble"),
			STAINED_GLASS_LIGHT_GRAY_PANEL = new BlockVariant(1, "stained_glass_light_gray_panel"),
			STAINED_GLASS_LIGHT_GRAY_PANEL_FANCY = new BlockVariant(2, "stained_glass_light_gray_panel_fancy"),
			STAINED_GLASS_LIGHT_GRAY_BORDERLESS = new BlockVariant(3, "stained_glass_light_gray_borderless"),

			STAINED_GLASS_GRAY_BUBBLE = new BlockVariant(0, "stained_glass_gray_bubble"),
			STAINED_GLASS_GRAY_PANEL = new BlockVariant(1, "stained_glass_gray_panel"),
			STAINED_GLASS_GRAY_PANEL_FANCY = new BlockVariant(2, "stained_glass_gray_panel_fancy"),
			STAINED_GLASS_GRAY_BORDERLESS = new BlockVariant(3, "stained_glass_gray_borderless"),

			STAINED_GLASS_PINK_BUBBLE = new BlockVariant(0, "stained_glass_pink_bubble"),
			STAINED_GLASS_PINK_PANEL = new BlockVariant(1, "stained_glass_pink_panel"),
			STAINED_GLASS_PINK_PANEL_FANCY = new BlockVariant(2, "stained_glass_pink_panel_fancy"),
			STAINED_GLASS_PINK_BORDERLESS = new BlockVariant(3, "stained_glass_pink_borderless"),

			STAINED_GLASS_LIME_BUBBLE = new BlockVariant(0, "stained_glass_lime_bubble"),
			STAINED_GLASS_LIME_PANEL = new BlockVariant(1, "stained_glass_lime_panel"),
			STAINED_GLASS_LIME_PANEL_FANCY = new BlockVariant(2, "stained_glass_lime_panel_fancy"),
			STAINED_GLASS_LIME_BORDERLESS = new BlockVariant(3, "stained_glass_lime_borderless"),

			STAINED_GLASS_YELLOW_BUBBLE = new BlockVariant(0, "stained_glass_yellow_bubble"),
			STAINED_GLASS_YELLOW_PANEL = new BlockVariant(1, "stained_glass_yellow_panel"),
			STAINED_GLASS_YELLOW_PANEL_FANCY = new BlockVariant(2, "stained_glass_yellow_panel_fancy"),
			STAINED_GLASS_YELLOW_BORDERLESS = new BlockVariant(3, "stained_glass_yellow_borderless"),

			STAINED_GLASS_LIGHT_BLUE_BUBBLE = new BlockVariant(0, "stained_glass_light_blue_bubble"),
			STAINED_GLASS_LIGHT_BLUE_PANEL = new BlockVariant(1, "stained_glass_light_blue_panel"),
			STAINED_GLASS_LIGHT_BLUE_PANEL_FANCY = new BlockVariant(2, "stained_glass_light_blue_panel_fancy"),
			STAINED_GLASS_LIGHT_BLUE_BORDERLESS = new BlockVariant(3, "stained_glass_light_blue_borderless"),

			STAINED_GLASS_MAGENTA_BUBBLE = new BlockVariant(0, "stained_glass_magenta_bubble"),
			STAINED_GLASS_MAGENTA_PANEL = new BlockVariant(1, "stained_glass_magenta_panel"),
			STAINED_GLASS_MAGENTA_PANEL_FANCY = new BlockVariant(2, "stained_glass_magenta_panel_fancy"),
			STAINED_GLASS_MAGENTA_BORDERLESS = new BlockVariant(3, "stained_glass_magenta_borderless"),

			STAINED_GLASS_ORANGE_BUBBLE = new BlockVariant(0, "stained_glass_orange_bubble"),
			STAINED_GLASS_ORANGE_PANEL = new BlockVariant(1, "stained_glass_orange_panel"),
			STAINED_GLASS_ORANGE_PANEL_FANCY = new BlockVariant(2, "stained_glass_orange_panel_fancy"),
			STAINED_GLASS_ORANGE_BORDERLESS = new BlockVariant(3, "stained_glass_orange_borderless"),

			STAINED_GLASS_WHITE_BUBBLE = new BlockVariant(0, "stained_glass_white_bubble"),
			STAINED_GLASS_WHITE_PANEL = new BlockVariant(1, "stained_glass_white_panel"),
			STAINED_GLASS_WHITE_PANEL_FANCY = new BlockVariant(2, "stained_glass_white_panel_fancy"),
			STAINED_GLASS_WHITE_BORDERLESS = new BlockVariant(3, "stained_glass_white_borderless"),

			STAINED_GLASS_PANE_BLACK_BUBBLE = new BlockVariant(0, "stained_glass_pane_black_bubble"),
			STAINED_GLASS_PANE_BLACK_PANEL = new BlockVariant(1, "stained_glass_pane_black_panel"),
			STAINED_GLASS_PANE_BLACK_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_black_panel_fancy"),
			STAINED_GLASS_PANE_BLACK_BORDERLESS = new BlockVariant(3, "stained_glass_pane_black_borderless"),

			STAINED_GLASS_PANE_RED_BUBBLE = new BlockVariant(0, "stained_glass_pane_red_bubble"),
			STAINED_GLASS_PANE_RED_PANEL = new BlockVariant(1, "stained_glass_pane_red_panel"),
			STAINED_GLASS_PANE_RED_PANEL_FANCY = new BlockVariant(2, "stained_glas_panes_red_panel_fancy"),
			STAINED_GLASS_PANE_RED_BORDERLESS = new BlockVariant(3, "stained_glass_pane_red_borderless"),

			STAINED_GLASS_PANE_GREEN_BUBBLE = new BlockVariant(0, "stained_glass_pane_green_bubble"),
			STAINED_GLASS_PANE_GREEN_PANEL = new BlockVariant(1, "stained_glass_pane_green_panel"),
			STAINED_GLASS_PANE_GREEN_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_green_panel_fancy"),
			STAINED_GLASS_PANE_GREEN_BORDERLESS = new BlockVariant(3, "stained_glass_pane_green_borderless"),

			STAINED_GLASS_PANE_BROWN_BUBBLE = new BlockVariant(0, "stained_glass_pane_brown_bubble"),
			STAINED_GLASS_PANE_BROWN_PANEL = new BlockVariant(1, "stained_glass_pane_brown_panel"),
			STAINED_GLASS_PANE_BROWN_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_brown_panel_fancy"),
			STAINED_GLASS_PANE_BROWN_BORDERLESS = new BlockVariant(3, "stained_glass_pane_brown_borderless"),

			STAINED_GLASS_PANE_BLUE_BUBBLE = new BlockVariant(0, "stained_glass_pane_blue_bubble"),
			STAINED_GLASS_PANE_BLUE_PANEL = new BlockVariant(1, "stained_glass_pane_blue_panel"),
			STAINED_GLASS_PANE_BLUE_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_blue_panel_fancy"),
			STAINED_GLASS_PANE_BLUE_BORDERLESS = new BlockVariant(3, "stained_glass_pane_blue_borderless"),

			STAINED_GLASS_PANE_PURPLE_BUBBLE = new BlockVariant(0, "stained_glass_pane_purple_bubble"),
			STAINED_GLASS_PANE_PURPLE_PANEL = new BlockVariant(1, "stained_glass_pane_purple_panel"),
			STAINED_GLASS_PANE_PURPLE_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_purple_panel_fancy"),
			STAINED_GLASS_PANE_PURPLE_BORDERLESS = new BlockVariant(3, "stained_glass_pane_purple_borderless"),

			STAINED_GLASS_PANE_CYAN_BUBBLE = new BlockVariant(0, "stained_glass_pane_cyan_bubble"),
			STAINED_GLASS_PANE_CYAN_PANEL = new BlockVariant(1, "stained_glass_pane_cyan_panel"),
			STAINED_GLASS_PANE_CYAN_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_cyan_panel_fancy"),
			STAINED_GLASS_PANE_CYAN_BORDERLESS = new BlockVariant(3, "stained_glass_pane_cyan_borderless"),

			STAINED_GLASS_PANE_LIGHT_GRAY_BUBBLE = new BlockVariant(0, "stained_glass_pane_light_gray_bubble"),
			STAINED_GLASS_PANE_LIGHT_GRAY_PANEL = new BlockVariant(1, "stained_glass_pane_light_gray_panel"),
			STAINED_GLASS_PANE_LIGHT_GRAY_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_light_gray_panel_fancy"),
			STAINED_GLASS_PANE_LIGHT_GRAY_BORDERLESS = new BlockVariant(3, "stained_glass_pane_light_gray_borderless"),

			STAINED_GLASS_PANE_GRAY_BUBBLE = new BlockVariant(0, "stained_glass_pane_gray_bubble"),
			STAINED_GLASS_PANE_GRAY_PANEL = new BlockVariant(1, "stained_glass_pane_gray_panel"),
			STAINED_GLASS_PANE_GRAY_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_gray_panel_fancy"),
			STAINED_GLASS_PANE_GRAY_BORDERLESS = new BlockVariant(3, "stained_glass_pane_gray_borderless"),

			STAINED_GLASS_PANE_PINK_BUBBLE = new BlockVariant(0, "stained_glass_pane_pink_bubble"),
			STAINED_GLASS_PANE_PINK_PANEL = new BlockVariant(1, "stained_glass_pane_pink_panel"),
			STAINED_GLASS_PANE_PINK_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_pink_panel_fancy"),
			STAINED_GLASS_PANE_PINK_BORDERLESS = new BlockVariant(3, "stained_glass_pane_pink_borderless"),

			STAINED_GLASS_PANE_LIME_BUBBLE = new BlockVariant(0, "stained_glass_pane_lime_bubble"),
			STAINED_GLASS_PANE_LIME_PANEL = new BlockVariant(1, "stained_glass_pane_lime_panel"),
			STAINED_GLASS_PANE_LIME_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_lime_panel_fancy"),
			STAINED_GLASS_PANE_LIME_BORDERLESS = new BlockVariant(3, "stained_glass_pane_lime_borderless"),

			STAINED_GLASS_PANE_YELLOW_BUBBLE = new BlockVariant(0, "stained_glass_pane_yellow_bubble"),
			STAINED_GLASS_PANE_YELLOW_PANEL = new BlockVariant(1, "stained_glass_pane_yellow_panel"),
			STAINED_GLASS_PANE_YELLOW_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_yellow_panel_fancy"),
			STAINED_GLASS_PANE_YELLOW_BORDERLESS = new BlockVariant(3, "stained_glass_pane_yellow_borderless"),

			STAINED_GLASS_PANE_LIGHT_BLUE_BUBBLE = new BlockVariant(0, "stained_glass_pane_light_blue_bubble"),
			STAINED_GLASS_PANE_LIGHT_BLUE_PANEL = new BlockVariant(1, "stained_glass_pane_light_blue_panel"),
			STAINED_GLASS_PANE_LIGHT_BLUE_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_light_blue_panel_fancy"),
			STAINED_GLASS_PANE_LIGHT_BLUE_BORDERLESS = new BlockVariant(3, "stained_glass_pane_light_blue_borderless"),

			STAINED_GLASS_PANE_MAGENTA_BUBBLE = new BlockVariant(0, "stained_glass_pane_magenta_bubble"),
			STAINED_GLASS_PANE_MAGENTA_PANEL = new BlockVariant(1, "stained_glass_pane_magenta_panel"),
			STAINED_GLASS_PANE_MAGENTA_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_magenta_panel_fancy"),
			STAINED_GLASS_PANE_MAGENTA_BORDERLESS = new BlockVariant(3, "stained_glass_pane_magenta_borderless"),

			STAINED_GLASS_PANE_ORANGE_BUBBLE = new BlockVariant(0, "stained_glass_pane_orange_bubble"),
			STAINED_GLASS_PANE_ORANGE_PANEL = new BlockVariant(1, "stained_glass_pane_orange_panel"),
			STAINED_GLASS_PANE_ORANGE_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_orange_panel_fancy"),
			STAINED_GLASS_PANE_ORANGE_BORDERLESS = new BlockVariant(3, "stained_glass_pane_orange_borderless"),

			STAINED_GLASS_PANE_WHITE_BUBBLE = new BlockVariant(0, "stained_glass_pane_white_bubble"),
			STAINED_GLASS_PANE_WHITE_PANEL = new BlockVariant(1, "stained_glass_pane_white_panel"),
			STAINED_GLASS_PANE_WHITE_PANEL_FANCY = new BlockVariant(2, "stained_glass_pane_white_panel_fancy"),
			STAINED_GLASS_PANE_WHITE_BORDERLESS = new BlockVariant(3, "stained_glass_pane_white_borderless"),

			STEEL_CAUTION = new BlockVariant(0, "steel_caution"),
			STEEL_SHIPPING = new BlockVariant(1, "steel_shipping"),
			STEEL_THERMAL = new BlockVariant(2, "steel_thermal"),
			STEEL_125 = new BlockVariant(3, "steel_125"),
			STEEL_BORDERED = new BlockVariant(4, "steel_bordered"),
			STEEL_BOLTED = new BlockVariant(5, "steel_bolted"),

			STONE_BRICKS_NEUTRAL = new BlockVariant(0, "stone_bricks_neutral"),
			STONE_BRICKS_FELSIC = new BlockVariant(1, "stone_bricks_felsic"),
			STONE_BRICKS_MAFIC = new BlockVariant(2, "stone_bricks_mafic"),
			STONE_BRICKS_SMALL = new BlockVariant(3, "stone_bricks_small"),
			STONE_BRICKS_WIDE = new BlockVariant(4, "stone_bricks_wide"),
			STONE_BRICKS_DISORDERED_SMALL = new BlockVariant(5, "stone_bricks_disordered_small"),
			STONE_BRICKS_DISORDERED = new BlockVariant(6, "stone_bricks_disordered"),
			STONE_BRICKS_DISORDERED_PANEL = new BlockVariant(7, "stone_bricks_disordered_panel"),
			STONE_BRICKS_FANCY = new BlockVariant(8, "stone_bricks_fancy"),
			STONE_BRICKS_ORNATE = new BlockVariant(9, "stone_bricks_ornate"),
			STONE_BRICKS_ORNATE_LARGE = new BlockVariant(10, "stone_bricks_ornate_large"),
			STONE_BRICKS_PANEL = new BlockVariant(11, "stone_bricks_panel"),
			STONE_BRICKS_PANEL_SUNKEN = new BlockVariant(12, "stone_bricks_panel_sunken"),
			STONE_BRICKS_PANEL_ORNATE = new BlockVariant(13, "stone_bricks_panel_ornate"),
			STONE_BRICKS_POISON = new BlockVariant(14, "stone_bricks_poison"),

			TECHNICAL_SCAFFOLD = new BlockVariant(0, "technical_scaffold"),
			TECHNICAL_PANEL_CAUTION = new BlockVariant(1, "technical_panel_caution"),
			TECHNICAL_125 = new BlockVariant(2, "technical_125"),
			TECHNICAL_UNDER_LARGE = new BlockVariant(3, "technical_UNDER_LARGE"),
			TECHNICAL_FAN_FAST = new BlockVariant(4, "technical_fan_fast"),
			TECHNICAL_UNDER_SMALL = new BlockVariant(5, "technical_under_small"),
			TECHNICAL_FAN_OFF = new BlockVariant(6, "technical_fan_off"),
			TECHNICAL_VENTS = new BlockVariant(7, "technical_vents"),
			TECHNICAL_VENTS_GLOWING = new BlockVariant(8, "technical_vents_glowing"),
			TECHNICAL_INSULATION = new BlockVariant(9, "technical_insulation"),
			TECHNICAL_GEARS = new BlockVariant(10, "technical_gears"),
			TECHNICAL_CABLES = new BlockVariant(11, "technical_cables"),
			TECHNICAL_PANEL_RUSTY = new BlockVariant(12, "technical_plate_rusty"),
			TECHNICAL_GRATE = new BlockVariant(13, "technical_grate"),
			TECHNICAL_FAN_MALFUNCTIONING = new BlockVariant(14, "technical_fan_malfunctioning"),
			TECHNICAL_GRATE_RUSTY = new BlockVariant(15, "technical_grate_rusty"),

			TEMPLE_COBBLE = new BlockVariant(0, "temple_cobble"),
			TEMPLE_ORNATE = new BlockVariant(1, "temple_ornate"),
			TEMPLE_PLATE = new BlockVariant(2, "temple_plate"),
			TEMPLE_PLATE_CRACKED = new BlockVariant(3, "temple_plate_cracked"),
			TEMPLE_BRICKS = new BlockVariant(4, "temple_bricks"),
			TEMPLE_BRICKS_LARGE = new BlockVariant(5, "temple_bricks_large"),
			TEMPLE_BRICKS_WORN = new BlockVariant(6, "temple_bricks_worn"),
			TEMPLE_BRICKS_DISARRAY = new BlockVariant(7, "temple_bricks_disarray"),
			TEMPLE_COLUMN = new BlockVariant(8, "temple_column"),
			TEMPLE_STAND = new BlockVariant(9, "temple_stand"),
			TEMPLE_STAND_MOSAIC = new BlockVariant(10, "temple_stand_mosaic"),
			TEMPLE_STAND_CREEPER = new BlockVariant(11, "temple_stand_creeper"),
			TEMPLE_TILES = new BlockVariant(12, "temple_tiles"),
			TEMPLE_TILES_SMALL = new BlockVariant(13, "temple_tiles_small"),
			TEMPLE_TILES_LIGHT = new BlockVariant(14, "temple_tiles_light"),
			TEMPLE_TILES_SMALL_LIGHT = new BlockVariant(15, "temple_tiles_small_light"),

			TIN_CAUTION = new BlockVariant(0, "tin_caution"),
			TIN_SHIPPING = new BlockVariant(1, "tin_shipping"),
			TIN_THERMAL = new BlockVariant(2, "tin_thermal"),
			TIN_125 = new BlockVariant(3, "tin_125"),
			TIN_BORDERED = new BlockVariant(4, "tin_bordered"),
			TIN_BOLTED = new BlockVariant(5, "tin_bolted"),

			TORCH_0 = new BlockVariant(0, "torch_0"),
			TORCH_1 = new BlockVariant(1, "torch_1"),
			TORCH_2 = new BlockVariant(2, "torch_2"),
			TORCH_3 = new BlockVariant(3, "torch_3"),
			TORCH_4 = new BlockVariant(4, "torch_4"),
			TORCH_5 = new BlockVariant(5, "torch_5"),
			TORCH_6 = new BlockVariant(6, "torch_6"),
			TORCH_7 = new BlockVariant(7, "torch_7"),
			TORCH_8 = new BlockVariant(8, "torch_8"),
			TORCH_9 = new BlockVariant(9, "torch_9"),

			TRANSPARENT_TECHNICAL_SCAFFOLD = new BlockVariant(0, "transparent_technical_scaffold"),
			TRANSPARENT_TECHNICAL_FAN_FAST = new BlockVariant(1, "transparent_technical_fan_fast"),
			TRANSPARENT_TECHNICAL_FAN_OFF = new BlockVariant(2, "transparent_technical_fan_off"),
			TRANSPARENT_TECHNICAL_FAN_MALFUNCTIONING = new BlockVariant(3, "transparent_technical_fan_malfunctioning"),

			TYRIAN_NORMAL = new BlockVariant(0, "tyrian_normal"),
			TYRIAN_BLEAK = new BlockVariant(1, "tyrian_bleak"),
			TYRIAN_PURPLE = new BlockVariant(2, "tyrian_purple"),
			TYRIAN_PURPLE_FADED = new BlockVariant(3, "tyrian_purple_faded"),
			TYRIAN_RUSTED = new BlockVariant(4, "tyrian_rusted"),
			TYRIAN_ELABORATE = new BlockVariant(5, "tyrian_elaborate"),
			TYRIAN_SEAMS = new BlockVariant(6, "tyrian_seams"),
			TYRIAN_PLATFORM = new BlockVariant(7, "tyrian_platform"),
			TYRIAN_TILES = new BlockVariant(8, "tyrian_tiles"),
			TYRIAN_DIAGONAL = new BlockVariant(9, "tyrian_diagonal"),
			TYRIAN_DENT = new BlockVariant(10, "tyrian_dent"),
			TYRIAN_BLUE = new BlockVariant(11, "tyrian_blue"),
			TYRIAN_BLACK = new BlockVariant(12, "tyrian_black"),
			TYRIAN_BLACK_TILES = new BlockVariant(13, "tyrian_black_tiles"),
			TYRIAN_OPENING = new BlockVariant(14, "tyrian_opening"),
			TYRIAN_SHINY = new BlockVariant(15, "tyrian_shiny"),

			URANIUM_CAUTION = new BlockVariant(0, "uranium_caution"),
			URANIUM_SHIPPING = new BlockVariant(1, "uranium_shipping"),
			URANIUM_THERMAL = new BlockVariant(2, "uranium_thermal"),
			URANIUM_125 = new BlockVariant(3, "uranium_125"),
			URANIUM_BORDERED = new BlockVariant(4, "uranium_bordered"),
			URANIUM_BOLTED = new BlockVariant(5, "uranium_bolted"),

			VALENTINES_BRICKS = new BlockVariant(0, "valentines_bricks"),
			VALENTINES_COMPANION = new BlockVariant(0, "valentines_companion"),
			VALENTINES_EMPTY = new BlockVariant(0, "valentines_empty"),
			VALENTINES_HEART = new BlockVariant(0, "valentines_heart"),
			VALENTINES_HEART_GRAY = new BlockVariant(0, "valentines_heart gray"),
			VALENTINES_BLOCK = new BlockVariant(0, "valentines_block"),
			VALENTINES_COBBLE = new BlockVariant(0, "valentines_cobble"),
			VALENTINES_BUMPY = new BlockVariant(0, "valentines_bumpy"),
			VALENTINES_FIRE = new BlockVariant(0, "valentines_fire"),
			VALENTINES_TILE = new BlockVariant(0, "valentines_tile"),

			VOIDSTONE_RAW = new BlockVariant(0, "voidstone_raw"),
			VOIDSTONE_TILES = new BlockVariant(1, "voidstone_tiles"),
			VOIDSTONE_SMOOTH = new BlockVariant(2, "voidstone_smooth"),
			VOIDSTONE_SKULL = new BlockVariant(3, "voidstone_skull"),
			VOIDSTONE_RUNIC = new BlockVariant(4, "voidstone_runic"),
			VOIDSTONE_METAL = new BlockVariant(5, "voidstone_metal"),
			VOIDSTONE_EYE = new BlockVariant(6, "voidstone_eye"),
			VOIDSTONE_BEVEL = new BlockVariant(7, "voidstone_bevel"),

			WARNING_RADIATION = new BlockVariant(0, "warning_radiation"),
			WARNING_BIOHAZARD = new BlockVariant(0, "warning_biohazard"),
			WARNING_FIRE = new BlockVariant(0, "warning_fire"),
			WARNING_EXPLOSION = new BlockVariant(0, "warning_explosion"),
			WARNING_DEATH = new BlockVariant(0, "warning_death"),
			WARNING_FALLING_OBJECTS = new BlockVariant(0, "warning_falling_objects"),
			WARNING_FALLING = new BlockVariant(0, "warning_falling"),
			WARNING_VOLTAGE = new BlockVariant(0, "warning_voltage"),
			WARNING_GENERIC = new BlockVariant(0, "warning_generic"),
			WARNING_CHEM = new BlockVariant(0, "warning_chem"),
			WARNING_CONSTRUCTION = new BlockVariant(0, "warning_construction"),
			WARNING_LOUD = new BlockVariant(0, "warning_loud"),
			WARNING_NO_ENTRY = new BlockVariant(0, "warning_no_entry"),
			WARNING_CRYOGENIC = new BlockVariant(0, "warning_cryogenic"),
			WARNING_OXYGEN = new BlockVariant(0, "warning_oxygen"),

			WATERSTONE_BRICKS = new BlockVariant(0, "waterstone_bricks"),
			WATERSTONE_BLACK = new BlockVariant(0, "waterstone_black"),
			WATERSTONE_TILES = new BlockVariant(0, "waterstone_tiles"),
			WATERSTONE_CHAOTIC = new BlockVariant(0, "waterstone_chaotic"),
			WATERSTONE_CREEPER = new BlockVariant(0, "waterstone_creeper"),
			WATERSTONE_PANEL = new BlockVariant(0, "waterstone_panel"),
			WATERSTONE_ORNATE = new BlockVariant(0, "waterstone_ornate"),

			WOOLEN_CLAY_0 = new BlockVariant(0, "woolen_clay_0"),
			WOOLEN_CLAY_1 = new BlockVariant(1, "woolen_clay_1"),
			WOOLEN_CLAY_2 = new BlockVariant(2, "woolen_clay_2"),
			WOOLEN_CLAY_3 = new BlockVariant(3, "woolen_clay_3"),
			WOOLEN_CLAY_4 = new BlockVariant(4, "woolen_clay_4"),
			WOOLEN_CLAY_5 = new BlockVariant(5, "woolen_clay_5"),
			WOOLEN_CLAY_6 = new BlockVariant(6, "woolen_clay_6"),
			WOOLEN_CLAY_7 = new BlockVariant(7, "woolen_clay_7"),
			WOOLEN_CLAY_8 = new BlockVariant(8, "woolen_clay_8"),
			WOOLEN_CLAY_9 = new BlockVariant(9, "woolen_clay_9"),
			WOOLEN_CLAY_10 = new BlockVariant(10, "woolen_clay_10"),
			WOOLEN_CLAY_11 = new BlockVariant(11, "woolen_clay_11"),
			WOOLEN_CLAY_12 = new BlockVariant(12, "woolen_clay_12"),
			WOOLEN_CLAY_13 = new BlockVariant(13, "woolen_clay_13"),
			WOOLEN_CLAY_14 = new BlockVariant(14, "woolen_clay_14"),
			WOOLEN_CLAY_15 = new BlockVariant(15, "woolen_clay_15");
}
