package com.cricketcraft.chisel.block.variant;

import com.cricketcraft.chisel.util.BlockVariant;

public class BlockVariants
{
	public static final BlockVariant
			CLOUD_NORMAL = new BlockVariant(0, "cloud_normal"),
			CLOUD_GRID = new BlockVariant(1, "cloud_grid"),
			CLOUD_LARGE = new BlockVariant(2, "cloud_large"),
			CLOUD_SMALL = new BlockVariant(3, "cloud_small"),
			CLOUD_VERTICAL = new BlockVariant(4, "cloud_vertical"),

			PUMPKIN_0 = new BlockVariant(0, "pumpkin_0"),
			PUMPKIN_1 = new BlockVariant(1, "pumpkin_1"),
			PUMPKIN_2 = new BlockVariant(2, "pumpkin_2"),
			PUMPKIN_3 = new BlockVariant(3, "pumpkin_3"),
			PUMPKIN_4 = new BlockVariant(4, "pumpkin_4"),
			PUMPKIN_5 = new BlockVariant(5, "pumpkin_5"),
			PUMPKIN_6 = new BlockVariant(6, "pumpkin_6"),
			PUMPKIN_7 = new BlockVariant(7, "pumpkin_7"),
			PUMPKIN_8 = new BlockVariant(8, "pumpkin_8"),
			PUMPKIN_9 = new BlockVariant(9, "pumpkin_9"),
			PUMPKIN_10 = new BlockVariant(10, "pumpkin_10"),
			PUMPKIN_11 = new BlockVariant(11, "pumpkin_11"),
			PUMPKIN_12 = new BlockVariant(12, "pumpkin_12"),
			PUMPKIN_13 = new BlockVariant(13, "pumpkin_13"),
			PUMPKIN_14 = new BlockVariant(14, "pumpkin_14"),
			PUMPKIN_15 = new BlockVariant(15, "pumpkin_15"),
			PUMPKIN_16 = new BlockVariant(16, "pumpkin_16"),

			MARBLE_RAW = new BlockVariant(0, "marble_raw"),
			MARBLE_BRICK = new BlockVariant(1, "marble_brick"),
			MARBLE_PANEL_CLASSIC = new BlockVariant(2, "marble_panel_classic"),
			MARBLE_PANEL_ORNATE = new BlockVariant(3, "marble_panel_ornate"),
			MARBLE_PANEL = new BlockVariant(4, "marble_panel"),
			MARBLE_BLOCK = new BlockVariant(5, "marble_block"),
			MARBLE_CREEPER_DARK = new BlockVariant(6, "marble_creeper_dark"),
			MARBLE_CREEPER_LIGHT = new BlockVariant(7, "marble_creeper_light"),
			MARBLE_CARVED = new BlockVariant(8, "marble_carved"),
			MARBLE_CARVED_RADIAL = new BlockVariant(9, "marble_carved_radial"),
			MARBLE_DENT = new BlockVariant(10, "marble_dent"),
			MARBLE_DENT_LARGE = new BlockVariant(11, "marble_dent_large"),
			MARBLE_TILES = new BlockVariant(12, "marble_tiles"),
			MARBLE_TILES_ARRANGED = new BlockVariant(13, "marble_tiles_arranged"),
			MARBLE_TILES_FANCY = new BlockVariant(14, "marble_tiles_fancy"),
			MARBLE_BLOCKS = new BlockVariant(15, "marble_blocks"),

			LIMESTONE_RAW = new BlockVariant(0, "limestone_raw"),
			LIMESTONE_TILES = new BlockVariant(1, "limestone_tiles"),
			LIMESTONE_TILES_FRENCH = new BlockVariant(2, "limestone_tiles_french"),
			LIMESTONE_TILES_FRENCH_LIGHT = new BlockVariant(2, "limestone_tiles_french_light"),
			LIMESTONE_TILES_CREEPER = new BlockVariant(3, "limestone_tiles_creeper"),
			LIMESTONE_TILES_DAMAGED = new BlockVariant(4, "limestone_tiles_damaged"),
			LIMESTONE_TILES_LARGE = new BlockVariant(5, "limestone_tiles_large"),
			LIMESTONE_BRICKS = new BlockVariant(6, "limestone_bricks"),
			LIMESTONE_SMOOTH = new BlockVariant(7, "limestone_smooth"),
			LIMESTONE_PANEL_ORNATE = new BlockVariant(8, "limestone_panel_ornate"),
			LIMESTONE_PANEL_ENGRAVED = new BlockVariant(9, "limestone_panel_engraved"),
			LIMESTONE_PANEL_CREEPER = new BlockVariant(10, "limestone_panel_creeper"),
			LIMESTONE_PANEL_LIGHT = new BlockVariant(11, "limestone_panel_light"),
			LIMESTONE_PANEL_DARK = new BlockVariant(12, "limestone_panel_dark"),
			LIMESTONE_PANEL = new BlockVariant(13, "limestone_panel"),
			LIMESTONE_DENT = new BlockVariant(14, "limestone_dent");
}
