package com.cricketcraft.chisel.init;

import static com.cricketcraft.chisel.block.variant.BlockVariants.*;

import com.cricketcraft.chisel.util.PropertyVariant;

public class ChiselProperties {
	public static final PropertyVariant
			ACCACIA_VARIANTS = PropertyVariant.create("variant", ACCACIA_PLANKS_SMOOTH, ACCACIA_PLANKS_SHORT, ACCACIA_PLANKS_FANCY, ACCACIA_PLANKS_PANEL, ACCACIA_PLANKS_DOUBLE_SLAB, ACCACIA_PLANKS_CRATE, ACCACIA_PLANKS_CRATE_FANCY, ACCACIA_PLANKS_LONG, ACCACIA_PLANKS_VERTICAL, ACCACIA_PLANKS_VERTICAL_UNEVEN, ACCACIA_PLANKS_PARQUET, ACCACIA_PLANKS_BLINDS, ACCACIA_PLANKS_SCAFFOLD, ACCACIA_PLANKS_DISARRAY, ACCACIA_PLANKS_DISARRAY_VERTICAL),
			ALUMINUM_VARIANTS = PropertyVariant.create("variant", ALUMINUM_CAUTION, ALUMINUM_SHIPPING, ALUMINUM_THERMAL, ALUMINUM_125, ALUMINUM_BORDERED, ALUMINUM_BOLTED),
			ANDESITE_VARIANTS = PropertyVariant.create("variant", ANDESITE_POLISHED, ANDESITE_PILLAR, ANDESITE_BRICKS, ANDESITE_ORNATE, ANDESITE_PRISMATIC, ANDESITE_TILES_SMALL),
			ANTIBLOCK_VARIANTS = PropertyVariant.create("variant", ANTIBLOCK_0, ANTIBLOCK_1, ANTIBLOCK_2, ANTIBLOCK_3, ANTIBLOCK_4, ANTIBLOCK_5, ANTIBLOCK_6, ANTIBLOCK_7, ANTIBLOCK_8, ANTIBLOCK_9, ANTIBLOCK_10, ANTIBLOCK_11, ANTIBLOCK_12, ANTIBLOCK_13, ANTIBLOCK_14, ANTIBLOCK_15),
			BIRCH_VARIATIONS = PropertyVariant.create("variant", BIRCH_PLANKS_SMOOTH, BIRCH_PLANKS_SHORT, BIRCH_PLANKS_FANCY, BIRCH_PLANKS_PANEL, BIRCH_PLANKS_DOUBLE_SLAB, BIRCH_PLANKS_CRATE, BIRCH_PLANKS_CRATE_FANCY, BIRCH_PLANKS_LONG, BIRCH_PLANKS_VERTICAL, BIRCH_PLANKS_VERTICAL_UNEVEN, BIRCH_PLANKS_PARQUET, BIRCH_PLANKS_BLINDS, BIRCH_PLANKS_SCAFFOLD, BIRCH_PLANKS_DISARRAY, BIRCH_PLANKS_DISARRAY_VERTICAL),
			BRONZE_VARIANTS = PropertyVariant.create("variant", BRONZE_CAUTION, BRONZE_SHIPPING, BRONZE_THERMAL, BRONZE_125, BRONZE_BORDERED, BRONZE_BOLTED),
			BRICKS_VARIANTS = PropertyVariant.create("variant", BRICKS_LARGE, BRICKS_MORTARLESS, BRICKS_VARIED, BRICKS_AGED, BRICKS_YELLOW),
			BOOKSHELF_VARIANTS = PropertyVariant.create("variant", BOOKSHELF_RAINBOW, BOOKSHELF_NECROMANCER_APPRENTICE, BOOKSHELF_NECROMANCER, BOOKSHELF_TOMES, BOOKSHELF_ABANDONED, BOOKSHELF_HOARDERS, BOOKSHELF_PASTEL, BOOKSHELF_HISTORIAN),
			CARPET_VARIANTS = PropertyVariant.create("variant", CARPET_0, CARPET_1, CARPET_2, CARPET_3, CARPET_4, CARPET_5, CARPET_6, CARPET_7, CARPET_8, CARPET_9, CARPET_10, CARPET_11, CARPET_12, CARPET_13, CARPET_14, CARPET_15),
			CARPET_FLOOR_VARIANTS = PropertyVariant.create("variant", CARPET_FLOOR_0, CARPET_FLOOR_1, CARPET_FLOOR_2, CARPET_FLOOR_3, CARPET_FLOOR_4, CARPET_FLOOR_5, CARPET_FLOOR_6, CARPET_FLOOR_7, CARPET_FLOOR_8, CARPET_FLOOR_9, CARPET_FLOOR_10, CARPET_FLOOR_11, CARPET_FLOOR_12, CARPET_FLOOR_13, CARPET_FLOOR_14, CARPET_FLOOR_15),
			CHEST_VARIANTS = PropertyVariant.create("variant", CHEST_0, CHEST_1, CHEST_2, CHEST_3, CHEST_4, CHEST_5, CHEST_6, CHEST_7, CHEST_8, CHEST_9, CHEST_10, CHEST_11, CHEST_12, CHEST_13, CHEST_14, CHEST_15),
			COBBLESTONE_VARIANTS = PropertyVariant.create("variant", COBBLESTONE_BRICKS_ALIGNED);


	public static final PropertyVariant CLOUD_VARIANTS = PropertyVariant.create("variant", CLOUD_NORMAL, CLOUD_GRID, CLOUD_LARGE, CLOUD_SMALL, CLOUD_VERTICAL);

	public static final PropertyVariant LIMESTONE_VARIANTS = PropertyVariant.create("variant", LIMESTONE_RAW, LIMESTONE_TILES, LIMESTONE_TILES_FRENCH, LIMESTONE_TILES_FRENCH_LIGHT, LIMESTONE_TILES_CREEPER, LIMESTONE_TILES_DAMAGED, LIMESTONE_TILES_LARGE, LIMESTONE_BRICKS, LIMESTONE_SMOOTH, LIMESTONE_PANEL_ORNATE, LIMESTONE_PANEL_ENGRAVED, LIMESTONE_PANEL_CREEPER, LIMESTONE_PANEL_LIGHT, LIMESTONE_PANEL_DARK, LIMESTONE_PANEL, LIMESTONE_DENT);

	public static final PropertyVariant MARBLE_VARIANTS = PropertyVariant.create("variant", MARBLE_RAW, MARBLE_BRICK, MARBLE_PANEL_CLASSIC, MARBLE_PANEL_ORNATE, MARBLE_PANEL, MARBLE_BLOCK, MARBLE_CREEPER_DARK, MARBLE_CREEPER_LIGHT, MARBLE_CARVED, MARBLE_CARVED_RADIAL, MARBLE_DENT, MARBLE_DENT_LARGE, MARBLE_TILES, MARBLE_TILES_ARRANGED, MARBLE_TILES_FANCY, MARBLE_BLOCKS);

	public static final PropertyVariant PUMPKINS_VARIANTS = PropertyVariant.create("variant", PUMPKIN_0, PUMPKIN_1, PUMPKIN_2, PUMPKIN_3, PUMPKIN_4, PUMPKIN_5, PUMPKIN_6, PUMPKIN_7, PUMPKIN_8, PUMPKIN_9, PUMPKIN_10, PUMPKIN_11, PUMPKIN_12, PUMPKIN_13, PUMPKIN_14, PUMPKIN_15, PUMPKIN_16);
	public static final PropertyVariant JACKOLANTERN_VARIANTS = PropertyVariant.create("variant", LITPUMPKIN_0, LITPUMPKIN_1, LITPUMPKIN_2, LITPUMPKIN_3, LITPUMPKIN_4, LITPUMPKIN_5, LITPUMPKIN_6, LITPUMPKIN_7, LITPUMPKIN_8, LITPUMPKIN_9, LITPUMPKIN_10, LITPUMPKIN_11, LITPUMPKIN_12, LITPUMPKIN_13, LITPUMPKIN_14, LITPUMPKIN_15, LITPUMPKIN_16);
}
