package com.cricketcraft.chisel.init;

import static com.cricketcraft.chisel.block.variant.BlockVariants.*;

import com.cricketcraft.chisel.util.PropertyVariant;

public class ChiselProperties
{
	public static final PropertyVariant CLOUD_VARIANTS = PropertyVariant.create("variant", CLOUD_NORMAL, CLOUD_GRID, CLOUD_LARGE, CLOUD_SMALL, CLOUD_VERTICAL);
	public static final PropertyVariant LIMESTONE_VARIANTS = PropertyVariant.create("variant", LIMESTONE_RAW, LIMESTONE_TILES, LIMESTONE_TILES_FRENCH, LIMESTONE_TILES_FRENCH_LIGHT, LIMESTONE_TILES_CREEPER, LIMESTONE_TILES_DAMAGED, LIMESTONE_TILES_LARGE, LIMESTONE_BRICKS, LIMESTONE_SMOOTH, LIMESTONE_PANEL_ORNATE, LIMESTONE_PANEL_ENGRAVED, LIMESTONE_PANEL_CREEPER, LIMESTONE_PANEL_LIGHT, LIMESTONE_PANEL_DARK, LIMESTONE_PANEL, LIMESTONE_DENT);
	public static final PropertyVariant MARBLE_VARIANTS = PropertyVariant.create("variant", MARBLE_RAW, MARBLE_BRICK, MARBLE_PANEL_CLASSIC, MARBLE_PANEL_ORNATE, MARBLE_PANEL, MARBLE_BLOCK, MARBLE_CREEPER_DARK, MARBLE_CREEPER_LIGHT, MARBLE_CARVED, MARBLE_CARVED_RADIAL, MARBLE_DENT, MARBLE_DENT_LARGE, MARBLE_TILES, MARBLE_TILES_ARRANGED, MARBLE_TILES_FANCY, MARBLE_BLOCKS);
	public static final PropertyVariant PUMPKINS_VARIANTS = PropertyVariant.create("variant", PUMPKIN_0, PUMPKIN_1, PUMPKIN_2, PUMPKIN_3, PUMPKIN_4, PUMPKIN_5, PUMPKIN_6, PUMPKIN_7, PUMPKIN_8, PUMPKIN_9, PUMPKIN_10, PUMPKIN_11, PUMPKIN_12, PUMPKIN_13, PUMPKIN_14, PUMPKIN_15, PUMPKIN_16);
}
