package com.cricketcraft.chisel.init;

import static com.cricketcraft.chisel.block.variant.BlockVariants.*;

import com.cricketcraft.chisel.util.PropertyVariant;

public class ChiselProperties {
	public static final PropertyVariant
			ACACIA_VARIANTS = PropertyVariant.create("variant", ACACIA_PLANKS_SMOOTH, ACACIA_PLANKS_SHORT, ACACIA_PLANKS_FANCY, ACACIA_PLANKS_PANEL, ACACIA_PLANKS_DOUBLE_SLAB, ACACIA_PLANKS_CRATE, ACACIA_PLANKS_CRATE_FANCY, ACACIA_PLANKS_LONG, ACACIA_PLANKS_VERTICAL, ACACIA_PLANKS_VERTICAL_UNEVEN, ACACIA_PLANKS_PARQUET, ACACIA_PLANKS_BLINDS, ACACIA_PLANKS_SCAFFOLD, ACACIA_PLANKS_DISARRAY, ACACIA_PLANKS_DISARRAY_VERTICAL),
			ALUMINUM_VARIANTS = PropertyVariant.create("variant", ALUMINUM_CAUTION, ALUMINUM_SHIPPING, ALUMINUM_THERMAL, ALUMINUM_125, ALUMINUM_BORDERED, ALUMINUM_BOLTED),
			ANDESITE_VARIANTS = PropertyVariant.create("variant", ANDESITE_PILLAR, ANDESITE_BRICKS, ANDESITE_ORNATE, ANDESITE_PRISMATIC, ANDESITE_TILES_SMALL),
			ANTIBLOCK_VARIANTS = PropertyVariant.create("variant", ANTIBLOCK_0, ANTIBLOCK_1, ANTIBLOCK_2, ANTIBLOCK_3, ANTIBLOCK_4, ANTIBLOCK_5, ANTIBLOCK_6, ANTIBLOCK_7, ANTIBLOCK_8, ANTIBLOCK_9, ANTIBLOCK_10, ANTIBLOCK_11, ANTIBLOCK_12, ANTIBLOCK_13, ANTIBLOCK_14, ANTIBLOCK_15),
			BIRCH_VARIATIONS = PropertyVariant.create("variant", BIRCH_PLANKS_SMOOTH, BIRCH_PLANKS_SHORT, BIRCH_PLANKS_FANCY, BIRCH_PLANKS_PANEL, BIRCH_PLANKS_DOUBLE_SLAB, BIRCH_PLANKS_CRATE, BIRCH_PLANKS_CRATE_FANCY, BIRCH_PLANKS_LONG, BIRCH_PLANKS_VERTICAL, BIRCH_PLANKS_VERTICAL_UNEVEN, BIRCH_PLANKS_PARQUET, BIRCH_PLANKS_BLINDS, BIRCH_PLANKS_SCAFFOLD, BIRCH_PLANKS_DISARRAY, BIRCH_PLANKS_DISARRAY_VERTICAL),
			BOOKSHELF_VARIANTS = PropertyVariant.create("variant", BOOKSHELF_RAINBOW, BOOKSHELF_NECROMANCER_APPRENTICE, BOOKSHELF_NECROMANCER, BOOKSHELF_TOMES, BOOKSHELF_ABANDONED, BOOKSHELF_HOARDERS, BOOKSHELF_PASTEL, BOOKSHELF_HISTORIAN),
	BRICKS_VARIANTS = PropertyVariant.create("variant", BRICKS_LARGE, BRICKS_MORTARLESS, BRICKS_VARIED, BRICKS_AGED, BRICKS_YELLOW),
			BRONZE_VARIANTS = PropertyVariant.create("variant", BRONZE_CAUTION, BRONZE_SHIPPING, BRONZE_THERMAL, BRONZE_125, BRONZE_BORDERED, BRONZE_BOLTED),
			CARPET_VARIANTS = PropertyVariant.create("variant", CARPET_0, CARPET_1, CARPET_2, CARPET_3, CARPET_4, CARPET_5, CARPET_6, CARPET_7, CARPET_8, CARPET_9, CARPET_10, CARPET_11, CARPET_12, CARPET_13, CARPET_14, CARPET_15),
			CARPET_FLOOR_VARIANTS = PropertyVariant.create("variant", CARPET_FLOOR_0, CARPET_FLOOR_1, CARPET_FLOOR_2, CARPET_FLOOR_3, CARPET_FLOOR_4, CARPET_FLOOR_5, CARPET_FLOOR_6, CARPET_FLOOR_7, CARPET_FLOOR_8, CARPET_FLOOR_9, CARPET_FLOOR_10, CARPET_FLOOR_11, CARPET_FLOOR_12, CARPET_FLOOR_13, CARPET_FLOOR_14, CARPET_FLOOR_15),
			CHEST_VARIANTS = PropertyVariant.create("variant", CHEST_0, CHEST_1, CHEST_2, CHEST_3, CHEST_4, CHEST_5, CHEST_6, CHEST_7, CHEST_8, CHEST_9, CHEST_10, CHEST_11, CHEST_12, CHEST_13, CHEST_14, CHEST_15),
			COBBLESTONE_VARIANTS = PropertyVariant.create("variant", COBBLESTONE_BRICKS_ALIGNED, COBBLESTONE_BRICKS_DETAILED, COBBLESTONE_BRICKS_SMALL, COBBLESTONE_TILES_LARGE, COBBLESTONE_TILES_SMALL, COBBLESTONE_TILES_FRENCH, COBBLESTONE_TILES_FRENCH_LIGHT, COBBLESTONE_TILES_CREEPER, COBBLESTONE_TILES_DAMAGED, COBBLESTONE_TILES_DAMAGED, COBBLESTONE_TILES_HUGE, COBBLESTONE_PANEL_CREEPER, COBBLESTONE_DENT, COBBLESTONE_PANEL, COBBLESTONE_PANEL_LIGHT, COBBLESTONE_PANEL_DARK),
			CONCRETE_VARIANTS = PropertyVariant.create("variant", CONCRETE_RAW, CONCRETE_BLOCK, CONCRETE_SLAB, CONCRETE_BLOCKS, CONCRETE_RAW_WEATHERED, CONCRETE_BLOCK_WEATHERED, CONCRETE_SLAB_WEATHERED, CONCRETE_BLOCKS_WEATHERED, CONCRETE_RAW_PARTLY, CONCRETE_BLOCK_PARTLY, CONCRETE_ASPHALT),
			COPPER_VARIANTS = PropertyVariant.create("variant", COPPER_CAUTION, COPPER_SHIPPING, COPPER_THERMAL, COPPER_125, COPPER_BORDERED, COPPER_BOLTED),
			CLOUD_VARIANTS = PropertyVariant.create("variant", CLOUD_NORMAL, CLOUD_GRID, CLOUD_LARGE, CLOUD_SMALL, CLOUD_VERTICAL),
			DARK_OAK_VARIANTS = PropertyVariant.create("variant", DARK_OAK_PLANKS_SMOOTH, DARK_OAK_PLANKS_SHORT, DARK_OAK_PLANKS_FANCY, DARK_OAK_PLANKS_PANEL, DARK_OAK_PLANKS_DOUBLE_SLAB, DARK_OAK_PLANKS_CRATE, DARK_OAK_PLANKS_CRATE_FANCY, DARK_OAK_PLANKS_LONG, DARK_OAK_PLANKS_VERTICAL, DARK_OAK_PLANKS_VERTICAL_UNEVEN, DARK_OAK_PLANKS_PARQUET, DARK_OAK_PLANKS_BLINDS, DARK_OAK_PLANKS_SCAFFOLD, DARK_OAK_PLANKS_DISARRAY, DARK_OAK_PLANKS_DISARRAY_VERTICAL),
			DIAMOND_VARIANTS = PropertyVariant.create("variant", DIAMOND_EMBOSSED, DIAMOND_PANEL, DIAMOND_CELLS, DIAMOND_OBSIDIAN_PURPLE, DIAMOND_OBSIDIAN, DIAMOND_SIMPLE, DIAMOND_BISMUTH, DIAMOND_CRUSHED, DIAMOND_SMALL_BLOCKS, DIAMOND_SMALL_BLOCKS_ORNATE, DIAMOND_ZELDA, DIAMOND_ORNATE),
			DIORITE_VARIANTS = PropertyVariant.create("variant", DIORITE_POLISHED, DIORITE_PILLAR, DIORITE_BRICKS, DIORITE_ORNATE, DIORITE_PRISMATIC, DIORITE_TILES_SMALL),
			DIRT_VARIANTS = PropertyVariant.create("variant", DIRT_BRICKS_DISARRAY, DIRT_NETHER, DIRT_BRICKS, DIRT_COBBLE, DIRT_COBBLE_REINFORCED, DIRT_REINFORCED, DIRT_HAPPY, DIRT_BRICKS_LARGE, DIRT_BRICKS_LARGE_ON, DIRT_HORIZONTAL, DIRT_VERTICAL, DIRT_LAYERS, DIRT_CRUMBLING),
			EMERALD_VARIANTS = PropertyVariant.create("variant", EMERALD_PANEL, EMERALD_PANEL_CLASSIC, EMERALD_SMOOTH, EMERALD_CHUNK, EMERALD_ORNATE_LAYER, EMERALD_ZELDA, EMERALD_CELL, EMERALD_BISMUTH, EMERALD_BLOCKS_SMALL, EMERALD_BLOCKS_SMALL_ORNATE, EMERALD_ORNATE),
			ENERGISED_VOIDSTONE_VARIANTS = PropertyVariant.create("variant", ENERGISED_VOIDSTONE_RAW, ENERGISED_VOIDSTONE_TILES, ENERGISED_VOIDSTONE_SMOOTH, ENERGISED_VOIDSTONE_SKULL, ENERGISED_VOIDSTONE_RUNIC, ENERGISED_VOIDSTONE_METAL, ENERGISED_VOIDSTONE_EYE, ENERGISED_VOIDSTONE_BEVEL),
			ENERGISED_VOIDSTONE_PILLAR_VARIANTS = PropertyVariant.create("variant", ENERGISED_VOIDSTONE_PILLAR_NORMAL),
			FACTORY_VARIANTS = PropertyVariant.create("variant", FACTORY_RUSTY_DOTTED, FACTORY_RUSTY_PLATE, FACTORY_RUSTY_VERY, FACTORY_RUSTY_LITTLE, FACTORY_WIREFRAME, FACTORY_WIREFRAME_PURPLE, FACTORY_HAZARD_YELLOW, FACTORY_HAZARD_ORANGE, FACTORY_CIRCUIT_FANCY, FACTORY_METAL, FACTORY_GOLD_CIRCUIT, FACTORY_GOLD_PURPLE, FACTORY_CONSTRUCTION, FACTORY_VENT_WORN, FACTORY_RUSTY_PLATE, FACTORY_COLUMN, FACTORY_BLUE, FACTORY_VENT_VERTICAL, FACTORY_CIRCUIT_BLUE, FACTORY_WIREFRAME_BLUE);


	public static final PropertyVariant LIMESTONE_VARIANTS = PropertyVariant.create("variant", LIMESTONE_RAW, LIMESTONE_TILES, LIMESTONE_TILES_FRENCH, LIMESTONE_TILES_FRENCH_LIGHT, LIMESTONE_TILES_CREEPER, LIMESTONE_TILES_DAMAGED, LIMESTONE_TILES_LARGE, LIMESTONE_BRICKS, LIMESTONE_SMOOTH, LIMESTONE_PANEL_ORNATE, LIMESTONE_PANEL_ENGRAVED, LIMESTONE_PANEL_CREEPER, LIMESTONE_PANEL_LIGHT, LIMESTONE_PANEL_DARK, LIMESTONE_PANEL, LIMESTONE_DENT);

	public static final PropertyVariant MARBLE_VARIANTS = PropertyVariant.create("variant", MARBLE_RAW, MARBLE_BRICK, MARBLE_PANEL_CLASSIC, MARBLE_PANEL_ORNATE, MARBLE_PANEL, MARBLE_BLOCK, MARBLE_CREEPER_DARK, MARBLE_CREEPER_LIGHT, MARBLE_CARVED, MARBLE_CARVED_RADIAL, MARBLE_DENT, MARBLE_DENT_LARGE, MARBLE_TILES, MARBLE_TILES_ARRANGED, MARBLE_TILES_FANCY, MARBLE_BLOCKS);

	public static final PropertyVariant PUMPKINS_VARIANTS = PropertyVariant.create("variant", PUMPKIN_0, PUMPKIN_1, PUMPKIN_2, PUMPKIN_3, PUMPKIN_4, PUMPKIN_5, PUMPKIN_6, PUMPKIN_7, PUMPKIN_8, PUMPKIN_9, PUMPKIN_10, PUMPKIN_11, PUMPKIN_12, PUMPKIN_13, PUMPKIN_14, PUMPKIN_15, PUMPKIN_16);
	public static final PropertyVariant JACKOLANTERN_VARIANTS = PropertyVariant.create("variant", LITPUMPKIN_0, LITPUMPKIN_1, LITPUMPKIN_2, LITPUMPKIN_3, LITPUMPKIN_4, LITPUMPKIN_5, LITPUMPKIN_6, LITPUMPKIN_7, LITPUMPKIN_8, LITPUMPKIN_9, LITPUMPKIN_10, LITPUMPKIN_11, LITPUMPKIN_12, LITPUMPKIN_13, LITPUMPKIN_14, LITPUMPKIN_15, LITPUMPKIN_16);
}
